// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package emiratesservice.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the EmiratesService module
	public static java.lang.String aCT_APIAmmendmentService(IContext context, system.proxies.HttpRequest _httpRequest, system.proxies.HttpResponse _httpResponse, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("httpRequest", _httpRequest == null ? null : _httpRequest.getMendixObject());
		params.put("httpResponse", _httpResponse == null ? null : _httpResponse.getMendixObject());
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		return (java.lang.String) Core.microflowCall("EmiratesService.ACT_APIAmmendmentService").withParams(params).execute(context);
	}
	public static java.lang.String aCT_APIMakePayment(IContext context, system.proxies.HttpRequest _httpRequest, system.proxies.HttpResponse _httpResponse, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("httpRequest", _httpRequest == null ? null : _httpRequest.getMendixObject());
		params.put("httpResponse", _httpResponse == null ? null : _httpResponse.getMendixObject());
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		return (java.lang.String) Core.microflowCall("EmiratesService.ACT_APIMakePayment").withParams(params).execute(context);
	}
	public static java.lang.String aCT_APINewBornCertificate(IContext context, system.proxies.HttpRequest _httpRequest, system.proxies.HttpResponse _httpResponse, myfirstmodule.proxies.BirthNotification _body)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("httpRequest", _httpRequest == null ? null : _httpRequest.getMendixObject());
		params.put("httpResponse", _httpResponse == null ? null : _httpResponse.getMendixObject());
		params.put("body", _body == null ? null : _body.getMendixObject());
		return (java.lang.String) Core.microflowCall("EmiratesService.ACT_APINewBornCertificate").withParams(params).execute(context);
	}
	public static emiratesservice.proxies.Validation aCT_CommitBirthNotificationAndStartWorkflow(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("EmiratesService.ACT_CommitBirthNotificationAndStartWorkflow").withParams(params).execute(context);
		return result == null ? null : emiratesservice.proxies.Validation.initialize(context, result);
	}
	public static myfirstmodule.proxies.Attachments aCT_GetAddtachmentsByNotificationNumber(IContext context, system.proxies.HttpRequest _httpRequest, system.proxies.HttpResponse _httpResponse, java.lang.String _notificationNumber, java.lang.Long _fileID)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("httpRequest", _httpRequest == null ? null : _httpRequest.getMendixObject());
		params.put("httpResponse", _httpResponse == null ? null : _httpResponse.getMendixObject());
		params.put("NotificationNumber", _notificationNumber);
		params.put("FileID", _fileID);
		IMendixObject result = (IMendixObject)Core.microflowCall("EmiratesService.ACT_GetAddtachmentsByNotificationNumber").withParams(params).execute(context);
		return result == null ? null : myfirstmodule.proxies.Attachments.initialize(context, result);
	}
	public static java.lang.String aCT_GetGenderEnumeration(IContext context, system.proxies.HttpRequest _httpRequest, system.proxies.HttpResponse _httpResponse)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("httpRequest", _httpRequest == null ? null : _httpRequest.getMendixObject());
		params.put("httpResponse", _httpResponse == null ? null : _httpResponse.getMendixObject());
		return (java.lang.String) Core.microflowCall("EmiratesService.ACT_GetGenderEnumeration").withParams(params).execute(context);
	}
	public static java.lang.String aCT_GetMartialStatusEnumeration(IContext context, system.proxies.HttpRequest _httpRequest, system.proxies.HttpResponse _httpResponse)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("httpRequest", _httpRequest == null ? null : _httpRequest.getMendixObject());
		params.put("httpResponse", _httpResponse == null ? null : _httpResponse.getMendixObject());
		return (java.lang.String) Core.microflowCall("EmiratesService.ACT_GetMartialStatusEnumeration").withParams(params).execute(context);
	}
	public static java.lang.String aCT_GetNationalityEnumerationData(IContext context, system.proxies.HttpRequest _httpRequest, system.proxies.HttpResponse _httpResponse)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("httpRequest", _httpRequest == null ? null : _httpRequest.getMendixObject());
		params.put("httpResponse", _httpResponse == null ? null : _httpResponse.getMendixObject());
		return (java.lang.String) Core.microflowCall("EmiratesService.ACT_GetNationalityEnumerationData").withParams(params).execute(context);
	}
	public static java.lang.String aCT_GetNotificationTypeEnumeration(IContext context, system.proxies.HttpRequest _httpRequest, system.proxies.HttpResponse _httpResponse)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("httpRequest", _httpRequest == null ? null : _httpRequest.getMendixObject());
		params.put("httpResponse", _httpResponse == null ? null : _httpResponse.getMendixObject());
		return (java.lang.String) Core.microflowCall("EmiratesService.ACT_GetNotificationTypeEnumeration").withParams(params).execute(context);
	}
	public static java.lang.String aCT_GetPlaceOfBirthEnumeration(IContext context, system.proxies.HttpRequest _httpRequest, system.proxies.HttpResponse _httpResponse)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("httpRequest", _httpRequest == null ? null : _httpRequest.getMendixObject());
		params.put("httpResponse", _httpResponse == null ? null : _httpResponse.getMendixObject());
		return (java.lang.String) Core.microflowCall("EmiratesService.ACT_GetPlaceOfBirthEnumeration").withParams(params).execute(context);
	}
	public static java.lang.String aCT_GetPlaceOfBirthMD(IContext context, system.proxies.HttpRequest _httpRequest, system.proxies.HttpResponse _httpResponse)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("httpRequest", _httpRequest == null ? null : _httpRequest.getMendixObject());
		params.put("httpResponse", _httpResponse == null ? null : _httpResponse.getMendixObject());
		return (java.lang.String) Core.microflowCall("EmiratesService.ACT_GetPlaceOfBirthMD").withParams(params).execute(context);
	}
	public static java.lang.String aCT_GetPlaceOfBirthPU(IContext context, system.proxies.HttpRequest _httpRequest, system.proxies.HttpResponse _httpResponse)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("httpRequest", _httpRequest == null ? null : _httpRequest.getMendixObject());
		params.put("httpResponse", _httpResponse == null ? null : _httpResponse.getMendixObject());
		return (java.lang.String) Core.microflowCall("EmiratesService.ACT_GetPlaceOfBirthPU").withParams(params).execute(context);
	}
	public static java.lang.String aCT_GetRelegionEnumeration(IContext context, system.proxies.HttpRequest _httpRequest, system.proxies.HttpResponse _httpResponse)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("httpRequest", _httpRequest == null ? null : _httpRequest.getMendixObject());
		params.put("httpResponse", _httpResponse == null ? null : _httpResponse.getMendixObject());
		return (java.lang.String) Core.microflowCall("EmiratesService.ACT_GetRelegionEnumeration").withParams(params).execute(context);
	}
	public static void aCT_SaveBirthAndAmmend(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("EmiratesService.ACT_SaveBirthAndAmmend").withParams(params).execute(context);
	}
	public static java.util.List<myfirstmodule.proxies.BirthNotification> birthNotification_Get_All(IContext context, system.proxies.HttpResponse _httpResponse)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("HttpResponse", _httpResponse == null ? null : _httpResponse.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("EmiratesService.BirthNotification_Get_All").withParams(params).execute(context);
		java.util.List<myfirstmodule.proxies.BirthNotification> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(myfirstmodule.proxies.BirthNotification.initialize(context, obj));
		}
		return result;
	}
	public static myfirstmodule.proxies.BirthNotification birthNotification_Get_ByKey(IContext context, system.proxies.HttpResponse _httpResponse, java.lang.String _notificationnumber)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("httpResponse", _httpResponse == null ? null : _httpResponse.getMendixObject());
		params.put("notificationnumber", _notificationnumber);
		IMendixObject result = (IMendixObject)Core.microflowCall("EmiratesService.BirthNotification_Get_ByKey").withParams(params).execute(context);
		return result == null ? null : myfirstmodule.proxies.BirthNotification.initialize(context, result);
	}
	public static void birthNotification_Post(IContext context, system.proxies.HttpResponse _httpResponse, myfirstmodule.proxies.BirthNotification _body)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("httpResponse", _httpResponse == null ? null : _httpResponse.getMendixObject());
		params.put("body", _body == null ? null : _body.getMendixObject());
		Core.microflowCall("EmiratesService.BirthNotification_Post").withParams(params).execute(context);
	}
	public static void certificate_Attachment(IContext context, emiratesservice.proxies.Root _root)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Root", _root == null ? null : _root.getMendixObject());
		Core.microflowCall("EmiratesService.Certificate_Attachment").withParams(params).execute(context);
	}
	public static java.util.List<emiratesservice.proxies.JsonObject> childConsume(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("EmiratesService.ChildConsume").withParams(params).execute(context);
		java.util.List<emiratesservice.proxies.JsonObject> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(emiratesservice.proxies.JsonObject.initialize(context, obj));
		}
		return result;
	}
	public static system.proxies.HttpResponse getEmirates(IContext context, system.proxies.HttpRequest _httpRequest, java.lang.String _emiratesID)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("httpRequest", _httpRequest == null ? null : _httpRequest.getMendixObject());
		params.put("EmiratesID", _emiratesID);
		IMendixObject result = (IMendixObject)Core.microflowCall("EmiratesService.GetEmirates").withParams(params).execute(context);
		return result == null ? null : system.proxies.HttpResponse.initialize(context, result);
	}
	public static emiratesservice.proxies.Validation sUB_Validattions(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification, emiratesservice.proxies.Validation _validation)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		params.put("Validation", _validation == null ? null : _validation.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("EmiratesService.SUB_Validattions").withParams(params).execute(context);
		return result == null ? null : emiratesservice.proxies.Validation.initialize(context, result);
	}
}