// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package consumeemiratesservices.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	// These are the microflows for the ConsumeEmiratesServices module
	public static void aCT_ConsumeEmirates(IContext context, consumeemiratesservices.proxies.Details _details)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Details", _details == null ? null : _details.getMendixObject());
		Core.microflowCall("ConsumeEmiratesServices.ACT_ConsumeEmirates").withParams(params).execute(context);
	}
}