// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the MyFirstModule module
	public static void account_excel_export(IContext context, administration.proxies.Account _account)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Account", _account == null ? null : _account.getMendixObject());
		Core.microflowCall("MyFirstModule.Account_excel_export").withParams(params).execute(context);
	}
	public static void act_AmendCertificate_Submit(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.Act_AmendCertificate_Submit").withParams(params).execute(context);
	}
	public static void act_AmendmentPayment(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.Act_AmendmentPayment").withParams(params).execute(context);
	}
	public static void aCT_ArabicCopyMinus(IContext context, myfirstmodule.proxies.BirthCerticate _birthCerticate)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthCerticate", _birthCerticate == null ? null : _birthCerticate.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_ArabicCopyMinus").withParams(params).execute(context);
	}
	public static void aCT_ArabicCopyPlus(IContext context, myfirstmodule.proxies.BirthCerticate _birthCerticate)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthCerticate", _birthCerticate == null ? null : _birthCerticate.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_ArabicCopyPlus").withParams(params).execute(context);
	}
	public static void aCT_BackfromReview(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_BackfromReview").withParams(params).execute(context);
	}
	public static void aCT_BacktoCertificate(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_BacktoCertificate").withParams(params).execute(context);
	}
	public static void aCT_Backtoparent_Certifi(IContext context, myfirstmodule.proxies.BirthCerticate _birthCerticate)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthCerticate", _birthCerticate == null ? null : _birthCerticate.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_Backtoparent_Certifi").withParams(params).execute(context);
	}
	public static boolean aCT_BirthCertificateReport(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		return (java.lang.Boolean) Core.microflowCall("MyFirstModule.ACT_BirthCertificateReport").withParams(params).execute(context);
	}
	public static boolean aCT_BirthNotificationReport(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		return (java.lang.Boolean) Core.microflowCall("MyFirstModule.ACT_BirthNotificationReport").withParams(params).execute(context);
	}
	public static void aCT_CalendarView(IContext context, myfirstmodule.proxies.Calendar _calender)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Calender", _calender == null ? null : _calender.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_CalendarView").withParams(params).execute(context);
	}
	public static void aCT_Calender(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("MyFirstModule.ACT_Calender").withParams(params).execute(context);
	}
	public static void aCT_cancel_notifiication(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_cancel_notifiication").withParams(params).execute(context);
	}
	public static void aCT_cancel_notifiication_2(IContext context, myfirstmodule.proxies.BirthCerticate _birthCerticate)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthCerticate", _birthCerticate == null ? null : _birthCerticate.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_cancel_notifiication_2").withParams(params).execute(context);
	}
	public static void aCT_ChangeBirth_MD(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_ChangeBirth_MD").withParams(params).execute(context);
	}
	public static void aCT_ChangeBirth_PU(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_ChangeBirth_PU").withParams(params).execute(context);
	}
	public static void aCT_ChangeLanguage(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("MyFirstModule.ACT_ChangeLanguage").withParams(params).execute(context);
	}
	public static void aCT_ChangeMotherDetails(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_ChangeMotherDetails").withParams(params).execute(context);
	}
	public static void aCT_ChangeNameOfTheHospital(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_ChangeNameOfTheHospital").withParams(params).execute(context);
	}
	public static void aCT_ChangePassword(IContext context, administration.proxies.Account _account)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Account", _account == null ? null : _account.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_ChangePassword").withParams(params).execute(context);
	}
	public static void aCT_ClickGood1(IContext context, myfirstmodule.proxies.HappinessMeter _happinessMeter)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("HappinessMeter", _happinessMeter == null ? null : _happinessMeter.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_ClickGood1").withParams(params).execute(context);
	}
	public static void aCT_ClickGood1_2(IContext context, myfirstmodule.proxies.HappinessMeter _happinessMeter)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("HappinessMeter", _happinessMeter == null ? null : _happinessMeter.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_ClickGood1_2").withParams(params).execute(context);
	}
	public static void aCT_ClickGood1_3(IContext context, myfirstmodule.proxies.HappinessMeter _happinessMeter)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("HappinessMeter", _happinessMeter == null ? null : _happinessMeter.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_ClickGood1_3").withParams(params).execute(context);
	}
	public static void aCT_ClickGood1_4(IContext context, myfirstmodule.proxies.HappinessMeter _happinessMeter)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("HappinessMeter", _happinessMeter == null ? null : _happinessMeter.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_ClickGood1_4").withParams(params).execute(context);
	}
	public static void aCT_ClickNotGood1(IContext context, myfirstmodule.proxies.HappinessMeter _happinessMeter)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("HappinessMeter", _happinessMeter == null ? null : _happinessMeter.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_ClickNotGood1").withParams(params).execute(context);
	}
	public static void aCT_ClickNotGood1_2(IContext context, myfirstmodule.proxies.HappinessMeter _happinessMeter)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("HappinessMeter", _happinessMeter == null ? null : _happinessMeter.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_ClickNotGood1_2").withParams(params).execute(context);
	}
	public static void aCT_ClickNotGood1_3(IContext context, myfirstmodule.proxies.HappinessMeter _happinessMeter)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("HappinessMeter", _happinessMeter == null ? null : _happinessMeter.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_ClickNotGood1_3").withParams(params).execute(context);
	}
	public static void aCT_ClickNotGood1_4(IContext context, myfirstmodule.proxies.HappinessMeter _happinessMeter)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("HappinessMeter", _happinessMeter == null ? null : _happinessMeter.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_ClickNotGood1_4").withParams(params).execute(context);
	}
	public static void aCT_ClickOK1(IContext context, myfirstmodule.proxies.HappinessMeter _happinessMeter)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("HappinessMeter", _happinessMeter == null ? null : _happinessMeter.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_ClickOK1").withParams(params).execute(context);
	}
	public static void aCT_ClickOK1_2(IContext context, myfirstmodule.proxies.HappinessMeter _happinessMeter)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("HappinessMeter", _happinessMeter == null ? null : _happinessMeter.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_ClickOK1_2").withParams(params).execute(context);
	}
	public static void aCT_ClickOK1_3(IContext context, myfirstmodule.proxies.HappinessMeter _happinessMeter)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("HappinessMeter", _happinessMeter == null ? null : _happinessMeter.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_ClickOK1_3").withParams(params).execute(context);
	}
	public static void aCT_ClickOK1_4(IContext context, myfirstmodule.proxies.HappinessMeter _happinessMeter)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("HappinessMeter", _happinessMeter == null ? null : _happinessMeter.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_ClickOK1_4").withParams(params).execute(context);
	}
	public static void aCT_Close(IContext context, myfirstmodule.proxies.ContactUs _contactUs)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("ContactUs", _contactUs == null ? null : _contactUs.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_Close").withParams(params).execute(context);
	}
	public static void aCT_ClosePageAll(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_ClosePageAll").withParams(params).execute(context);
	}
	public static void aCT_ConsumeEmirates_father(IContext context, myfirstmodule.proxies.BirthNotification _details)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Details", _details == null ? null : _details.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_ConsumeEmirates_father").withParams(params).execute(context);
	}
	public static void aCT_ConsumeEmirates_mother(IContext context, myfirstmodule.proxies.BirthNotification _details)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Details", _details == null ? null : _details.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_ConsumeEmirates_mother").withParams(params).execute(context);
	}
	public static void aCT_ContinueToCertificate(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_ContinueToCertificate").withParams(params).execute(context);
	}
	public static void aCT_CopiesPayment(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_CopiesPayment").withParams(params).execute(context);
	}
	public static java.lang.String aCT_Create_Birth_CertificateNumber(IContext context, myfirstmodule.proxies.BirthNotification _birthCerticate)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthCerticate", _birthCerticate == null ? null : _birthCerticate.getMendixObject());
		return (java.lang.String) Core.microflowCall("MyFirstModule.ACT_Create_Birth_CertificateNumber").withParams(params).execute(context);
	}
	public static void aCT_Create_Birth_CertificateNumber_2(IContext context, myfirstmodule.proxies.BirthCerticate _birthCerticate)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthCerticate", _birthCerticate == null ? null : _birthCerticate.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_Create_Birth_CertificateNumber_2").withParams(params).execute(context);
	}
	public static void aCT_Create_Birth_NotificationNumber(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_Create_Birth_NotificationNumber").withParams(params).execute(context);
	}
	public static myfirstmodule.proxies.search act_create_search(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("MyFirstModule.Act_create_search").withParams(params).execute(context);
		return result == null ? null : myfirstmodule.proxies.search.initialize(context, result);
	}
	public static void aCT_CreateBirthNotification(IContext context, myfirstmodule.proxies.Service _service)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Service", _service == null ? null : _service.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_CreateBirthNotification").withParams(params).execute(context);
	}
	public static void aCT_CreateCertificateDetails(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_CreateCertificateDetails").withParams(params).execute(context);
	}
	public static void aCT_CreateFatherDetails(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_CreateFatherDetails").withParams(params).execute(context);
	}
	public static void aCT_CreateInfants(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_CreateInfants").withParams(params).execute(context);
	}
	public static void aCT_CreateMotherDetails(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_CreateMotherDetails").withParams(params).execute(context);
	}
	public static void aCT_Createobj_Circular(IContext context, myfirstmodule.proxies.Circulars _circulars)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Circulars", _circulars == null ? null : _circulars.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_Createobj_Circular").withParams(params).execute(context);
	}
	public static void aCT_CreateSibiling(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_CreateSibiling").withParams(params).execute(context);
	}
	public static void aCT_CSDOfficer_NeedComittee(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_CSDOfficer_NeedComittee").withParams(params).execute(context);
	}
	public static void aCT_CSDOfficer_Return(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_CSDOfficer_Return").withParams(params).execute(context);
	}
	public static void aCT_DeleteInfant(IContext context, myfirstmodule.proxies.Infant _infant, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Infant", _infant == null ? null : _infant.getMendixObject());
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_DeleteInfant").withParams(params).execute(context);
	}
	public static void aCT_DeleteSibiling(IContext context, myfirstmodule.proxies.Sibilings _sibilings, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Sibilings", _sibilings == null ? null : _sibilings.getMendixObject());
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_DeleteSibiling").withParams(params).execute(context);
	}
	public static void aCT_DOHLegal_Accept(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_DOHLegal_Accept").withParams(params).execute(context);
	}
	public static void aCT_DOHLegal_Returned(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_DOHLegal_Returned").withParams(params).execute(context);
	}
	public static void act_Edit_notification(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.Act_Edit_notification").withParams(params).execute(context);
	}
	public static void aCT_EditAddedInfants(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_EditAddedInfants").withParams(params).execute(context);
	}
	public static void aCT_EditApplicationDetails(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_EditApplicationDetails").withParams(params).execute(context);
	}
	public static void aCT_EditCertificatecopies(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_EditCertificatecopies").withParams(params).execute(context);
	}
	public static void aCT_EditCertificateDetails(IContext context, myfirstmodule.proxies.BirthCerticate _birthCerticate, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthCerticate", _birthCerticate == null ? null : _birthCerticate.getMendixObject());
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_EditCertificateDetails").withParams(params).execute(context);
	}
	public static void aCT_editFatherDetails(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_editFatherDetails").withParams(params).execute(context);
	}
	public static void aCT_EditMedicalDetails(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_EditMedicalDetails").withParams(params).execute(context);
	}
	public static void aCT_EditMotherDetails(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_EditMotherDetails").withParams(params).execute(context);
	}
	public static void aCT_EngCopyMinus(IContext context, myfirstmodule.proxies.BirthCerticate _birthCerticate)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthCerticate", _birthCerticate == null ? null : _birthCerticate.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_EngCopyMinus").withParams(params).execute(context);
	}
	public static void aCT_EngCopyPlus(IContext context, myfirstmodule.proxies.BirthCerticate _birthCerticate)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthCerticate", _birthCerticate == null ? null : _birthCerticate.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_EngCopyPlus").withParams(params).execute(context);
	}
	public static myfirstmodule.proxies.Count aCT_ExternalUser_Dashboard(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("MyFirstModule.ACT_ExternalUser_Dashboard").withParams(params).execute(context);
		return result == null ? null : myfirstmodule.proxies.Count.initialize(context, result);
	}
	public static void aCT_Feedback(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("MyFirstModule.ACT_Feedback").withParams(params).execute(context);
	}
	public static void aCT_Generate_PaymentDocument(IContext context, myfirstmodule.proxies.BirthCerticate _birthCerticate)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthCerticate", _birthCerticate == null ? null : _birthCerticate.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_Generate_PaymentDocument").withParams(params).execute(context);
	}
	public static void aCT_Generate_PaymentDocument_2(IContext context, myfirstmodule.proxies.Payment _payment)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Payment", _payment == null ? null : _payment.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_Generate_PaymentDocument_2").withParams(params).execute(context);
	}
	public static void aCT_GenerateCertificate(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_GenerateCertificate").withParams(params).execute(context);
	}
	public static void aCT_GenerateCertificate_2(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_GenerateCertificate_2").withParams(params).execute(context);
	}
	public static java.lang.String aCT_GetArabicTranslation(IContext context, java.lang.String _string)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("string", _string);
		return (java.lang.String) Core.microflowCall("MyFirstModule.ACT_GetArabicTranslation").withParams(params).execute(context);
	}
	public static void aCT_GetCurrentProfile(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("MyFirstModule.ACT_GetCurrentProfile").withParams(params).execute(context);
	}
	public static administration.proxies.Account aCT_GetCurrentUser(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("MyFirstModule.ACT_GetCurrentUser").withParams(params).execute(context);
		return result == null ? null : administration.proxies.Account.initialize(context, result);
	}
	public static administration.proxies.Account aCT_GetCurrentUserProfile(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("MyFirstModule.ACT_GetCurrentUserProfile").withParams(params).execute(context);
		return result == null ? null : administration.proxies.Account.initialize(context, result);
	}
	public static myfirstmodule.proxies.Greetings_Message aCT_Greetings_Message(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("MyFirstModule.ACT_Greetings_Message").withParams(params).execute(context);
		return result == null ? null : myfirstmodule.proxies.Greetings_Message.initialize(context, result);
	}
	public static myfirstmodule.proxies.Help aCT_help(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("MyFirstModule.ACT_help").withParams(params).execute(context);
		return result == null ? null : myfirstmodule.proxies.Help.initialize(context, result);
	}
	public static myfirstmodule.proxies.Count aCT_InternalUser_Dashboard(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("MyFirstModule.ACT_InternalUser_Dashboard").withParams(params).execute(context);
		return result == null ? null : myfirstmodule.proxies.Count.initialize(context, result);
	}
	public static void aCT_MemberOne_Accept(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_MemberOne_Accept").withParams(params).execute(context);
	}
	public static void aCT_MemberOne_Return(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_MemberOne_Return").withParams(params).execute(context);
	}
	public static void aCT_NewBirthCertificate(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_NewBirthCertificate").withParams(params).execute(context);
	}
	public static void aCT_NewBorn_AddCertificate(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_NewBorn_AddCertificate").withParams(params).execute(context);
	}
	public static void aCT_NewBornBirthCertificate_Submit(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_NewBornBirthCertificate_Submit").withParams(params).execute(context);
	}
	public static void aCT_NextHappinessMeterPage(IContext context, myfirstmodule.proxies.HappinessMeter _happinessMeter)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("HappinessMeter", _happinessMeter == null ? null : _happinessMeter.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_NextHappinessMeterPage").withParams(params).execute(context);
	}
	public static void aCT_NotificationLinkClosePage(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_NotificationLinkClosePage").withParams(params).execute(context);
	}
	public static void aCT_NotificationLinkCreate(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_NotificationLinkCreate").withParams(params).execute(context);
	}
	public static void aCT_PaymentPage_Call(IContext context, myfirstmodule.proxies.BirthCerticate _birthCerticate)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthCerticate", _birthCerticate == null ? null : _birthCerticate.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_PaymentPage_Call").withParams(params).execute(context);
	}
	public static void aCT_PreviousPage(IContext context, myfirstmodule.proxies.HappinessMeter _happinessMeter)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("HappinessMeter", _happinessMeter == null ? null : _happinessMeter.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_PreviousPage").withParams(params).execute(context);
	}
	public static void aCT_Refresh(IContext context, administration.proxies.Account _account, myfirstmodule.proxies.Circulars _circulars)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Account", _account == null ? null : _account.getMendixObject());
		params.put("Circulars", _circulars == null ? null : _circulars.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_Refresh").withParams(params).execute(context);
	}
	public static void aCT_Resubmit_BirthNotification(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_Resubmit_BirthNotification").withParams(params).execute(context);
	}
	public static void aCT_SaveandSendCircular(IContext context, myfirstmodule.proxies.Circulars _circulars)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Circulars", _circulars == null ? null : _circulars.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_SaveandSendCircular").withParams(params).execute(context);
	}
	public static void aCT_SaveBirthNotification_Link(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_SaveBirthNotification_Link").withParams(params).execute(context);
	}
	public static void aCT_SaveDratNotification(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_SaveDratNotification").withParams(params).execute(context);
	}
	public static void aCT_SaveProfile(IContext context, myfirstmodule.proxies.Profile _profile)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Profile", _profile == null ? null : _profile.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_SaveProfile").withParams(params).execute(context);
	}
	public static void aCT_SaveSignature(IContext context, myfirstmodule.proxies.Signature _signature)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Signature", _signature == null ? null : _signature.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_SaveSignature").withParams(params).execute(context);
	}
	public static void aCT_Search(IContext context, myfirstmodule.proxies.BirthSearch _birthSearch)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthSearch", _birthSearch == null ? null : _birthSearch.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_Search").withParams(params).execute(context);
	}
	public static void aCT_searchRefresh(IContext context, myfirstmodule.proxies.BirthSearch _birthSearch)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthSearch", _birthSearch == null ? null : _birthSearch.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_searchRefresh").withParams(params).execute(context);
	}
	public static void aCT_SelectReplacementService(IContext context, myfirstmodule.proxies.Service _service)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Service", _service == null ? null : _service.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_SelectReplacementService").withParams(params).execute(context);
	}
	public static void aCT_SendInquiry(IContext context, myfirstmodule.proxies.ContactUs _contactUs)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("ContactUs", _contactUs == null ? null : _contactUs.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_SendInquiry").withParams(params).execute(context);
	}
	public static void aCT_show_payment_page(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_show_payment_page").withParams(params).execute(context);
	}
	public static void aCT_ShowCalender(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("MyFirstModule.ACT_ShowCalender").withParams(params).execute(context);
	}
	public static void aCT_ShowContactUs(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("MyFirstModule.ACT_ShowContactUs").withParams(params).execute(context);
	}
	public static void aCT_ShowDOHDashboard(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("MyFirstModule.ACT_ShowDOHDashboard").withParams(params).execute(context);
	}
	public static void aCT_ShowHappinessMeter(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("MyFirstModule.ACT_ShowHappinessMeter").withParams(params).execute(context);
	}
	public static void aCT_SHowwizard_Step4_Certificate(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_SHowwizard_Step4_Certificate").withParams(params).execute(context);
	}
	public static void aCT_ShowWizardStep3_Certificate(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification, myfirstmodule.proxies.BirthCerticate _birthCerticate)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		params.put("BirthCerticate", _birthCerticate == null ? null : _birthCerticate.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_ShowWizardStep3_Certificate").withParams(params).execute(context);
	}
	public static void aCT_ShowWizardstepOne(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_ShowWizardstepOne").withParams(params).execute(context);
	}
	public static void aCT_ShowWizardstepThree_certificate(IContext context, myfirstmodule.proxies.BirthCerticate _birthCerticate, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthCerticate", _birthCerticate == null ? null : _birthCerticate.getMendixObject());
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_ShowWizardstepThree_certificate").withParams(params).execute(context);
	}
	public static void aCT_ShowWizardstepTwo(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_ShowWizardstepTwo").withParams(params).execute(context);
	}
	public static void aCT_SortBirthOrder(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_SortBirthOrder").withParams(params).execute(context);
	}
	public static void aCT_SubmitDocuments(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_SubmitDocuments").withParams(params).execute(context);
	}
	public static void aCT_upload_docs(IContext context, myfirstmodule.proxies.BirthCerticate _birthCerticate)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthCerticate", _birthCerticate == null ? null : _birthCerticate.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_upload_docs").withParams(params).execute(context);
	}
	public static void adPolice_complete(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification, system.proxies.WorkflowUserTask _workflowUserTask)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		params.put("WorkflowUserTask", _workflowUserTask == null ? null : _workflowUserTask.getMendixObject());
		Core.microflowCall("MyFirstModule.AdPolice_complete").withParams(params).execute(context);
	}
	public static void adPolice_return(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification, system.proxies.WorkflowUserTask _workflowUserTask)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		params.put("WorkflowUserTask", _workflowUserTask == null ? null : _workflowUserTask.getMendixObject());
		Core.microflowCall("MyFirstModule.AdPolice_return").withParams(params).execute(context);
	}
	public static void amendment_Payment(IContext context, myfirstmodule.proxies.BirthCerticate _birthCerticate)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthCerticate", _birthCerticate == null ? null : _birthCerticate.getMendixObject());
		Core.microflowCall("MyFirstModule.Amendment_Payment").withParams(params).execute(context);
	}
	public static void aSU_CreateGreeting_Startup(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("MyFirstModule.ASU_CreateGreeting_Startup").withParams(params).execute(context);
	}
	public static boolean aSU_Startup_Microflow(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		return (java.lang.Boolean) Core.microflowCall("MyFirstModule.ASU_Startup_Microflow").withParams(params).execute(context);
	}
	public static boolean bCO_Audit_trail_account(IContext context, administration.proxies.Account _account)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Account", _account == null ? null : _account.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("MyFirstModule.BCO_Audit_trail_account").withParams(params).execute(context);
	}
	public static boolean bDE_audit_trail_account(IContext context, administration.proxies.Account _account)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Account", _account == null ? null : _account.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("MyFirstModule.BDE_audit_trail_account").withParams(params).execute(context);
	}
	public static void birth_excel_export_(IContext context, myfirstmodule.proxies.BirthNotification _birth)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("birth", _birth == null ? null : _birth.getMendixObject());
		Core.microflowCall("MyFirstModule.Birth_excel_export_").withParams(params).execute(context);
	}
	public static java.util.Date cAL_Hijri_Calendar(IContext context, myfirstmodule.proxies.Infant _infant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Infant", _infant == null ? null : _infant.getMendixObject());
		return (java.util.Date) Core.microflowCall("MyFirstModule.CAL_Hijri_Calendar").withParams(params).execute(context);
	}
	public static void chairman_complete(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification, system.proxies.WorkflowUserTask _workflowUserTask)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		params.put("WorkflowUserTask", _workflowUserTask == null ? null : _workflowUserTask.getMendixObject());
		Core.microflowCall("MyFirstModule.Chairman_complete").withParams(params).execute(context);
	}
	public static void chairman_INComplete(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification, system.proxies.WorkflowUserTask _workflowUserTask)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		params.put("WorkflowUserTask", _workflowUserTask == null ? null : _workflowUserTask.getMendixObject());
		Core.microflowCall("MyFirstModule.Chairman_INComplete").withParams(params).execute(context);
	}
	public static void chairman_Rejected(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification, system.proxies.WorkflowUserTask _workflowUserTask)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		params.put("WorkflowUserTask", _workflowUserTask == null ? null : _workflowUserTask.getMendixObject());
		Core.microflowCall("MyFirstModule.Chairman_Rejected").withParams(params).execute(context);
	}
	public static void count_Amount(IContext context, myfirstmodule.proxies.BirthCerticate _birthCerticate)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthCerticate", _birthCerticate == null ? null : _birthCerticate.getMendixObject());
		Core.microflowCall("MyFirstModule.Count_Amount").withParams(params).execute(context);
	}
	public static void csd_approve(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification, system.proxies.WorkflowUserTask _workflowUserTask)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		params.put("WorkflowUserTask", _workflowUserTask == null ? null : _workflowUserTask.getMendixObject());
		Core.microflowCall("MyFirstModule.csd_approve").withParams(params).execute(context);
	}
	public static void csd_incomplete(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification, system.proxies.WorkflowUserTask _workflowUserTask)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		params.put("WorkflowUserTask", _workflowUserTask == null ? null : _workflowUserTask.getMendixObject());
		Core.microflowCall("MyFirstModule.csd_incomplete").withParams(params).execute(context);
	}
	public static void csd_need_commitee(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification, system.proxies.WorkflowUserTask _workflowUserTask)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		params.put("WorkflowUserTask", _workflowUserTask == null ? null : _workflowUserTask.getMendixObject());
		Core.microflowCall("MyFirstModule.csd_need_commitee").withParams(params).execute(context);
	}
	public static system.proxies.Language currentUser_language(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("MyFirstModule.CurrentUser_language").withParams(params).execute(context);
		return result == null ? null : system.proxies.Language.initialize(context, result);
	}
	public static void dC_workflow_opentask(IContext context, workflowcommons.proxies.TaskCount _taskCount)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TaskCount", _taskCount == null ? null : _taskCount.getMendixObject());
		Core.microflowCall("MyFirstModule.DC_workflow_opentask").withParams(params).execute(context);
	}
	public static void dEL_Signature(IContext context, myfirstmodule.proxies.Profile _profile)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Profile", _profile == null ? null : _profile.getMendixObject());
		Core.microflowCall("MyFirstModule.DEL_Signature").withParams(params).execute(context);
	}
	public static boolean dS_(IContext context, myfirstmodule.proxies.Calendar _calender)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Calender", _calender == null ? null : _calender.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("MyFirstModule.DS_").withParams(params).execute(context);
	}
	public static void dS_Calender(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.DS_Calender").withParams(params).execute(context);
	}
	public static myfirstmodule.proxies.search dS_CreateWarnings(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("MyFirstModule.DS_CreateWarnings").withParams(params).execute(context);
		return result == null ? null : myfirstmodule.proxies.search.initialize(context, result);
	}
	public static java.util.List<myfirstmodule.proxies.Circulars> dS_FetchCirculars(IContext context, administration.proxies.Account _account)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Account", _account == null ? null : _account.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("MyFirstModule.DS_FetchCirculars").withParams(params).execute(context);
		java.util.List<myfirstmodule.proxies.Circulars> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(myfirstmodule.proxies.Circulars.initialize(context, obj));
		}
		return result;
	}
	public static java.util.List<myfirstmodule.proxies.BirthNotification> dS_Search(IContext context, myfirstmodule.proxies.BirthSearch _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("MyFirstModule.DS_Search").withParams(params).execute(context);
		java.util.List<myfirstmodule.proxies.BirthNotification> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(myfirstmodule.proxies.BirthNotification.initialize(context, obj));
		}
		return result;
	}
	public static void dS_SelectCertificateService(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("MyFirstModule.DS_SelectCertificateService").withParams(params).execute(context);
	}
	public static void dS_SelectNotificationService(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("MyFirstModule.DS_SelectNotificationService").withParams(params).execute(context);
	}
	public static myfirstmodule.proxies.BirthNotification dS_Workflow_GetBirthCertificateFlowContext(IContext context, system.proxies.Workflow _workflow)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Workflow", _workflow == null ? null : _workflow.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("MyFirstModule.DS_Workflow_GetBirthCertificateFlowContext").withParams(params).execute(context);
		return result == null ? null : myfirstmodule.proxies.BirthNotification.initialize(context, result);
	}
	public static java.util.List<system.proxies.WorkflowUserTask> dS_Workflow_usertask(IContext context, workflowcommons.proxies.TaskCount _taskCount)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TaskCount", _taskCount == null ? null : _taskCount.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("MyFirstModule.DS_Workflow_usertask").withParams(params).execute(context);
		java.util.List<system.proxies.WorkflowUserTask> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(system.proxies.WorkflowUserTask.initialize(context, obj));
		}
		return result;
	}
	public static myfirstmodule.proxies.BirthNotification dS_WorkflowUserTask_GetBirthCertificateFlowContext(IContext context, system.proxies.WorkflowUserTask _userTask)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("UserTask", _userTask == null ? null : _userTask.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("MyFirstModule.DS_WorkflowUserTask_GetBirthCertificateFlowContext").withParams(params).execute(context);
		return result == null ? null : myfirstmodule.proxies.BirthNotification.initialize(context, result);
	}
	public static void export_account_audit(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("MyFirstModule.Export_account_audit").withParams(params).execute(context);
	}
	public static system.proxies.HttpResponse getBirth(IContext context, system.proxies.HttpRequest _httpRequest)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("httpRequest", _httpRequest == null ? null : _httpRequest.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("MyFirstModule.GetBirth").withParams(params).execute(context);
		return result == null ? null : system.proxies.HttpResponse.initialize(context, result);
	}
	public static administration.proxies.Account getCurrentUser(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("MyFirstModule.GetCurrentUser").withParams(params).execute(context);
		return result == null ? null : administration.proxies.Account.initialize(context, result);
	}
	public static void legal_complete(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification, system.proxies.WorkflowUserTask _workflowUserTask)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		params.put("WorkflowUserTask", _workflowUserTask == null ? null : _workflowUserTask.getMendixObject());
		Core.microflowCall("MyFirstModule.Legal_complete").withParams(params).execute(context);
	}
	public static void legal_return(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification, system.proxies.WorkflowUserTask _workflowUserTask)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		params.put("WorkflowUserTask", _workflowUserTask == null ? null : _workflowUserTask.getMendixObject());
		Core.microflowCall("MyFirstModule.Legal_return").withParams(params).execute(context);
	}
	public static void m1_complete(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification, system.proxies.WorkflowUserTask _workflowUserTask)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		params.put("WorkflowUserTask", _workflowUserTask == null ? null : _workflowUserTask.getMendixObject());
		Core.microflowCall("MyFirstModule.m1_complete").withParams(params).execute(context);
	}
	public static void m1_INcomplet(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification, system.proxies.WorkflowUserTask _workflowUserTask)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		params.put("WorkflowUserTask", _workflowUserTask == null ? null : _workflowUserTask.getMendixObject());
		Core.microflowCall("MyFirstModule.m1_INcomplet").withParams(params).execute(context);
	}
	public static java.util.List<myfirstmodule.proxies.BirthNotification> microflow(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("MyFirstModule.Microflow").withParams(params).execute(context);
		java.util.List<myfirstmodule.proxies.BirthNotification> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(myfirstmodule.proxies.BirthNotification.initialize(context, obj));
		}
		return result;
	}
	public static void microflow_2(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.Microflow_2").withParams(params).execute(context);
	}
	public static void microflow_3(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("MyFirstModule.Microflow_3").withParams(params).execute(context);
	}
	public static void microflow_get_time(IContext context, system.proxies.WorkflowUserTask _workflowUserTask, workflowcommons.proxies.TaskCount _taskCount)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("WorkflowUserTask", _workflowUserTask == null ? null : _workflowUserTask.getMendixObject());
		params.put("TaskCount", _taskCount == null ? null : _taskCount.getMendixObject());
		Core.microflowCall("MyFirstModule.Microflow_get_time").withParams(params).execute(context);
	}
	public static java.util.List<myfirstmodule.proxies.BirthNotification> microflow_retrive_doctor_notifons(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("MyFirstModule.Microflow_retrive_doctor_notifons").withParams(params).execute(context);
		java.util.List<myfirstmodule.proxies.BirthNotification> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(myfirstmodule.proxies.BirthNotification.initialize(context, obj));
		}
		return result;
	}
	public static void notification_refresh(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.Notification_refresh").withParams(params).execute(context);
	}
	public static void oCH_FatherMartialStatus(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.OCH_FatherMartialStatus").withParams(params).execute(context);
	}
	public static void oCH_FatherReligion(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.OCH_FatherReligion").withParams(params).execute(context);
	}
	public static void oCH_FathersNationality(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.OCH_FathersNationality").withParams(params).execute(context);
	}
	public static void oCH_MotherMartialStatus(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.OCH_MotherMartialStatus").withParams(params).execute(context);
	}
	public static void oCH_MotherNationality(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.OCH_MotherNationality").withParams(params).execute(context);
	}
	public static void oCH_MotherReligion(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.OCH_MotherReligion").withParams(params).execute(context);
	}
	public static void oCH_netbank(IContext context, myfirstmodule.proxies.Payment _payment)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Payment", _payment == null ? null : _payment.getMendixObject());
		Core.microflowCall("MyFirstModule.OCH_netbank").withParams(params).execute(context);
	}
	public static void oCH_Noqodi(IContext context, myfirstmodule.proxies.Payment _payment)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Payment", _payment == null ? null : _payment.getMendixObject());
		Core.microflowCall("MyFirstModule.OCH_Noqodi").withParams(params).execute(context);
	}
	public static void oCH_NotificationType(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.OCH_NotificationType").withParams(params).execute(context);
	}
	public static void oCH_PlaceofBirth(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.OCH_PlaceofBirth").withParams(params).execute(context);
	}
	public static void oCH_PlaceofBirth_MD(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.OCH_PlaceofBirth_MD").withParams(params).execute(context);
	}
	public static void oCH_PlaceOfBirthPU(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.OCH_PlaceOfBirthPU").withParams(params).execute(context);
	}
	public static void onChange_card(IContext context, myfirstmodule.proxies.Payment _payment)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Payment", _payment == null ? null : _payment.getMendixObject());
		Core.microflowCall("MyFirstModule.OnChange_card").withParams(params).execute(context);
	}
	public static void print_certificate(IContext context, myfirstmodule.proxies.BirthCerticate _birthCerticate)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthCerticate", _birthCerticate == null ? null : _birthCerticate.getMendixObject());
		Core.microflowCall("MyFirstModule.Print_certificate").withParams(params).execute(context);
	}
	public static java.util.List<administration.proxies.Account> rET_Account(IContext context, myfirstmodule.proxies.Circulars _circulars)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Circulars", _circulars == null ? null : _circulars.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("MyFirstModule.RET_Account").withParams(params).execute(context);
		java.util.List<administration.proxies.Account> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(administration.proxies.Account.initialize(context, obj));
		}
		return result;
	}
	public static void rET_Account_(IContext context, myfirstmodule.proxies.Circulars _circulars)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Circulars", _circulars == null ? null : _circulars.getMendixObject());
		Core.microflowCall("MyFirstModule.RET_Account_").withParams(params).execute(context);
	}
	public static java.util.List<myfirstmodule.proxies.BirthNotification> rET_Achive_Notification(IContext context, myfirstmodule.proxies.search _search)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("search", _search == null ? null : _search.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("MyFirstModule.RET_Achive_Notification").withParams(params).execute(context);
		java.util.List<myfirstmodule.proxies.BirthNotification> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(myfirstmodule.proxies.BirthNotification.initialize(context, obj));
		}
		return result;
	}
	public static java.util.List<myfirstmodule.proxies.Calendar> rET_Calender(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("MyFirstModule.RET_Calender").withParams(params).execute(context);
		java.util.List<myfirstmodule.proxies.Calendar> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(myfirstmodule.proxies.Calendar.initialize(context, obj));
		}
		return result;
	}
	public static myfirstmodule.proxies.Profile rET_CurrentUserProfile(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("MyFirstModule.RET_CurrentUserProfile").withParams(params).execute(context);
		return result == null ? null : myfirstmodule.proxies.Profile.initialize(context, result);
	}
	public static java.util.List<emiratesservice.proxies.Enumerations> rET_Placeofbirth_md(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("MyFirstModule.RET_Placeofbirth_md").withParams(params).execute(context);
		java.util.List<emiratesservice.proxies.Enumerations> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(emiratesservice.proxies.Enumerations.initialize(context, obj));
		}
		return result;
	}
	public static void save_EmiratesDetails(IContext context, emiratesservice.proxies.Details _details)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Details", _details == null ? null : _details.getMendixObject());
		Core.microflowCall("MyFirstModule.Save_EmiratesDetails").withParams(params).execute(context);
	}
	public static myfirstmodule.proxies.Service services_Create(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("MyFirstModule.Services_Create").withParams(params).execute(context);
		return result == null ? null : myfirstmodule.proxies.Service.initialize(context, result);
	}
	public static void show__paid_message(IContext context, myfirstmodule.proxies.Payment _payment)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("payment", _payment == null ? null : _payment.getMendixObject());
		Core.microflowCall("MyFirstModule.Show__paid_message").withParams(params).execute(context);
	}
	public static void show_continue_edit_page(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.Show_continue_edit_page").withParams(params).execute(context);
	}
	public static void show_continue_without_certificate(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.Show_continue_without_certificate").withParams(params).execute(context);
	}
	public static myfirstmodule.proxies.Count sUB_CountCalender(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("MyFirstModule.SUB_CountCalender").withParams(params).execute(context);
		return result == null ? null : myfirstmodule.proxies.Count.initialize(context, result);
	}
	public static java.util.List<myfirstmodule.proxies.Document> sub_create_doc_list_acc(IContext context, administration.proxies.Account _account)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Account", _account == null ? null : _account.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("MyFirstModule.Sub_create_doc_list_acc").withParams(params).execute(context);
		java.util.List<myfirstmodule.proxies.Document> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(myfirstmodule.proxies.Document.initialize(context, obj));
		}
		return result;
	}
	public static java.util.List<myfirstmodule.proxies.Document> sub_create_doc_list_birth_notification(IContext context, myfirstmodule.proxies.BirthNotification _birth)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("birth", _birth == null ? null : _birth.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("MyFirstModule.Sub_create_doc_list_birth_notification").withParams(params).execute(context);
		java.util.List<myfirstmodule.proxies.Document> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(myfirstmodule.proxies.Document.initialize(context, obj));
		}
		return result;
	}
	public static void sUB_create_docs(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.SUB_create_docs").withParams(params).execute(context);
	}
	public static myfirstmodule.proxies.excel_ sub_excel_export_account(IContext context, administration.proxies.Account _account)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Account", _account == null ? null : _account.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("MyFirstModule.Sub_excel_export_account").withParams(params).execute(context);
		return result == null ? null : myfirstmodule.proxies.excel_.initialize(context, result);
	}
	public static myfirstmodule.proxies.excel_ sub_excel_export_birth(IContext context, myfirstmodule.proxies.BirthNotification _birth)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("birth", _birth == null ? null : _birth.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("MyFirstModule.Sub_excel_export_birth").withParams(params).execute(context);
		return result == null ? null : myfirstmodule.proxies.excel_.initialize(context, result);
	}
	public static void sUB_History_commitee_officers(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification, system.proxies.WorkflowUserTask _workflowUserTask)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		params.put("WorkflowUserTask", _workflowUserTask == null ? null : _workflowUserTask.getMendixObject());
		Core.microflowCall("MyFirstModule.SUB_History_commitee_officers").withParams(params).execute(context);
	}
	public static void sUB_History_CSD(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification, system.proxies.WorkflowUserTask _workflowUserTask)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		params.put("WorkflowUserTask", _workflowUserTask == null ? null : _workflowUserTask.getMendixObject());
		Core.microflowCall("MyFirstModule.SUB_History_CSD").withParams(params).execute(context);
	}
	public static void submit_fa(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.Submit_fa").withParams(params).execute(context);
	}
	public static emiratesservice.proxies.Validation submitting_birth_notification(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("MyFirstModule.Submitting_birth_notification").withParams(params).execute(context);
		return result == null ? null : emiratesservice.proxies.Validation.initialize(context, result);
	}
	public static void terminate(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification, system.proxies.WorkflowUserTask _workflowUserTask)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		params.put("WorkflowUserTask", _workflowUserTask == null ? null : _workflowUserTask.getMendixObject());
		Core.microflowCall("MyFirstModule.Terminate").withParams(params).execute(context);
	}
	public static void terminate_fa(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		Core.microflowCall("MyFirstModule.Terminate_fa").withParams(params).execute(context);
	}
	public static boolean vAL_Appedit(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("MyFirstModule.VAL_Appedit").withParams(params).execute(context);
	}
	public static boolean vAL_ContactUs(IContext context, myfirstmodule.proxies.ContactUs _contactUs)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("ContactUs", _contactUs == null ? null : _contactUs.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("MyFirstModule.VAL_ContactUs").withParams(params).execute(context);
	}
	public static boolean vAL_FatherDet(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("MyFirstModule.VAL_FatherDet").withParams(params).execute(context);
	}
	public static void vAL_InfantDet(IContext context, myfirstmodule.proxies.Infant _infant)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Infant", _infant == null ? null : _infant.getMendixObject());
		Core.microflowCall("MyFirstModule.VAL_InfantDet").withParams(params).execute(context);
	}
	public static boolean vAL_MotherDet(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("MyFirstModule.VAL_MotherDet").withParams(params).execute(context);
	}
	public static void vAL_Payment(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("MyFirstModule.VAL_Payment").withParams(params).execute(context);
	}
	public static void vAL_SibilingDet(IContext context, myfirstmodule.proxies.Sibilings _sibilings)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Sibilings", _sibilings == null ? null : _sibilings.getMendixObject());
		Core.microflowCall("MyFirstModule.VAL_SibilingDet").withParams(params).execute(context);
	}
	public static boolean validate_duplicate_notification(IContext context, myfirstmodule.proxies.BirthNotification _birthNotification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("BirthNotification", _birthNotification == null ? null : _birthNotification.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("MyFirstModule.Validate_duplicate_notification").withParams(params).execute(context);
	}
}