// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package xlsreport.proxies;

public enum DateTimePresentation
{
	mdyy(new java.lang.String[][] { new java.lang.String[] { "en_US", "m/d/yy" }, new java.lang.String[] { "ar_AE", "m/d/yy" } }),
	dmmmyy(new java.lang.String[][] { new java.lang.String[] { "en_US", "d-mmm-yy" }, new java.lang.String[] { "ar_AE", "d-mmm-yy" } }),
	mdyyhmm(new java.lang.String[][] { new java.lang.String[] { "en_US", "m/d/yy h:mm" }, new java.lang.String[] { "ar_AE", "m/d/yy h:mm" } }),
	ddmmyyyy(new java.lang.String[][] { new java.lang.String[] { "en_US", "dd-mm-yyyy" }, new java.lang.String[] { "ar_AE", "dd-mm-yyyy" } }),
	ddmmyyyyhhmm(new java.lang.String[][] { new java.lang.String[] { "en_US", "dd-mm-yyyy hh:mm" }, new java.lang.String[] { "ar_AE", "dd-mm-yyyy hh:mm" } }),
	mmddyyyy(new java.lang.String[][] { new java.lang.String[] { "en_US", "mm/dd/yyyy" }, new java.lang.String[] { "ar_AE", "mm/dd/yyyy" } }),
	mmddyyyyhhmm(new java.lang.String[][] { new java.lang.String[] { "en_US", "mm/dd/yyyy hh:mm" }, new java.lang.String[] { "ar_AE", "mm/dd/yyyy hh:mm" } }),
	custom(new java.lang.String[][] { new java.lang.String[] { "en_US", "custom format" }, new java.lang.String[] { "ar_AE", "تنسيق مخصص" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private DateTimePresentation(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
