// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package xlsreport.proxies;

public enum MxColor
{
	Blank(new java.lang.String[][] { new java.lang.String[] { "en_US", "None" }, new java.lang.String[] { "ar_AE", "لا أحد" } }),
	Black(new java.lang.String[][] { new java.lang.String[] { "en_US", "Black" }, new java.lang.String[] { "ar_AE", "أسود" } }),
	White(new java.lang.String[][] { new java.lang.String[] { "en_US", "White" }, new java.lang.String[] { "ar_AE", "أبيض" } }),
	Pink(new java.lang.String[][] { new java.lang.String[] { "en_US", "Pink" }, new java.lang.String[] { "ar_AE", "لون القرنفل" } }),
	Red(new java.lang.String[][] { new java.lang.String[] { "en_US", "Red" }, new java.lang.String[] { "ar_AE", "أحمر" } }),
	Orange(new java.lang.String[][] { new java.lang.String[] { "en_US", "Orange" }, new java.lang.String[] { "ar_AE", "البرتقالي" } }),
	Yellow(new java.lang.String[][] { new java.lang.String[] { "en_US", "Yellow" }, new java.lang.String[] { "ar_AE", "الأصفر" } }),
	Green(new java.lang.String[][] { new java.lang.String[] { "en_US", "Green" }, new java.lang.String[] { "ar_AE", "أخضر" } }),
	Light_Blue(new java.lang.String[][] { new java.lang.String[] { "en_US", "Light Blue" }, new java.lang.String[] { "ar_AE", "أزرق فاتح" } }),
	Blue(new java.lang.String[][] { new java.lang.String[] { "en_US", "Blue" }, new java.lang.String[] { "ar_AE", "أزرق" } }),
	Brown(new java.lang.String[][] { new java.lang.String[] { "en_US", "Brown" }, new java.lang.String[] { "ar_AE", "بني" } }),
	Gray_1(new java.lang.String[][] { new java.lang.String[] { "en_US", "Gray 25%" }, new java.lang.String[] { "ar_AE", "رمادي 25٪" } }),
	Gray_2(new java.lang.String[][] { new java.lang.String[] { "en_US", "Gray 40%" }, new java.lang.String[] { "ar_AE", "رمادي 40٪" } }),
	Gray_3(new java.lang.String[][] { new java.lang.String[] { "en_US", "Gray 50%" }, new java.lang.String[] { "ar_AE", "رمادي 50٪" } }),
	Gray_4(new java.lang.String[][] { new java.lang.String[] { "en_US", "Gray 80%" }, new java.lang.String[] { "ar_AE", "رمادي 80٪" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private MxColor(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
