// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Attachments extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Attachments";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Doc_name("Doc_name"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		Attachments_BirthNotification("MyFirstModule.Attachments_BirthNotification");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Attachments(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.Attachments"));
	}

	protected Attachments(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject attachmentsMendixObject)
	{
		super(context, attachmentsMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.Attachments", attachmentsMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.Attachments");
	}

	/**
	 * @deprecated Use 'Attachments.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.Attachments initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Attachments.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.Attachments initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Attachments(context, mendixObject);
	}

	public static myfirstmodule.proxies.Attachments load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Attachments.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Attachments> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.Attachments> result = new java.util.ArrayList<myfirstmodule.proxies.Attachments>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MyFirstModule.Attachments" + xpathConstraint))
			result.add(myfirstmodule.proxies.Attachments.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of Doc_name
	 */
	public final java.lang.String getDoc_name()
	{
		return getDoc_name(getContext());
	}

	/**
	 * @param context
	 * @return value of Doc_name
	 */
	public final java.lang.String getDoc_name(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Doc_name.toString());
	}

	/**
	 * Set value of Doc_name
	 * @param doc_name
	 */
	public final void setDoc_name(java.lang.String doc_name)
	{
		setDoc_name(getContext(), doc_name);
	}

	/**
	 * Set value of Doc_name
	 * @param context
	 * @param doc_name
	 */
	public final void setDoc_name(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String doc_name)
	{
		getMendixObject().setValue(context, MemberNames.Doc_name.toString(), doc_name);
	}

	/**
	 * @return value of Attachments_BirthNotification
	 */
	public final myfirstmodule.proxies.BirthNotification getAttachments_BirthNotification() throws com.mendix.core.CoreException
	{
		return getAttachments_BirthNotification(getContext());
	}

	/**
	 * @param context
	 * @return value of Attachments_BirthNotification
	 */
	public final myfirstmodule.proxies.BirthNotification getAttachments_BirthNotification(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.BirthNotification result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Attachments_BirthNotification.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.BirthNotification.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Attachments_BirthNotification
	 * @param attachments_birthnotification
	 */
	public final void setAttachments_BirthNotification(myfirstmodule.proxies.BirthNotification attachments_birthnotification)
	{
		setAttachments_BirthNotification(getContext(), attachments_birthnotification);
	}

	/**
	 * Set value of Attachments_BirthNotification
	 * @param context
	 * @param attachments_birthnotification
	 */
	public final void setAttachments_BirthNotification(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.BirthNotification attachments_birthnotification)
	{
		if (attachments_birthnotification == null)
			getMendixObject().setValue(context, MemberNames.Attachments_BirthNotification.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Attachments_BirthNotification.toString(), attachments_birthnotification.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Attachments that = (myfirstmodule.proxies.Attachments) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.Attachments";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
