// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class BirthCerticate
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject birthCerticateMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.BirthCerticate";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		TypeOfIssue("TypeOfIssue"),
		NoOfArabicCopies("NoOfArabicCopies"),
		NoOfEnglishCopies("NoOfEnglishCopies"),
		DeliverThroughEmiratesPost("DeliverThroughEmiratesPost"),
		CertificateNumber("CertificateNumber"),
		Recepient_Name("Recepient_Name"),
		EmiratesID("EmiratesID"),
		Payment_method("Payment_method"),
		Card_type("Card_type"),
		Card_no("Card_no"),
		Amount("Amount"),
		recepient_arabic_name("recepient_arabic_name"),
		BirthCerticate_BirthNotification("MyFirstModule.BirthCerticate_BirthNotification"),
		Payment_Docs_BirthCerticate("MyFirstModule.Payment_Docs_BirthCerticate"),
		Payment_BirthCerticate("MyFirstModule.Payment_BirthCerticate");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public BirthCerticate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.BirthCerticate"));
	}

	protected BirthCerticate(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject birthCerticateMendixObject)
	{
		if (birthCerticateMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.BirthCerticate", birthCerticateMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.BirthCerticate");

		this.birthCerticateMendixObject = birthCerticateMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'BirthCerticate.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.BirthCerticate initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.BirthCerticate.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.BirthCerticate initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.BirthCerticate(context, mendixObject);
	}

	public static myfirstmodule.proxies.BirthCerticate load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.BirthCerticate.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.BirthCerticate> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.BirthCerticate> result = new java.util.ArrayList<myfirstmodule.proxies.BirthCerticate>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MyFirstModule.BirthCerticate" + xpathConstraint))
			result.add(myfirstmodule.proxies.BirthCerticate.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of TypeOfIssue
	 */
	public final java.lang.String getTypeOfIssue()
	{
		return getTypeOfIssue(getContext());
	}

	/**
	 * @param context
	 * @return value of TypeOfIssue
	 */
	public final java.lang.String getTypeOfIssue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TypeOfIssue.toString());
	}

	/**
	 * Set value of TypeOfIssue
	 * @param typeofissue
	 */
	public final void setTypeOfIssue(java.lang.String typeofissue)
	{
		setTypeOfIssue(getContext(), typeofissue);
	}

	/**
	 * Set value of TypeOfIssue
	 * @param context
	 * @param typeofissue
	 */
	public final void setTypeOfIssue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String typeofissue)
	{
		getMendixObject().setValue(context, MemberNames.TypeOfIssue.toString(), typeofissue);
	}

	/**
	 * @return value of NoOfArabicCopies
	 */
	public final java.lang.Integer getNoOfArabicCopies()
	{
		return getNoOfArabicCopies(getContext());
	}

	/**
	 * @param context
	 * @return value of NoOfArabicCopies
	 */
	public final java.lang.Integer getNoOfArabicCopies(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.NoOfArabicCopies.toString());
	}

	/**
	 * Set value of NoOfArabicCopies
	 * @param noofarabiccopies
	 */
	public final void setNoOfArabicCopies(java.lang.Integer noofarabiccopies)
	{
		setNoOfArabicCopies(getContext(), noofarabiccopies);
	}

	/**
	 * Set value of NoOfArabicCopies
	 * @param context
	 * @param noofarabiccopies
	 */
	public final void setNoOfArabicCopies(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer noofarabiccopies)
	{
		getMendixObject().setValue(context, MemberNames.NoOfArabicCopies.toString(), noofarabiccopies);
	}

	/**
	 * @return value of NoOfEnglishCopies
	 */
	public final java.lang.Integer getNoOfEnglishCopies()
	{
		return getNoOfEnglishCopies(getContext());
	}

	/**
	 * @param context
	 * @return value of NoOfEnglishCopies
	 */
	public final java.lang.Integer getNoOfEnglishCopies(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.NoOfEnglishCopies.toString());
	}

	/**
	 * Set value of NoOfEnglishCopies
	 * @param noofenglishcopies
	 */
	public final void setNoOfEnglishCopies(java.lang.Integer noofenglishcopies)
	{
		setNoOfEnglishCopies(getContext(), noofenglishcopies);
	}

	/**
	 * Set value of NoOfEnglishCopies
	 * @param context
	 * @param noofenglishcopies
	 */
	public final void setNoOfEnglishCopies(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer noofenglishcopies)
	{
		getMendixObject().setValue(context, MemberNames.NoOfEnglishCopies.toString(), noofenglishcopies);
	}

	/**
	 * @return value of DeliverThroughEmiratesPost
	 */
	public final java.lang.Boolean getDeliverThroughEmiratesPost()
	{
		return getDeliverThroughEmiratesPost(getContext());
	}

	/**
	 * @param context
	 * @return value of DeliverThroughEmiratesPost
	 */
	public final java.lang.Boolean getDeliverThroughEmiratesPost(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.DeliverThroughEmiratesPost.toString());
	}

	/**
	 * Set value of DeliverThroughEmiratesPost
	 * @param deliverthroughemiratespost
	 */
	public final void setDeliverThroughEmiratesPost(java.lang.Boolean deliverthroughemiratespost)
	{
		setDeliverThroughEmiratesPost(getContext(), deliverthroughemiratespost);
	}

	/**
	 * Set value of DeliverThroughEmiratesPost
	 * @param context
	 * @param deliverthroughemiratespost
	 */
	public final void setDeliverThroughEmiratesPost(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean deliverthroughemiratespost)
	{
		getMendixObject().setValue(context, MemberNames.DeliverThroughEmiratesPost.toString(), deliverthroughemiratespost);
	}

	/**
	 * @return value of CertificateNumber
	 */
	public final java.lang.String getCertificateNumber()
	{
		return getCertificateNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of CertificateNumber
	 */
	public final java.lang.String getCertificateNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CertificateNumber.toString());
	}

	/**
	 * Set value of CertificateNumber
	 * @param certificatenumber
	 */
	public final void setCertificateNumber(java.lang.String certificatenumber)
	{
		setCertificateNumber(getContext(), certificatenumber);
	}

	/**
	 * Set value of CertificateNumber
	 * @param context
	 * @param certificatenumber
	 */
	public final void setCertificateNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String certificatenumber)
	{
		getMendixObject().setValue(context, MemberNames.CertificateNumber.toString(), certificatenumber);
	}

	/**
	 * @return value of Recepient_Name
	 */
	public final java.lang.String getRecepient_Name()
	{
		return getRecepient_Name(getContext());
	}

	/**
	 * @param context
	 * @return value of Recepient_Name
	 */
	public final java.lang.String getRecepient_Name(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Recepient_Name.toString());
	}

	/**
	 * Set value of Recepient_Name
	 * @param recepient_name
	 */
	public final void setRecepient_Name(java.lang.String recepient_name)
	{
		setRecepient_Name(getContext(), recepient_name);
	}

	/**
	 * Set value of Recepient_Name
	 * @param context
	 * @param recepient_name
	 */
	public final void setRecepient_Name(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String recepient_name)
	{
		getMendixObject().setValue(context, MemberNames.Recepient_Name.toString(), recepient_name);
	}

	/**
	 * @return value of EmiratesID
	 */
	public final java.lang.String getEmiratesID()
	{
		return getEmiratesID(getContext());
	}

	/**
	 * @param context
	 * @return value of EmiratesID
	 */
	public final java.lang.String getEmiratesID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EmiratesID.toString());
	}

	/**
	 * Set value of EmiratesID
	 * @param emiratesid
	 */
	public final void setEmiratesID(java.lang.String emiratesid)
	{
		setEmiratesID(getContext(), emiratesid);
	}

	/**
	 * Set value of EmiratesID
	 * @param context
	 * @param emiratesid
	 */
	public final void setEmiratesID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String emiratesid)
	{
		getMendixObject().setValue(context, MemberNames.EmiratesID.toString(), emiratesid);
	}

	/**
	 * Set value of Payment_method
	 * @param payment_method
	 */
	public final myfirstmodule.proxies.Enumeration_payment_method getPayment_method()
	{
		return getPayment_method(getContext());
	}

	/**
	 * @param context
	 * @return value of Payment_method
	 */
	public final myfirstmodule.proxies.Enumeration_payment_method getPayment_method(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Payment_method.toString());
		if (obj == null)
			return null;

		return myfirstmodule.proxies.Enumeration_payment_method.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Payment_method
	 * @param payment_method
	 */
	public final void setPayment_method(myfirstmodule.proxies.Enumeration_payment_method payment_method)
	{
		setPayment_method(getContext(), payment_method);
	}

	/**
	 * Set value of Payment_method
	 * @param context
	 * @param payment_method
	 */
	public final void setPayment_method(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Enumeration_payment_method payment_method)
	{
		if (payment_method != null)
			getMendixObject().setValue(context, MemberNames.Payment_method.toString(), payment_method.toString());
		else
			getMendixObject().setValue(context, MemberNames.Payment_method.toString(), null);
	}

	/**
	 * @return value of Card_type
	 */
	public final java.lang.String getCard_type()
	{
		return getCard_type(getContext());
	}

	/**
	 * @param context
	 * @return value of Card_type
	 */
	public final java.lang.String getCard_type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Card_type.toString());
	}

	/**
	 * Set value of Card_type
	 * @param card_type
	 */
	public final void setCard_type(java.lang.String card_type)
	{
		setCard_type(getContext(), card_type);
	}

	/**
	 * Set value of Card_type
	 * @param context
	 * @param card_type
	 */
	public final void setCard_type(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String card_type)
	{
		getMendixObject().setValue(context, MemberNames.Card_type.toString(), card_type);
	}

	/**
	 * @return value of Card_no
	 */
	public final java.lang.Integer getCard_no()
	{
		return getCard_no(getContext());
	}

	/**
	 * @param context
	 * @return value of Card_no
	 */
	public final java.lang.Integer getCard_no(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Card_no.toString());
	}

	/**
	 * Set value of Card_no
	 * @param card_no
	 */
	public final void setCard_no(java.lang.Integer card_no)
	{
		setCard_no(getContext(), card_no);
	}

	/**
	 * Set value of Card_no
	 * @param context
	 * @param card_no
	 */
	public final void setCard_no(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer card_no)
	{
		getMendixObject().setValue(context, MemberNames.Card_no.toString(), card_no);
	}

	/**
	 * @return value of Amount
	 */
	public final java.math.BigDecimal getAmount()
	{
		return getAmount(getContext());
	}

	/**
	 * @param context
	 * @return value of Amount
	 */
	public final java.math.BigDecimal getAmount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Amount.toString());
	}

	/**
	 * Set value of Amount
	 * @param amount
	 */
	public final void setAmount(java.math.BigDecimal amount)
	{
		setAmount(getContext(), amount);
	}

	/**
	 * Set value of Amount
	 * @param context
	 * @param amount
	 */
	public final void setAmount(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal amount)
	{
		getMendixObject().setValue(context, MemberNames.Amount.toString(), amount);
	}

	/**
	 * @return value of recepient_arabic_name
	 */
	public final java.lang.String getrecepient_arabic_name()
	{
		return getrecepient_arabic_name(getContext());
	}

	/**
	 * @param context
	 * @return value of recepient_arabic_name
	 */
	public final java.lang.String getrecepient_arabic_name(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.recepient_arabic_name.toString());
	}

	/**
	 * Set value of recepient_arabic_name
	 * @param recepient_arabic_name
	 */
	public final void setrecepient_arabic_name(java.lang.String recepient_arabic_name)
	{
		setrecepient_arabic_name(getContext(), recepient_arabic_name);
	}

	/**
	 * Set value of recepient_arabic_name
	 * @param context
	 * @param recepient_arabic_name
	 */
	public final void setrecepient_arabic_name(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String recepient_arabic_name)
	{
		getMendixObject().setValue(context, MemberNames.recepient_arabic_name.toString(), recepient_arabic_name);
	}

	/**
	 * @return value of BirthCerticate_BirthNotification
	 */
	public final myfirstmodule.proxies.BirthNotification getBirthCerticate_BirthNotification() throws com.mendix.core.CoreException
	{
		return getBirthCerticate_BirthNotification(getContext());
	}

	/**
	 * @param context
	 * @return value of BirthCerticate_BirthNotification
	 */
	public final myfirstmodule.proxies.BirthNotification getBirthCerticate_BirthNotification(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.BirthNotification result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.BirthCerticate_BirthNotification.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.BirthNotification.load(context, identifier);
		return result;
	}

	/**
	 * Set value of BirthCerticate_BirthNotification
	 * @param birthcerticate_birthnotification
	 */
	public final void setBirthCerticate_BirthNotification(myfirstmodule.proxies.BirthNotification birthcerticate_birthnotification)
	{
		setBirthCerticate_BirthNotification(getContext(), birthcerticate_birthnotification);
	}

	/**
	 * Set value of BirthCerticate_BirthNotification
	 * @param context
	 * @param birthcerticate_birthnotification
	 */
	public final void setBirthCerticate_BirthNotification(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.BirthNotification birthcerticate_birthnotification)
	{
		if (birthcerticate_birthnotification == null)
			getMendixObject().setValue(context, MemberNames.BirthCerticate_BirthNotification.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.BirthCerticate_BirthNotification.toString(), birthcerticate_birthnotification.getMendixObject().getId());
	}

	/**
	 * @return value of Payment_Docs_BirthCerticate
	 */
	public final myfirstmodule.proxies.Payment_Docs getPayment_Docs_BirthCerticate() throws com.mendix.core.CoreException
	{
		return getPayment_Docs_BirthCerticate(getContext());
	}

	/**
	 * @param context
	 * @return value of Payment_Docs_BirthCerticate
	 */
	public final myfirstmodule.proxies.Payment_Docs getPayment_Docs_BirthCerticate(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Payment_Docs result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Payment_Docs_BirthCerticate.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Payment_Docs.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Payment_Docs_BirthCerticate
	 * @param payment_docs_birthcerticate
	 */
	public final void setPayment_Docs_BirthCerticate(myfirstmodule.proxies.Payment_Docs payment_docs_birthcerticate)
	{
		setPayment_Docs_BirthCerticate(getContext(), payment_docs_birthcerticate);
	}

	/**
	 * Set value of Payment_Docs_BirthCerticate
	 * @param context
	 * @param payment_docs_birthcerticate
	 */
	public final void setPayment_Docs_BirthCerticate(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Payment_Docs payment_docs_birthcerticate)
	{
		if (payment_docs_birthcerticate == null)
			getMendixObject().setValue(context, MemberNames.Payment_Docs_BirthCerticate.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Payment_Docs_BirthCerticate.toString(), payment_docs_birthcerticate.getMendixObject().getId());
	}

	/**
	 * @return value of Payment_BirthCerticate
	 */
	public final myfirstmodule.proxies.Payment getPayment_BirthCerticate() throws com.mendix.core.CoreException
	{
		return getPayment_BirthCerticate(getContext());
	}

	/**
	 * @param context
	 * @return value of Payment_BirthCerticate
	 */
	public final myfirstmodule.proxies.Payment getPayment_BirthCerticate(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Payment result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Payment_BirthCerticate.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Payment.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Payment_BirthCerticate
	 * @param payment_birthcerticate
	 */
	public final void setPayment_BirthCerticate(myfirstmodule.proxies.Payment payment_birthcerticate)
	{
		setPayment_BirthCerticate(getContext(), payment_birthcerticate);
	}

	/**
	 * Set value of Payment_BirthCerticate
	 * @param context
	 * @param payment_birthcerticate
	 */
	public final void setPayment_BirthCerticate(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Payment payment_birthcerticate)
	{
		if (payment_birthcerticate == null)
			getMendixObject().setValue(context, MemberNames.Payment_BirthCerticate.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Payment_BirthCerticate.toString(), payment_birthcerticate.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return birthCerticateMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.BirthCerticate that = (myfirstmodule.proxies.BirthCerticate) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.BirthCerticate";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
