// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Calendar
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject calendarMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Calendar";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Notification_Number("Notification_Number"),
		Approved_Date("Approved_Date"),
		AllDay("AllDay"),
		End_Date("End_Date"),
		Title("Title"),
		Status("Status"),
		Approved("Approved"),
		Returned("Returned"),
		Rejected("Rejected"),
		Pending("Pending"),
		Calendar_BirthNotification("MyFirstModule.Calendar_BirthNotification"),
		Calendar_Account("MyFirstModule.Calendar_Account");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Calendar(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.Calendar"));
	}

	protected Calendar(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject calendarMendixObject)
	{
		if (calendarMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.Calendar", calendarMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.Calendar");

		this.calendarMendixObject = calendarMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Calendar.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.Calendar initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Calendar.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.Calendar initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Calendar(context, mendixObject);
	}

	public static myfirstmodule.proxies.Calendar load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Calendar.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Calendar> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.Calendar> result = new java.util.ArrayList<myfirstmodule.proxies.Calendar>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MyFirstModule.Calendar" + xpathConstraint))
			result.add(myfirstmodule.proxies.Calendar.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Notification_Number
	 */
	public final java.lang.String getNotification_Number()
	{
		return getNotification_Number(getContext());
	}

	/**
	 * @param context
	 * @return value of Notification_Number
	 */
	public final java.lang.String getNotification_Number(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Notification_Number.toString());
	}

	/**
	 * Set value of Notification_Number
	 * @param notification_number
	 */
	public final void setNotification_Number(java.lang.String notification_number)
	{
		setNotification_Number(getContext(), notification_number);
	}

	/**
	 * Set value of Notification_Number
	 * @param context
	 * @param notification_number
	 */
	public final void setNotification_Number(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String notification_number)
	{
		getMendixObject().setValue(context, MemberNames.Notification_Number.toString(), notification_number);
	}

	/**
	 * @return value of Approved_Date
	 */
	public final java.util.Date getApproved_Date()
	{
		return getApproved_Date(getContext());
	}

	/**
	 * @param context
	 * @return value of Approved_Date
	 */
	public final java.util.Date getApproved_Date(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Approved_Date.toString());
	}

	/**
	 * Set value of Approved_Date
	 * @param approved_date
	 */
	public final void setApproved_Date(java.util.Date approved_date)
	{
		setApproved_Date(getContext(), approved_date);
	}

	/**
	 * Set value of Approved_Date
	 * @param context
	 * @param approved_date
	 */
	public final void setApproved_Date(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date approved_date)
	{
		getMendixObject().setValue(context, MemberNames.Approved_Date.toString(), approved_date);
	}

	/**
	 * @return value of AllDay
	 */
	public final java.lang.Boolean getAllDay()
	{
		return getAllDay(getContext());
	}

	/**
	 * @param context
	 * @return value of AllDay
	 */
	public final java.lang.Boolean getAllDay(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.AllDay.toString());
	}

	/**
	 * Set value of AllDay
	 * @param allday
	 */
	public final void setAllDay(java.lang.Boolean allday)
	{
		setAllDay(getContext(), allday);
	}

	/**
	 * Set value of AllDay
	 * @param context
	 * @param allday
	 */
	public final void setAllDay(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean allday)
	{
		getMendixObject().setValue(context, MemberNames.AllDay.toString(), allday);
	}

	/**
	 * @return value of End_Date
	 */
	public final java.util.Date getEnd_Date()
	{
		return getEnd_Date(getContext());
	}

	/**
	 * @param context
	 * @return value of End_Date
	 */
	public final java.util.Date getEnd_Date(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.End_Date.toString());
	}

	/**
	 * Set value of End_Date
	 * @param end_date
	 */
	public final void setEnd_Date(java.util.Date end_date)
	{
		setEnd_Date(getContext(), end_date);
	}

	/**
	 * Set value of End_Date
	 * @param context
	 * @param end_date
	 */
	public final void setEnd_Date(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date end_date)
	{
		getMendixObject().setValue(context, MemberNames.End_Date.toString(), end_date);
	}

	/**
	 * @return value of Title
	 */
	public final java.lang.String getTitle()
	{
		return getTitle(getContext());
	}

	/**
	 * @param context
	 * @return value of Title
	 */
	public final java.lang.String getTitle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Title.toString());
	}

	/**
	 * Set value of Title
	 * @param title
	 */
	public final void setTitle(java.lang.String title)
	{
		setTitle(getContext(), title);
	}

	/**
	 * Set value of Title
	 * @param context
	 * @param title
	 */
	public final void setTitle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String title)
	{
		getMendixObject().setValue(context, MemberNames.Title.toString(), title);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final myfirstmodule.proxies.EnumStatus getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final myfirstmodule.proxies.EnumStatus getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Status.toString());
		if (obj == null)
			return null;

		return myfirstmodule.proxies.EnumStatus.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(myfirstmodule.proxies.EnumStatus status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.EnumStatus status)
	{
		if (status != null)
			getMendixObject().setValue(context, MemberNames.Status.toString(), status.toString());
		else
			getMendixObject().setValue(context, MemberNames.Status.toString(), null);
	}

	/**
	 * @return value of Approved
	 */
	public final java.lang.Integer getApproved()
	{
		return getApproved(getContext());
	}

	/**
	 * @param context
	 * @return value of Approved
	 */
	public final java.lang.Integer getApproved(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Approved.toString());
	}

	/**
	 * Set value of Approved
	 * @param approved
	 */
	public final void setApproved(java.lang.Integer approved)
	{
		setApproved(getContext(), approved);
	}

	/**
	 * Set value of Approved
	 * @param context
	 * @param approved
	 */
	public final void setApproved(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer approved)
	{
		getMendixObject().setValue(context, MemberNames.Approved.toString(), approved);
	}

	/**
	 * @return value of Returned
	 */
	public final java.lang.Integer getReturned()
	{
		return getReturned(getContext());
	}

	/**
	 * @param context
	 * @return value of Returned
	 */
	public final java.lang.Integer getReturned(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Returned.toString());
	}

	/**
	 * Set value of Returned
	 * @param returned
	 */
	public final void setReturned(java.lang.Integer returned)
	{
		setReturned(getContext(), returned);
	}

	/**
	 * Set value of Returned
	 * @param context
	 * @param returned
	 */
	public final void setReturned(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer returned)
	{
		getMendixObject().setValue(context, MemberNames.Returned.toString(), returned);
	}

	/**
	 * @return value of Rejected
	 */
	public final java.lang.Integer getRejected()
	{
		return getRejected(getContext());
	}

	/**
	 * @param context
	 * @return value of Rejected
	 */
	public final java.lang.Integer getRejected(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Rejected.toString());
	}

	/**
	 * Set value of Rejected
	 * @param rejected
	 */
	public final void setRejected(java.lang.Integer rejected)
	{
		setRejected(getContext(), rejected);
	}

	/**
	 * Set value of Rejected
	 * @param context
	 * @param rejected
	 */
	public final void setRejected(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer rejected)
	{
		getMendixObject().setValue(context, MemberNames.Rejected.toString(), rejected);
	}

	/**
	 * @return value of Pending
	 */
	public final java.lang.Integer getPending()
	{
		return getPending(getContext());
	}

	/**
	 * @param context
	 * @return value of Pending
	 */
	public final java.lang.Integer getPending(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Pending.toString());
	}

	/**
	 * Set value of Pending
	 * @param pending
	 */
	public final void setPending(java.lang.Integer pending)
	{
		setPending(getContext(), pending);
	}

	/**
	 * Set value of Pending
	 * @param context
	 * @param pending
	 */
	public final void setPending(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer pending)
	{
		getMendixObject().setValue(context, MemberNames.Pending.toString(), pending);
	}

	/**
	 * @return value of Calendar_BirthNotification
	 */
	public final java.util.List<myfirstmodule.proxies.BirthNotification> getCalendar_BirthNotification() throws com.mendix.core.CoreException
	{
		return getCalendar_BirthNotification(getContext());
	}

	/**
	 * @param context
	 * @return value of Calendar_BirthNotification
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<myfirstmodule.proxies.BirthNotification> getCalendar_BirthNotification(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.BirthNotification> result = new java.util.ArrayList<myfirstmodule.proxies.BirthNotification>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.Calendar_BirthNotification.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(myfirstmodule.proxies.BirthNotification.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of Calendar_BirthNotification
	 * @param calendar_birthnotification
	 */
	public final void setCalendar_BirthNotification(java.util.List<myfirstmodule.proxies.BirthNotification> calendar_birthnotification)
	{
		setCalendar_BirthNotification(getContext(), calendar_birthnotification);
	}

	/**
	 * Set value of Calendar_BirthNotification
	 * @param context
	 * @param calendar_birthnotification
	 */
	public final void setCalendar_BirthNotification(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<myfirstmodule.proxies.BirthNotification> calendar_birthnotification)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (myfirstmodule.proxies.BirthNotification proxyObject : calendar_birthnotification)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.Calendar_BirthNotification.toString(), identifiers);
	}

	/**
	 * @return value of Calendar_Account
	 */
	public final administration.proxies.Account getCalendar_Account() throws com.mendix.core.CoreException
	{
		return getCalendar_Account(getContext());
	}

	/**
	 * @param context
	 * @return value of Calendar_Account
	 */
	public final administration.proxies.Account getCalendar_Account(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		administration.proxies.Account result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Calendar_Account.toString());
		if (identifier != null)
			result = administration.proxies.Account.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Calendar_Account
	 * @param calendar_account
	 */
	public final void setCalendar_Account(administration.proxies.Account calendar_account)
	{
		setCalendar_Account(getContext(), calendar_account);
	}

	/**
	 * Set value of Calendar_Account
	 * @param context
	 * @param calendar_account
	 */
	public final void setCalendar_Account(com.mendix.systemwideinterfaces.core.IContext context, administration.proxies.Account calendar_account)
	{
		if (calendar_account == null)
			getMendixObject().setValue(context, MemberNames.Calendar_Account.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Calendar_Account.toString(), calendar_account.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return calendarMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Calendar that = (myfirstmodule.proxies.Calendar) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.Calendar";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
