// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Circulardoc extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Circulardoc";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Doc_Name("Doc_Name"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		Circulardoc_Circulars("MyFirstModule.Circulardoc_Circulars"),
		Circulardoc_Account("MyFirstModule.Circulardoc_Account");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Circulardoc(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.Circulardoc"));
	}

	protected Circulardoc(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject circulardocMendixObject)
	{
		super(context, circulardocMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.Circulardoc", circulardocMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.Circulardoc");
	}

	/**
	 * @deprecated Use 'Circulardoc.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.Circulardoc initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Circulardoc.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.Circulardoc initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Circulardoc(context, mendixObject);
	}

	public static myfirstmodule.proxies.Circulardoc load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Circulardoc.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Circulardoc> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.Circulardoc> result = new java.util.ArrayList<myfirstmodule.proxies.Circulardoc>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MyFirstModule.Circulardoc" + xpathConstraint))
			result.add(myfirstmodule.proxies.Circulardoc.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of Doc_Name
	 */
	public final java.lang.String getDoc_Name()
	{
		return getDoc_Name(getContext());
	}

	/**
	 * @param context
	 * @return value of Doc_Name
	 */
	public final java.lang.String getDoc_Name(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Doc_Name.toString());
	}

	/**
	 * Set value of Doc_Name
	 * @param doc_name
	 */
	public final void setDoc_Name(java.lang.String doc_name)
	{
		setDoc_Name(getContext(), doc_name);
	}

	/**
	 * Set value of Doc_Name
	 * @param context
	 * @param doc_name
	 */
	public final void setDoc_Name(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String doc_name)
	{
		getMendixObject().setValue(context, MemberNames.Doc_Name.toString(), doc_name);
	}

	/**
	 * @return value of Circulardoc_Circulars
	 */
	public final myfirstmodule.proxies.Circulars getCirculardoc_Circulars() throws com.mendix.core.CoreException
	{
		return getCirculardoc_Circulars(getContext());
	}

	/**
	 * @param context
	 * @return value of Circulardoc_Circulars
	 */
	public final myfirstmodule.proxies.Circulars getCirculardoc_Circulars(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Circulars result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Circulardoc_Circulars.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Circulars.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Circulardoc_Circulars
	 * @param circulardoc_circulars
	 */
	public final void setCirculardoc_Circulars(myfirstmodule.proxies.Circulars circulardoc_circulars)
	{
		setCirculardoc_Circulars(getContext(), circulardoc_circulars);
	}

	/**
	 * Set value of Circulardoc_Circulars
	 * @param context
	 * @param circulardoc_circulars
	 */
	public final void setCirculardoc_Circulars(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Circulars circulardoc_circulars)
	{
		if (circulardoc_circulars == null)
			getMendixObject().setValue(context, MemberNames.Circulardoc_Circulars.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Circulardoc_Circulars.toString(), circulardoc_circulars.getMendixObject().getId());
	}

	/**
	 * @return value of Circulardoc_Account
	 */
	public final java.util.List<administration.proxies.Account> getCirculardoc_Account() throws com.mendix.core.CoreException
	{
		return getCirculardoc_Account(getContext());
	}

	/**
	 * @param context
	 * @return value of Circulardoc_Account
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<administration.proxies.Account> getCirculardoc_Account(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<administration.proxies.Account> result = new java.util.ArrayList<administration.proxies.Account>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.Circulardoc_Account.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(administration.proxies.Account.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of Circulardoc_Account
	 * @param circulardoc_account
	 */
	public final void setCirculardoc_Account(java.util.List<administration.proxies.Account> circulardoc_account)
	{
		setCirculardoc_Account(getContext(), circulardoc_account);
	}

	/**
	 * Set value of Circulardoc_Account
	 * @param context
	 * @param circulardoc_account
	 */
	public final void setCirculardoc_Account(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<administration.proxies.Account> circulardoc_account)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (administration.proxies.Account proxyObject : circulardoc_account)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.Circulardoc_Account.toString(), identifiers);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Circulardoc that = (myfirstmodule.proxies.Circulardoc) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.Circulardoc";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
