// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Document extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Document";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Changed_by("Changed_by"),
		changed_date("changed_date"),
		oldValue("oldValue"),
		NewValue("NewValue"),
		Member("Member"),
		Action("Action"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		Document_excel_("MyFirstModule.Document_excel_");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Document(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.Document"));
	}

	protected Document(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject documentMendixObject)
	{
		super(context, documentMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.Document", documentMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.Document");
	}

	/**
	 * @deprecated Use 'Document.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.Document initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Document.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.Document initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Document(context, mendixObject);
	}

	public static myfirstmodule.proxies.Document load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Document.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Document> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.Document> result = new java.util.ArrayList<myfirstmodule.proxies.Document>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MyFirstModule.Document" + xpathConstraint))
			result.add(myfirstmodule.proxies.Document.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of Changed_by
	 */
	public final java.lang.String getChanged_by()
	{
		return getChanged_by(getContext());
	}

	/**
	 * @param context
	 * @return value of Changed_by
	 */
	public final java.lang.String getChanged_by(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Changed_by.toString());
	}

	/**
	 * Set value of Changed_by
	 * @param changed_by
	 */
	public final void setChanged_by(java.lang.String changed_by)
	{
		setChanged_by(getContext(), changed_by);
	}

	/**
	 * Set value of Changed_by
	 * @param context
	 * @param changed_by
	 */
	public final void setChanged_by(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String changed_by)
	{
		getMendixObject().setValue(context, MemberNames.Changed_by.toString(), changed_by);
	}

	/**
	 * @return value of changed_date
	 */
	public final java.util.Date getchanged_date()
	{
		return getchanged_date(getContext());
	}

	/**
	 * @param context
	 * @return value of changed_date
	 */
	public final java.util.Date getchanged_date(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.changed_date.toString());
	}

	/**
	 * Set value of changed_date
	 * @param changed_date
	 */
	public final void setchanged_date(java.util.Date changed_date)
	{
		setchanged_date(getContext(), changed_date);
	}

	/**
	 * Set value of changed_date
	 * @param context
	 * @param changed_date
	 */
	public final void setchanged_date(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date changed_date)
	{
		getMendixObject().setValue(context, MemberNames.changed_date.toString(), changed_date);
	}

	/**
	 * @return value of oldValue
	 */
	public final java.lang.String getoldValue()
	{
		return getoldValue(getContext());
	}

	/**
	 * @param context
	 * @return value of oldValue
	 */
	public final java.lang.String getoldValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.oldValue.toString());
	}

	/**
	 * Set value of oldValue
	 * @param oldvalue
	 */
	public final void setoldValue(java.lang.String oldvalue)
	{
		setoldValue(getContext(), oldvalue);
	}

	/**
	 * Set value of oldValue
	 * @param context
	 * @param oldvalue
	 */
	public final void setoldValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String oldvalue)
	{
		getMendixObject().setValue(context, MemberNames.oldValue.toString(), oldvalue);
	}

	/**
	 * @return value of NewValue
	 */
	public final java.lang.String getNewValue()
	{
		return getNewValue(getContext());
	}

	/**
	 * @param context
	 * @return value of NewValue
	 */
	public final java.lang.String getNewValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.NewValue.toString());
	}

	/**
	 * Set value of NewValue
	 * @param newvalue
	 */
	public final void setNewValue(java.lang.String newvalue)
	{
		setNewValue(getContext(), newvalue);
	}

	/**
	 * Set value of NewValue
	 * @param context
	 * @param newvalue
	 */
	public final void setNewValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String newvalue)
	{
		getMendixObject().setValue(context, MemberNames.NewValue.toString(), newvalue);
	}

	/**
	 * @return value of Member
	 */
	public final java.lang.String getMember()
	{
		return getMember(getContext());
	}

	/**
	 * @param context
	 * @return value of Member
	 */
	public final java.lang.String getMember(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Member.toString());
	}

	/**
	 * Set value of Member
	 * @param member
	 */
	public final void setMember(java.lang.String member)
	{
		setMember(getContext(), member);
	}

	/**
	 * Set value of Member
	 * @param context
	 * @param member
	 */
	public final void setMember(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String member)
	{
		getMendixObject().setValue(context, MemberNames.Member.toString(), member);
	}

	/**
	 * @return value of Action
	 */
	public final java.lang.String getAction()
	{
		return getAction(getContext());
	}

	/**
	 * @param context
	 * @return value of Action
	 */
	public final java.lang.String getAction(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Action.toString());
	}

	/**
	 * Set value of Action
	 * @param action
	 */
	public final void setAction(java.lang.String action)
	{
		setAction(getContext(), action);
	}

	/**
	 * Set value of Action
	 * @param context
	 * @param action
	 */
	public final void setAction(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String action)
	{
		getMendixObject().setValue(context, MemberNames.Action.toString(), action);
	}

	/**
	 * @return value of Document_excel_
	 */
	public final myfirstmodule.proxies.excel_ getDocument_excel_() throws com.mendix.core.CoreException
	{
		return getDocument_excel_(getContext());
	}

	/**
	 * @param context
	 * @return value of Document_excel_
	 */
	public final myfirstmodule.proxies.excel_ getDocument_excel_(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.excel_ result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Document_excel_.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.excel_.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Document_excel_
	 * @param document_excel_
	 */
	public final void setDocument_excel_(myfirstmodule.proxies.excel_ document_excel_)
	{
		setDocument_excel_(getContext(), document_excel_);
	}

	/**
	 * Set value of Document_excel_
	 * @param context
	 * @param document_excel_
	 */
	public final void setDocument_excel_(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.excel_ document_excel_)
	{
		if (document_excel_ == null)
			getMendixObject().setValue(context, MemberNames.Document_excel_.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Document_excel_.toString(), document_excel_.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Document that = (myfirstmodule.proxies.Document) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.Document";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
