// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public enum EnumCertificateService
{
	NewBorn_Birth_Certificate(new java.lang.String[][] { new java.lang.String[] { "en_US", "NewBorn Birth Certificate" }, new java.lang.String[] { "ar_AE", "شهادة ميلاد المولود الجديد" } }),
	Replacement_and_Additional_Copy_Of_BirthCertificate(new java.lang.String[][] { new java.lang.String[] { "en_US", "Replacement and Additional Copy Of BirthCertificate" }, new java.lang.String[] { "ar_AE", "إصدار شهادة الميلاد البديلة والإضافية" } }),
	Amending_a_Birth_Certificate(new java.lang.String[][] { new java.lang.String[] { "en_US", "Amending a Birth Certificate" }, new java.lang.String[] { "ar_AE", "تعديل شهادة الميلاد" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private EnumCertificateService(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
