// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public enum EnumSelectService
{
	BirthNotification(new java.lang.String[][] { new java.lang.String[] { "en_US", "Birth Notification" }, new java.lang.String[] { "ar_AE", "اشعار الميلاد" } }),
	Birth_Notification_Certificate(new java.lang.String[][] { new java.lang.String[] { "en_US", "Birth Notification Correction" }, new java.lang.String[] { "ar_AE", "شهادة الميلاد" } }),
	Birth_Notification_Link(new java.lang.String[][] { new java.lang.String[] { "en_US", "Birth Notification Link" }, new java.lang.String[] { "ar_AE", "رابط اشعار الميلاد" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private EnumSelectService(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
