// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public enum ENUM_Wizardstep
{
	Visited(new java.lang.String[][] { new java.lang.String[] { "en_US", "Visited" }, new java.lang.String[] { "ar_AE", "تمت زيارته" } }),
	Unvisited(new java.lang.String[][] { new java.lang.String[] { "en_US", "Unvisited" }, new java.lang.String[] { "ar_AE", "لم تتم زيارته" } }),
	Partialy_Visited(new java.lang.String[][] { new java.lang.String[] { "en_US", "Partialy_Visited" }, new java.lang.String[] { "ar_AE", "تمت الزيارة جزئيًا" } }),
	Active(new java.lang.String[][] { new java.lang.String[] { "en_US", "Active" }, new java.lang.String[] { "ar_AE", "مفعل" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private ENUM_Wizardstep(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
