// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public enum EnumPlaceOfBirthPU
{
	Home_Unattended(new java.lang.String[][] { new java.lang.String[] { "en_US", "Home Unattended" }, new java.lang.String[] { "ar_AE", "لم يحضر المنزل" } }),
	Outside(new java.lang.String[][] { new java.lang.String[] { "en_US", "Outside" }, new java.lang.String[] { "ar_AE", "الخارج" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private EnumPlaceOfBirthPU(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
