// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public enum EnumReligion
{
	Muslim(new java.lang.String[][] { new java.lang.String[] { "en_US", "Muslim" }, new java.lang.String[] { "ar_AE", "مسلم" } }),
	Christian(new java.lang.String[][] { new java.lang.String[] { "en_US", "Christian" }, new java.lang.String[] { "ar_AE", "مسيحي" } }),
	Jewish(new java.lang.String[][] { new java.lang.String[] { "en_US", "Jewish" }, new java.lang.String[] { "ar_AE", "يهودي" } }),
	Other(new java.lang.String[][] { new java.lang.String[] { "en_US", "Other" }, new java.lang.String[] { "ar_AE", "آخر" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private EnumReligion(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
