// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public enum EnumPlaceOfBirth
{
	Hospital(new java.lang.String[][] { new java.lang.String[] { "en_US", "Hospital" }, new java.lang.String[] { "ar_AE", "مستشفى" } }),
	HomeAttended(new java.lang.String[][] { new java.lang.String[] { "en_US", "HomeAttended" }, new java.lang.String[] { "ar_AE", "حضر المنزل" } }),
	HomeUnAttended(new java.lang.String[][] { new java.lang.String[] { "en_US", "HomeUnAttended" }, new java.lang.String[] { "ar_AE", "لم يحضر المنزل" } }),
	RoadAttended(new java.lang.String[][] { new java.lang.String[] { "en_US", "RoadAttended" }, new java.lang.String[] { "ar_AE", "الطريق التي حضرها" } }),
	Outside(new java.lang.String[][] { new java.lang.String[] { "en_US", "Outside" }, new java.lang.String[] { "ar_AE", "الخارج" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private EnumPlaceOfBirth(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
