// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public enum EnumMartialStatus
{
	Single(new java.lang.String[][] { new java.lang.String[] { "en_US", "Single" }, new java.lang.String[] { "ar_AE", "أعزب" } }),
	Married(new java.lang.String[][] { new java.lang.String[] { "en_US", "Married" }, new java.lang.String[] { "ar_AE", "متزوج" } }),
	Divorced(new java.lang.String[][] { new java.lang.String[] { "en_US", "Divorced" }, new java.lang.String[] { "ar_AE", "مطلق" } }),
	NotKnown(new java.lang.String[][] { new java.lang.String[] { "en_US", "NotKnown" }, new java.lang.String[] { "ar_AE", "غير معروف" } }),
	Widowed(new java.lang.String[][] { new java.lang.String[] { "en_US", "Widowed" }, new java.lang.String[] { "ar_AE", "الأرامل" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private EnumMartialStatus(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
