// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class HappinessMeter
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject happinessMeterMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.HappinessMeter";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Flag("Flag"),
		Good1("Good1"),
		Good2("Good2"),
		Good3("Good3"),
		Good4("Good4"),
		OK1("OK1"),
		OK2("OK2"),
		OK3("OK3"),
		OK4("OK4"),
		NotGood1("NotGood1"),
		NotGood2("NotGood2"),
		NotGood3("NotGood3"),
		NotGood4("NotGood4"),
		Questions("Questions"),
		Date("Date"),
		OverallRating("OverallRating"),
		HappinessMeter_Profile("MyFirstModule.HappinessMeter_Profile"),
		HappinessMeter_Account("MyFirstModule.HappinessMeter_Account");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public HappinessMeter(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.HappinessMeter"));
	}

	protected HappinessMeter(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject happinessMeterMendixObject)
	{
		if (happinessMeterMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.HappinessMeter", happinessMeterMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.HappinessMeter");

		this.happinessMeterMendixObject = happinessMeterMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'HappinessMeter.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.HappinessMeter initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.HappinessMeter.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.HappinessMeter initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.HappinessMeter(context, mendixObject);
	}

	public static myfirstmodule.proxies.HappinessMeter load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.HappinessMeter.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.HappinessMeter> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.HappinessMeter> result = new java.util.ArrayList<myfirstmodule.proxies.HappinessMeter>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MyFirstModule.HappinessMeter" + xpathConstraint))
			result.add(myfirstmodule.proxies.HappinessMeter.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Flag
	 */
	public final java.lang.Boolean getFlag()
	{
		return getFlag(getContext());
	}

	/**
	 * @param context
	 * @return value of Flag
	 */
	public final java.lang.Boolean getFlag(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Flag.toString());
	}

	/**
	 * Set value of Flag
	 * @param flag
	 */
	public final void setFlag(java.lang.Boolean flag)
	{
		setFlag(getContext(), flag);
	}

	/**
	 * Set value of Flag
	 * @param context
	 * @param flag
	 */
	public final void setFlag(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean flag)
	{
		getMendixObject().setValue(context, MemberNames.Flag.toString(), flag);
	}

	/**
	 * @return value of Good1
	 */
	public final java.lang.Boolean getGood1()
	{
		return getGood1(getContext());
	}

	/**
	 * @param context
	 * @return value of Good1
	 */
	public final java.lang.Boolean getGood1(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Good1.toString());
	}

	/**
	 * Set value of Good1
	 * @param good1
	 */
	public final void setGood1(java.lang.Boolean good1)
	{
		setGood1(getContext(), good1);
	}

	/**
	 * Set value of Good1
	 * @param context
	 * @param good1
	 */
	public final void setGood1(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean good1)
	{
		getMendixObject().setValue(context, MemberNames.Good1.toString(), good1);
	}

	/**
	 * @return value of Good2
	 */
	public final java.lang.Boolean getGood2()
	{
		return getGood2(getContext());
	}

	/**
	 * @param context
	 * @return value of Good2
	 */
	public final java.lang.Boolean getGood2(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Good2.toString());
	}

	/**
	 * Set value of Good2
	 * @param good2
	 */
	public final void setGood2(java.lang.Boolean good2)
	{
		setGood2(getContext(), good2);
	}

	/**
	 * Set value of Good2
	 * @param context
	 * @param good2
	 */
	public final void setGood2(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean good2)
	{
		getMendixObject().setValue(context, MemberNames.Good2.toString(), good2);
	}

	/**
	 * @return value of Good3
	 */
	public final java.lang.Boolean getGood3()
	{
		return getGood3(getContext());
	}

	/**
	 * @param context
	 * @return value of Good3
	 */
	public final java.lang.Boolean getGood3(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Good3.toString());
	}

	/**
	 * Set value of Good3
	 * @param good3
	 */
	public final void setGood3(java.lang.Boolean good3)
	{
		setGood3(getContext(), good3);
	}

	/**
	 * Set value of Good3
	 * @param context
	 * @param good3
	 */
	public final void setGood3(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean good3)
	{
		getMendixObject().setValue(context, MemberNames.Good3.toString(), good3);
	}

	/**
	 * @return value of Good4
	 */
	public final java.lang.Boolean getGood4()
	{
		return getGood4(getContext());
	}

	/**
	 * @param context
	 * @return value of Good4
	 */
	public final java.lang.Boolean getGood4(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Good4.toString());
	}

	/**
	 * Set value of Good4
	 * @param good4
	 */
	public final void setGood4(java.lang.Boolean good4)
	{
		setGood4(getContext(), good4);
	}

	/**
	 * Set value of Good4
	 * @param context
	 * @param good4
	 */
	public final void setGood4(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean good4)
	{
		getMendixObject().setValue(context, MemberNames.Good4.toString(), good4);
	}

	/**
	 * @return value of OK1
	 */
	public final java.lang.Boolean getOK1()
	{
		return getOK1(getContext());
	}

	/**
	 * @param context
	 * @return value of OK1
	 */
	public final java.lang.Boolean getOK1(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.OK1.toString());
	}

	/**
	 * Set value of OK1
	 * @param ok1
	 */
	public final void setOK1(java.lang.Boolean ok1)
	{
		setOK1(getContext(), ok1);
	}

	/**
	 * Set value of OK1
	 * @param context
	 * @param ok1
	 */
	public final void setOK1(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean ok1)
	{
		getMendixObject().setValue(context, MemberNames.OK1.toString(), ok1);
	}

	/**
	 * @return value of OK2
	 */
	public final java.lang.Boolean getOK2()
	{
		return getOK2(getContext());
	}

	/**
	 * @param context
	 * @return value of OK2
	 */
	public final java.lang.Boolean getOK2(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.OK2.toString());
	}

	/**
	 * Set value of OK2
	 * @param ok2
	 */
	public final void setOK2(java.lang.Boolean ok2)
	{
		setOK2(getContext(), ok2);
	}

	/**
	 * Set value of OK2
	 * @param context
	 * @param ok2
	 */
	public final void setOK2(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean ok2)
	{
		getMendixObject().setValue(context, MemberNames.OK2.toString(), ok2);
	}

	/**
	 * @return value of OK3
	 */
	public final java.lang.Boolean getOK3()
	{
		return getOK3(getContext());
	}

	/**
	 * @param context
	 * @return value of OK3
	 */
	public final java.lang.Boolean getOK3(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.OK3.toString());
	}

	/**
	 * Set value of OK3
	 * @param ok3
	 */
	public final void setOK3(java.lang.Boolean ok3)
	{
		setOK3(getContext(), ok3);
	}

	/**
	 * Set value of OK3
	 * @param context
	 * @param ok3
	 */
	public final void setOK3(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean ok3)
	{
		getMendixObject().setValue(context, MemberNames.OK3.toString(), ok3);
	}

	/**
	 * @return value of OK4
	 */
	public final java.lang.Boolean getOK4()
	{
		return getOK4(getContext());
	}

	/**
	 * @param context
	 * @return value of OK4
	 */
	public final java.lang.Boolean getOK4(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.OK4.toString());
	}

	/**
	 * Set value of OK4
	 * @param ok4
	 */
	public final void setOK4(java.lang.Boolean ok4)
	{
		setOK4(getContext(), ok4);
	}

	/**
	 * Set value of OK4
	 * @param context
	 * @param ok4
	 */
	public final void setOK4(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean ok4)
	{
		getMendixObject().setValue(context, MemberNames.OK4.toString(), ok4);
	}

	/**
	 * @return value of NotGood1
	 */
	public final java.lang.Boolean getNotGood1()
	{
		return getNotGood1(getContext());
	}

	/**
	 * @param context
	 * @return value of NotGood1
	 */
	public final java.lang.Boolean getNotGood1(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.NotGood1.toString());
	}

	/**
	 * Set value of NotGood1
	 * @param notgood1
	 */
	public final void setNotGood1(java.lang.Boolean notgood1)
	{
		setNotGood1(getContext(), notgood1);
	}

	/**
	 * Set value of NotGood1
	 * @param context
	 * @param notgood1
	 */
	public final void setNotGood1(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean notgood1)
	{
		getMendixObject().setValue(context, MemberNames.NotGood1.toString(), notgood1);
	}

	/**
	 * @return value of NotGood2
	 */
	public final java.lang.Boolean getNotGood2()
	{
		return getNotGood2(getContext());
	}

	/**
	 * @param context
	 * @return value of NotGood2
	 */
	public final java.lang.Boolean getNotGood2(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.NotGood2.toString());
	}

	/**
	 * Set value of NotGood2
	 * @param notgood2
	 */
	public final void setNotGood2(java.lang.Boolean notgood2)
	{
		setNotGood2(getContext(), notgood2);
	}

	/**
	 * Set value of NotGood2
	 * @param context
	 * @param notgood2
	 */
	public final void setNotGood2(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean notgood2)
	{
		getMendixObject().setValue(context, MemberNames.NotGood2.toString(), notgood2);
	}

	/**
	 * @return value of NotGood3
	 */
	public final java.lang.Boolean getNotGood3()
	{
		return getNotGood3(getContext());
	}

	/**
	 * @param context
	 * @return value of NotGood3
	 */
	public final java.lang.Boolean getNotGood3(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.NotGood3.toString());
	}

	/**
	 * Set value of NotGood3
	 * @param notgood3
	 */
	public final void setNotGood3(java.lang.Boolean notgood3)
	{
		setNotGood3(getContext(), notgood3);
	}

	/**
	 * Set value of NotGood3
	 * @param context
	 * @param notgood3
	 */
	public final void setNotGood3(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean notgood3)
	{
		getMendixObject().setValue(context, MemberNames.NotGood3.toString(), notgood3);
	}

	/**
	 * @return value of NotGood4
	 */
	public final java.lang.Boolean getNotGood4()
	{
		return getNotGood4(getContext());
	}

	/**
	 * @param context
	 * @return value of NotGood4
	 */
	public final java.lang.Boolean getNotGood4(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.NotGood4.toString());
	}

	/**
	 * Set value of NotGood4
	 * @param notgood4
	 */
	public final void setNotGood4(java.lang.Boolean notgood4)
	{
		setNotGood4(getContext(), notgood4);
	}

	/**
	 * Set value of NotGood4
	 * @param context
	 * @param notgood4
	 */
	public final void setNotGood4(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean notgood4)
	{
		getMendixObject().setValue(context, MemberNames.NotGood4.toString(), notgood4);
	}

	/**
	 * @return value of Questions
	 */
	public final java.lang.String getQuestions()
	{
		return getQuestions(getContext());
	}

	/**
	 * @param context
	 * @return value of Questions
	 */
	public final java.lang.String getQuestions(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Questions.toString());
	}

	/**
	 * Set value of Questions
	 * @param questions
	 */
	public final void setQuestions(java.lang.String questions)
	{
		setQuestions(getContext(), questions);
	}

	/**
	 * Set value of Questions
	 * @param context
	 * @param questions
	 */
	public final void setQuestions(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String questions)
	{
		getMendixObject().setValue(context, MemberNames.Questions.toString(), questions);
	}

	/**
	 * @return value of Date
	 */
	public final java.util.Date getDate()
	{
		return getDate(getContext());
	}

	/**
	 * @param context
	 * @return value of Date
	 */
	public final java.util.Date getDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Date.toString());
	}

	/**
	 * Set value of Date
	 * @param date
	 */
	public final void setDate(java.util.Date date)
	{
		setDate(getContext(), date);
	}

	/**
	 * Set value of Date
	 * @param context
	 * @param date
	 */
	public final void setDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date date)
	{
		getMendixObject().setValue(context, MemberNames.Date.toString(), date);
	}

	/**
	 * Set value of OverallRating
	 * @param overallrating
	 */
	public final myfirstmodule.proxies.Enum_OverallRating getOverallRating()
	{
		return getOverallRating(getContext());
	}

	/**
	 * @param context
	 * @return value of OverallRating
	 */
	public final myfirstmodule.proxies.Enum_OverallRating getOverallRating(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.OverallRating.toString());
		if (obj == null)
			return null;

		return myfirstmodule.proxies.Enum_OverallRating.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of OverallRating
	 * @param overallrating
	 */
	public final void setOverallRating(myfirstmodule.proxies.Enum_OverallRating overallrating)
	{
		setOverallRating(getContext(), overallrating);
	}

	/**
	 * Set value of OverallRating
	 * @param context
	 * @param overallrating
	 */
	public final void setOverallRating(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Enum_OverallRating overallrating)
	{
		if (overallrating != null)
			getMendixObject().setValue(context, MemberNames.OverallRating.toString(), overallrating.toString());
		else
			getMendixObject().setValue(context, MemberNames.OverallRating.toString(), null);
	}

	/**
	 * @return value of HappinessMeter_Profile
	 */
	public final myfirstmodule.proxies.Profile getHappinessMeter_Profile() throws com.mendix.core.CoreException
	{
		return getHappinessMeter_Profile(getContext());
	}

	/**
	 * @param context
	 * @return value of HappinessMeter_Profile
	 */
	public final myfirstmodule.proxies.Profile getHappinessMeter_Profile(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Profile result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.HappinessMeter_Profile.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Profile.load(context, identifier);
		return result;
	}

	/**
	 * Set value of HappinessMeter_Profile
	 * @param happinessmeter_profile
	 */
	public final void setHappinessMeter_Profile(myfirstmodule.proxies.Profile happinessmeter_profile)
	{
		setHappinessMeter_Profile(getContext(), happinessmeter_profile);
	}

	/**
	 * Set value of HappinessMeter_Profile
	 * @param context
	 * @param happinessmeter_profile
	 */
	public final void setHappinessMeter_Profile(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Profile happinessmeter_profile)
	{
		if (happinessmeter_profile == null)
			getMendixObject().setValue(context, MemberNames.HappinessMeter_Profile.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.HappinessMeter_Profile.toString(), happinessmeter_profile.getMendixObject().getId());
	}

	/**
	 * @return value of HappinessMeter_Account
	 */
	public final administration.proxies.Account getHappinessMeter_Account() throws com.mendix.core.CoreException
	{
		return getHappinessMeter_Account(getContext());
	}

	/**
	 * @param context
	 * @return value of HappinessMeter_Account
	 */
	public final administration.proxies.Account getHappinessMeter_Account(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		administration.proxies.Account result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.HappinessMeter_Account.toString());
		if (identifier != null)
			result = administration.proxies.Account.load(context, identifier);
		return result;
	}

	/**
	 * Set value of HappinessMeter_Account
	 * @param happinessmeter_account
	 */
	public final void setHappinessMeter_Account(administration.proxies.Account happinessmeter_account)
	{
		setHappinessMeter_Account(getContext(), happinessmeter_account);
	}

	/**
	 * Set value of HappinessMeter_Account
	 * @param context
	 * @param happinessmeter_account
	 */
	public final void setHappinessMeter_Account(com.mendix.systemwideinterfaces.core.IContext context, administration.proxies.Account happinessmeter_account)
	{
		if (happinessmeter_account == null)
			getMendixObject().setValue(context, MemberNames.HappinessMeter_Account.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.HappinessMeter_Account.toString(), happinessmeter_account.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return happinessMeterMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.HappinessMeter that = (myfirstmodule.proxies.HappinessMeter) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.HappinessMeter";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
