// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class History
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject historyMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.History";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Sender("Sender"),
		Receiver("Receiver"),
		Status("Status"),
		NotificationNumber("NotificationNumber"),
		SLA("SLA"),
		SLAStatus("SLAStatus"),
		refno("refno"),
		SLADate("SLADate"),
		History_BirthNotification("MyFirstModule.History_BirthNotification");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public History(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.History"));
	}

	protected History(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject historyMendixObject)
	{
		if (historyMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.History", historyMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.History");

		this.historyMendixObject = historyMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'History.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.History initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.History.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.History initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.History(context, mendixObject);
	}

	public static myfirstmodule.proxies.History load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.History.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.History> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.History> result = new java.util.ArrayList<myfirstmodule.proxies.History>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MyFirstModule.History" + xpathConstraint))
			result.add(myfirstmodule.proxies.History.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Sender
	 */
	public final java.lang.String getSender()
	{
		return getSender(getContext());
	}

	/**
	 * @param context
	 * @return value of Sender
	 */
	public final java.lang.String getSender(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Sender.toString());
	}

	/**
	 * Set value of Sender
	 * @param sender
	 */
	public final void setSender(java.lang.String sender)
	{
		setSender(getContext(), sender);
	}

	/**
	 * Set value of Sender
	 * @param context
	 * @param sender
	 */
	public final void setSender(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sender)
	{
		getMendixObject().setValue(context, MemberNames.Sender.toString(), sender);
	}

	/**
	 * @return value of Receiver
	 */
	public final java.lang.String getReceiver()
	{
		return getReceiver(getContext());
	}

	/**
	 * @param context
	 * @return value of Receiver
	 */
	public final java.lang.String getReceiver(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Receiver.toString());
	}

	/**
	 * Set value of Receiver
	 * @param receiver
	 */
	public final void setReceiver(java.lang.String receiver)
	{
		setReceiver(getContext(), receiver);
	}

	/**
	 * Set value of Receiver
	 * @param context
	 * @param receiver
	 */
	public final void setReceiver(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String receiver)
	{
		getMendixObject().setValue(context, MemberNames.Receiver.toString(), receiver);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final myfirstmodule.proxies.EnumStatus getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final myfirstmodule.proxies.EnumStatus getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Status.toString());
		if (obj == null)
			return null;

		return myfirstmodule.proxies.EnumStatus.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(myfirstmodule.proxies.EnumStatus status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.EnumStatus status)
	{
		if (status != null)
			getMendixObject().setValue(context, MemberNames.Status.toString(), status.toString());
		else
			getMendixObject().setValue(context, MemberNames.Status.toString(), null);
	}

	/**
	 * @return value of NotificationNumber
	 */
	public final java.lang.String getNotificationNumber()
	{
		return getNotificationNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of NotificationNumber
	 */
	public final java.lang.String getNotificationNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.NotificationNumber.toString());
	}

	/**
	 * Set value of NotificationNumber
	 * @param notificationnumber
	 */
	public final void setNotificationNumber(java.lang.String notificationnumber)
	{
		setNotificationNumber(getContext(), notificationnumber);
	}

	/**
	 * Set value of NotificationNumber
	 * @param context
	 * @param notificationnumber
	 */
	public final void setNotificationNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String notificationnumber)
	{
		getMendixObject().setValue(context, MemberNames.NotificationNumber.toString(), notificationnumber);
	}

	/**
	 * @return value of SLA
	 */
	public final java.lang.String getSLA()
	{
		return getSLA(getContext());
	}

	/**
	 * @param context
	 * @return value of SLA
	 */
	public final java.lang.String getSLA(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SLA.toString());
	}

	/**
	 * Set value of SLA
	 * @param sla
	 */
	public final void setSLA(java.lang.String sla)
	{
		setSLA(getContext(), sla);
	}

	/**
	 * Set value of SLA
	 * @param context
	 * @param sla
	 */
	public final void setSLA(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sla)
	{
		getMendixObject().setValue(context, MemberNames.SLA.toString(), sla);
	}

	/**
	 * Set value of SLAStatus
	 * @param slastatus
	 */
	public final myfirstmodule.proxies.EnumSlaStatus getSLAStatus()
	{
		return getSLAStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of SLAStatus
	 */
	public final myfirstmodule.proxies.EnumSlaStatus getSLAStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.SLAStatus.toString());
		if (obj == null)
			return null;

		return myfirstmodule.proxies.EnumSlaStatus.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of SLAStatus
	 * @param slastatus
	 */
	public final void setSLAStatus(myfirstmodule.proxies.EnumSlaStatus slastatus)
	{
		setSLAStatus(getContext(), slastatus);
	}

	/**
	 * Set value of SLAStatus
	 * @param context
	 * @param slastatus
	 */
	public final void setSLAStatus(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.EnumSlaStatus slastatus)
	{
		if (slastatus != null)
			getMendixObject().setValue(context, MemberNames.SLAStatus.toString(), slastatus.toString());
		else
			getMendixObject().setValue(context, MemberNames.SLAStatus.toString(), null);
	}

	/**
	 * @return value of refno
	 */
	public final java.lang.Integer getrefno()
	{
		return getrefno(getContext());
	}

	/**
	 * @param context
	 * @return value of refno
	 */
	public final java.lang.Integer getrefno(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.refno.toString());
	}

	/**
	 * Set value of refno
	 * @param refno
	 */
	public final void setrefno(java.lang.Integer refno)
	{
		setrefno(getContext(), refno);
	}

	/**
	 * Set value of refno
	 * @param context
	 * @param refno
	 */
	public final void setrefno(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer refno)
	{
		getMendixObject().setValue(context, MemberNames.refno.toString(), refno);
	}

	/**
	 * @return value of SLADate
	 */
	public final java.util.Date getSLADate()
	{
		return getSLADate(getContext());
	}

	/**
	 * @param context
	 * @return value of SLADate
	 */
	public final java.util.Date getSLADate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.SLADate.toString());
	}

	/**
	 * Set value of SLADate
	 * @param sladate
	 */
	public final void setSLADate(java.util.Date sladate)
	{
		setSLADate(getContext(), sladate);
	}

	/**
	 * Set value of SLADate
	 * @param context
	 * @param sladate
	 */
	public final void setSLADate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date sladate)
	{
		getMendixObject().setValue(context, MemberNames.SLADate.toString(), sladate);
	}

	/**
	 * @return value of History_BirthNotification
	 */
	public final myfirstmodule.proxies.BirthNotification getHistory_BirthNotification() throws com.mendix.core.CoreException
	{
		return getHistory_BirthNotification(getContext());
	}

	/**
	 * @param context
	 * @return value of History_BirthNotification
	 */
	public final myfirstmodule.proxies.BirthNotification getHistory_BirthNotification(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.BirthNotification result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.History_BirthNotification.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.BirthNotification.load(context, identifier);
		return result;
	}

	/**
	 * Set value of History_BirthNotification
	 * @param history_birthnotification
	 */
	public final void setHistory_BirthNotification(myfirstmodule.proxies.BirthNotification history_birthnotification)
	{
		setHistory_BirthNotification(getContext(), history_birthnotification);
	}

	/**
	 * Set value of History_BirthNotification
	 * @param context
	 * @param history_birthnotification
	 */
	public final void setHistory_BirthNotification(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.BirthNotification history_birthnotification)
	{
		if (history_birthnotification == null)
			getMendixObject().setValue(context, MemberNames.History_BirthNotification.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.History_BirthNotification.toString(), history_birthnotification.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return historyMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.History that = (myfirstmodule.proxies.History) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.History";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
