// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Payment
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject paymentMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Payment";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		CreditCard("CreditCard"),
		NetBanking("NetBanking"),
		Noqodi("Noqodi"),
		Payno("Payno"),
		CreditCardNumber("CreditCardNumber"),
		ExpiryDate("ExpiryDate"),
		CVV_Number("CVV_Number"),
		ReceiptNo("ReceiptNo"),
		Payment_BirthCerticate("MyFirstModule.Payment_BirthCerticate");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Payment(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.Payment"));
	}

	protected Payment(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject paymentMendixObject)
	{
		if (paymentMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.Payment", paymentMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.Payment");

		this.paymentMendixObject = paymentMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Payment.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.Payment initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Payment.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.Payment initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Payment(context, mendixObject);
	}

	public static myfirstmodule.proxies.Payment load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Payment.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Payment> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.Payment> result = new java.util.ArrayList<myfirstmodule.proxies.Payment>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MyFirstModule.Payment" + xpathConstraint))
			result.add(myfirstmodule.proxies.Payment.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of CreditCard
	 */
	public final java.lang.Boolean getCreditCard()
	{
		return getCreditCard(getContext());
	}

	/**
	 * @param context
	 * @return value of CreditCard
	 */
	public final java.lang.Boolean getCreditCard(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.CreditCard.toString());
	}

	/**
	 * Set value of CreditCard
	 * @param creditcard
	 */
	public final void setCreditCard(java.lang.Boolean creditcard)
	{
		setCreditCard(getContext(), creditcard);
	}

	/**
	 * Set value of CreditCard
	 * @param context
	 * @param creditcard
	 */
	public final void setCreditCard(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean creditcard)
	{
		getMendixObject().setValue(context, MemberNames.CreditCard.toString(), creditcard);
	}

	/**
	 * @return value of NetBanking
	 */
	public final java.lang.Boolean getNetBanking()
	{
		return getNetBanking(getContext());
	}

	/**
	 * @param context
	 * @return value of NetBanking
	 */
	public final java.lang.Boolean getNetBanking(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.NetBanking.toString());
	}

	/**
	 * Set value of NetBanking
	 * @param netbanking
	 */
	public final void setNetBanking(java.lang.Boolean netbanking)
	{
		setNetBanking(getContext(), netbanking);
	}

	/**
	 * Set value of NetBanking
	 * @param context
	 * @param netbanking
	 */
	public final void setNetBanking(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean netbanking)
	{
		getMendixObject().setValue(context, MemberNames.NetBanking.toString(), netbanking);
	}

	/**
	 * @return value of Noqodi
	 */
	public final java.lang.Boolean getNoqodi()
	{
		return getNoqodi(getContext());
	}

	/**
	 * @param context
	 * @return value of Noqodi
	 */
	public final java.lang.Boolean getNoqodi(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Noqodi.toString());
	}

	/**
	 * Set value of Noqodi
	 * @param noqodi
	 */
	public final void setNoqodi(java.lang.Boolean noqodi)
	{
		setNoqodi(getContext(), noqodi);
	}

	/**
	 * Set value of Noqodi
	 * @param context
	 * @param noqodi
	 */
	public final void setNoqodi(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean noqodi)
	{
		getMendixObject().setValue(context, MemberNames.Noqodi.toString(), noqodi);
	}

	/**
	 * @return value of Payno
	 */
	public final java.lang.Integer getPayno()
	{
		return getPayno(getContext());
	}

	/**
	 * @param context
	 * @return value of Payno
	 */
	public final java.lang.Integer getPayno(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Payno.toString());
	}

	/**
	 * Set value of Payno
	 * @param payno
	 */
	public final void setPayno(java.lang.Integer payno)
	{
		setPayno(getContext(), payno);
	}

	/**
	 * Set value of Payno
	 * @param context
	 * @param payno
	 */
	public final void setPayno(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer payno)
	{
		getMendixObject().setValue(context, MemberNames.Payno.toString(), payno);
	}

	/**
	 * @return value of CreditCardNumber
	 */
	public final java.lang.String getCreditCardNumber()
	{
		return getCreditCardNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of CreditCardNumber
	 */
	public final java.lang.String getCreditCardNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CreditCardNumber.toString());
	}

	/**
	 * Set value of CreditCardNumber
	 * @param creditcardnumber
	 */
	public final void setCreditCardNumber(java.lang.String creditcardnumber)
	{
		setCreditCardNumber(getContext(), creditcardnumber);
	}

	/**
	 * Set value of CreditCardNumber
	 * @param context
	 * @param creditcardnumber
	 */
	public final void setCreditCardNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String creditcardnumber)
	{
		getMendixObject().setValue(context, MemberNames.CreditCardNumber.toString(), creditcardnumber);
	}

	/**
	 * @return value of ExpiryDate
	 */
	public final java.util.Date getExpiryDate()
	{
		return getExpiryDate(getContext());
	}

	/**
	 * @param context
	 * @return value of ExpiryDate
	 */
	public final java.util.Date getExpiryDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.ExpiryDate.toString());
	}

	/**
	 * Set value of ExpiryDate
	 * @param expirydate
	 */
	public final void setExpiryDate(java.util.Date expirydate)
	{
		setExpiryDate(getContext(), expirydate);
	}

	/**
	 * Set value of ExpiryDate
	 * @param context
	 * @param expirydate
	 */
	public final void setExpiryDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date expirydate)
	{
		getMendixObject().setValue(context, MemberNames.ExpiryDate.toString(), expirydate);
	}

	/**
	 * @return value of CVV_Number
	 */
	public final java.lang.Integer getCVV_Number()
	{
		return getCVV_Number(getContext());
	}

	/**
	 * @param context
	 * @return value of CVV_Number
	 */
	public final java.lang.Integer getCVV_Number(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.CVV_Number.toString());
	}

	/**
	 * Set value of CVV_Number
	 * @param cvv_number
	 */
	public final void setCVV_Number(java.lang.Integer cvv_number)
	{
		setCVV_Number(getContext(), cvv_number);
	}

	/**
	 * Set value of CVV_Number
	 * @param context
	 * @param cvv_number
	 */
	public final void setCVV_Number(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer cvv_number)
	{
		getMendixObject().setValue(context, MemberNames.CVV_Number.toString(), cvv_number);
	}

	/**
	 * @return value of ReceiptNo
	 */
	public final java.lang.String getReceiptNo()
	{
		return getReceiptNo(getContext());
	}

	/**
	 * @param context
	 * @return value of ReceiptNo
	 */
	public final java.lang.String getReceiptNo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ReceiptNo.toString());
	}

	/**
	 * Set value of ReceiptNo
	 * @param receiptno
	 */
	public final void setReceiptNo(java.lang.String receiptno)
	{
		setReceiptNo(getContext(), receiptno);
	}

	/**
	 * Set value of ReceiptNo
	 * @param context
	 * @param receiptno
	 */
	public final void setReceiptNo(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String receiptno)
	{
		getMendixObject().setValue(context, MemberNames.ReceiptNo.toString(), receiptno);
	}

	/**
	 * @return value of Payment_BirthCerticate
	 */
	public final myfirstmodule.proxies.BirthCerticate getPayment_BirthCerticate() throws com.mendix.core.CoreException
	{
		return getPayment_BirthCerticate(getContext());
	}

	/**
	 * @param context
	 * @return value of Payment_BirthCerticate
	 */
	public final myfirstmodule.proxies.BirthCerticate getPayment_BirthCerticate(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.BirthCerticate result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Payment_BirthCerticate.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.BirthCerticate.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Payment_BirthCerticate
	 * @param payment_birthcerticate
	 */
	public final void setPayment_BirthCerticate(myfirstmodule.proxies.BirthCerticate payment_birthcerticate)
	{
		setPayment_BirthCerticate(getContext(), payment_birthcerticate);
	}

	/**
	 * Set value of Payment_BirthCerticate
	 * @param context
	 * @param payment_birthcerticate
	 */
	public final void setPayment_BirthCerticate(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.BirthCerticate payment_birthcerticate)
	{
		if (payment_birthcerticate == null)
			getMendixObject().setValue(context, MemberNames.Payment_BirthCerticate.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Payment_BirthCerticate.toString(), payment_birthcerticate.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return paymentMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Payment that = (myfirstmodule.proxies.Payment) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.Payment";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
