// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Payment_Docs extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Payment_Docs";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Doc_Name("Doc_Name"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		Payment_Docs_BirthCerticate("MyFirstModule.Payment_Docs_BirthCerticate");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Payment_Docs(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.Payment_Docs"));
	}

	protected Payment_Docs(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject payment_DocsMendixObject)
	{
		super(context, payment_DocsMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.Payment_Docs", payment_DocsMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.Payment_Docs");
	}

	/**
	 * @deprecated Use 'Payment_Docs.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.Payment_Docs initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Payment_Docs.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.Payment_Docs initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Payment_Docs(context, mendixObject);
	}

	public static myfirstmodule.proxies.Payment_Docs load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Payment_Docs.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Payment_Docs> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.Payment_Docs> result = new java.util.ArrayList<myfirstmodule.proxies.Payment_Docs>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MyFirstModule.Payment_Docs" + xpathConstraint))
			result.add(myfirstmodule.proxies.Payment_Docs.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of Doc_Name
	 */
	public final java.lang.String getDoc_Name()
	{
		return getDoc_Name(getContext());
	}

	/**
	 * @param context
	 * @return value of Doc_Name
	 */
	public final java.lang.String getDoc_Name(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Doc_Name.toString());
	}

	/**
	 * Set value of Doc_Name
	 * @param doc_name
	 */
	public final void setDoc_Name(java.lang.String doc_name)
	{
		setDoc_Name(getContext(), doc_name);
	}

	/**
	 * Set value of Doc_Name
	 * @param context
	 * @param doc_name
	 */
	public final void setDoc_Name(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String doc_name)
	{
		getMendixObject().setValue(context, MemberNames.Doc_Name.toString(), doc_name);
	}

	/**
	 * @return value of Payment_Docs_BirthCerticate
	 */
	public final myfirstmodule.proxies.BirthCerticate getPayment_Docs_BirthCerticate() throws com.mendix.core.CoreException
	{
		return getPayment_Docs_BirthCerticate(getContext());
	}

	/**
	 * @param context
	 * @return value of Payment_Docs_BirthCerticate
	 */
	public final myfirstmodule.proxies.BirthCerticate getPayment_Docs_BirthCerticate(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.BirthCerticate result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Payment_Docs_BirthCerticate.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.BirthCerticate.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Payment_Docs_BirthCerticate
	 * @param payment_docs_birthcerticate
	 */
	public final void setPayment_Docs_BirthCerticate(myfirstmodule.proxies.BirthCerticate payment_docs_birthcerticate)
	{
		setPayment_Docs_BirthCerticate(getContext(), payment_docs_birthcerticate);
	}

	/**
	 * Set value of Payment_Docs_BirthCerticate
	 * @param context
	 * @param payment_docs_birthcerticate
	 */
	public final void setPayment_Docs_BirthCerticate(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.BirthCerticate payment_docs_birthcerticate)
	{
		if (payment_docs_birthcerticate == null)
			getMendixObject().setValue(context, MemberNames.Payment_Docs_BirthCerticate.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Payment_Docs_BirthCerticate.toString(), payment_docs_birthcerticate.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Payment_Docs that = (myfirstmodule.proxies.Payment_Docs) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.Payment_Docs";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
