// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class search
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject searchMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.search";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		input("input"),
		MWarn("MWarn"),
		search_BirthNotification("MyFirstModule.search_BirthNotification");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public search(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.search"));
	}

	protected search(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject searchMendixObject)
	{
		if (searchMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.search", searchMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.search");

		this.searchMendixObject = searchMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'search.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.search initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.search.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.search initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.search(context, mendixObject);
	}

	public static myfirstmodule.proxies.search load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.search.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of input
	 */
	public final java.lang.String getinput()
	{
		return getinput(getContext());
	}

	/**
	 * @param context
	 * @return value of input
	 */
	public final java.lang.String getinput(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.input.toString());
	}

	/**
	 * Set value of input
	 * @param input
	 */
	public final void setinput(java.lang.String input)
	{
		setinput(getContext(), input);
	}

	/**
	 * Set value of input
	 * @param context
	 * @param input
	 */
	public final void setinput(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String input)
	{
		getMendixObject().setValue(context, MemberNames.input.toString(), input);
	}

	/**
	 * @return value of MWarn
	 */
	public final java.lang.String getMWarn()
	{
		return getMWarn(getContext());
	}

	/**
	 * @param context
	 * @return value of MWarn
	 */
	public final java.lang.String getMWarn(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MWarn.toString());
	}

	/**
	 * Set value of MWarn
	 * @param mwarn
	 */
	public final void setMWarn(java.lang.String mwarn)
	{
		setMWarn(getContext(), mwarn);
	}

	/**
	 * Set value of MWarn
	 * @param context
	 * @param mwarn
	 */
	public final void setMWarn(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String mwarn)
	{
		getMendixObject().setValue(context, MemberNames.MWarn.toString(), mwarn);
	}

	/**
	 * @return value of search_BirthNotification
	 */
	public final myfirstmodule.proxies.BirthNotification getsearch_BirthNotification() throws com.mendix.core.CoreException
	{
		return getsearch_BirthNotification(getContext());
	}

	/**
	 * @param context
	 * @return value of search_BirthNotification
	 */
	public final myfirstmodule.proxies.BirthNotification getsearch_BirthNotification(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.BirthNotification result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.search_BirthNotification.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.BirthNotification.load(context, identifier);
		return result;
	}

	/**
	 * Set value of search_BirthNotification
	 * @param search_birthnotification
	 */
	public final void setsearch_BirthNotification(myfirstmodule.proxies.BirthNotification search_birthnotification)
	{
		setsearch_BirthNotification(getContext(), search_birthnotification);
	}

	/**
	 * Set value of search_BirthNotification
	 * @param context
	 * @param search_birthnotification
	 */
	public final void setsearch_BirthNotification(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.BirthNotification search_birthnotification)
	{
		if (search_birthnotification == null)
			getMendixObject().setValue(context, MemberNames.search_BirthNotification.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.search_BirthNotification.toString(), search_birthnotification.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return searchMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.search that = (myfirstmodule.proxies.search) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.search";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
