// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Service
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject serviceMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Service";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		SelectNotitficationService("SelectNotitficationService"),
		SelectCertificateService("SelectCertificateService"),
		IsNotificationSelected("IsNotificationSelected"),
		IsCertificateSelected("IsCertificateSelected"),
		ENUM_Replacementorcopies("ENUM_Replacementorcopies");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Service(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.Service"));
	}

	protected Service(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject serviceMendixObject)
	{
		if (serviceMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.Service", serviceMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.Service");

		this.serviceMendixObject = serviceMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Service.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.Service initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Service.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.Service initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Service(context, mendixObject);
	}

	public static myfirstmodule.proxies.Service load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Service.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * Set value of SelectNotitficationService
	 * @param selectnotitficationservice
	 */
	public final myfirstmodule.proxies.EnumSelectService getSelectNotitficationService()
	{
		return getSelectNotitficationService(getContext());
	}

	/**
	 * @param context
	 * @return value of SelectNotitficationService
	 */
	public final myfirstmodule.proxies.EnumSelectService getSelectNotitficationService(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.SelectNotitficationService.toString());
		if (obj == null)
			return null;

		return myfirstmodule.proxies.EnumSelectService.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of SelectNotitficationService
	 * @param selectnotitficationservice
	 */
	public final void setSelectNotitficationService(myfirstmodule.proxies.EnumSelectService selectnotitficationservice)
	{
		setSelectNotitficationService(getContext(), selectnotitficationservice);
	}

	/**
	 * Set value of SelectNotitficationService
	 * @param context
	 * @param selectnotitficationservice
	 */
	public final void setSelectNotitficationService(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.EnumSelectService selectnotitficationservice)
	{
		if (selectnotitficationservice != null)
			getMendixObject().setValue(context, MemberNames.SelectNotitficationService.toString(), selectnotitficationservice.toString());
		else
			getMendixObject().setValue(context, MemberNames.SelectNotitficationService.toString(), null);
	}

	/**
	 * Set value of SelectCertificateService
	 * @param selectcertificateservice
	 */
	public final myfirstmodule.proxies.EnumCertificateService getSelectCertificateService()
	{
		return getSelectCertificateService(getContext());
	}

	/**
	 * @param context
	 * @return value of SelectCertificateService
	 */
	public final myfirstmodule.proxies.EnumCertificateService getSelectCertificateService(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.SelectCertificateService.toString());
		if (obj == null)
			return null;

		return myfirstmodule.proxies.EnumCertificateService.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of SelectCertificateService
	 * @param selectcertificateservice
	 */
	public final void setSelectCertificateService(myfirstmodule.proxies.EnumCertificateService selectcertificateservice)
	{
		setSelectCertificateService(getContext(), selectcertificateservice);
	}

	/**
	 * Set value of SelectCertificateService
	 * @param context
	 * @param selectcertificateservice
	 */
	public final void setSelectCertificateService(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.EnumCertificateService selectcertificateservice)
	{
		if (selectcertificateservice != null)
			getMendixObject().setValue(context, MemberNames.SelectCertificateService.toString(), selectcertificateservice.toString());
		else
			getMendixObject().setValue(context, MemberNames.SelectCertificateService.toString(), null);
	}

	/**
	 * @return value of IsNotificationSelected
	 */
	public final java.lang.Boolean getIsNotificationSelected()
	{
		return getIsNotificationSelected(getContext());
	}

	/**
	 * @param context
	 * @return value of IsNotificationSelected
	 */
	public final java.lang.Boolean getIsNotificationSelected(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsNotificationSelected.toString());
	}

	/**
	 * Set value of IsNotificationSelected
	 * @param isnotificationselected
	 */
	public final void setIsNotificationSelected(java.lang.Boolean isnotificationselected)
	{
		setIsNotificationSelected(getContext(), isnotificationselected);
	}

	/**
	 * Set value of IsNotificationSelected
	 * @param context
	 * @param isnotificationselected
	 */
	public final void setIsNotificationSelected(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isnotificationselected)
	{
		getMendixObject().setValue(context, MemberNames.IsNotificationSelected.toString(), isnotificationselected);
	}

	/**
	 * @return value of IsCertificateSelected
	 */
	public final java.lang.Boolean getIsCertificateSelected()
	{
		return getIsCertificateSelected(getContext());
	}

	/**
	 * @param context
	 * @return value of IsCertificateSelected
	 */
	public final java.lang.Boolean getIsCertificateSelected(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsCertificateSelected.toString());
	}

	/**
	 * Set value of IsCertificateSelected
	 * @param iscertificateselected
	 */
	public final void setIsCertificateSelected(java.lang.Boolean iscertificateselected)
	{
		setIsCertificateSelected(getContext(), iscertificateselected);
	}

	/**
	 * Set value of IsCertificateSelected
	 * @param context
	 * @param iscertificateselected
	 */
	public final void setIsCertificateSelected(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean iscertificateselected)
	{
		getMendixObject().setValue(context, MemberNames.IsCertificateSelected.toString(), iscertificateselected);
	}

	/**
	 * Set value of ENUM_Replacementorcopies
	 * @param enum_replacementorcopies
	 */
	public final myfirstmodule.proxies.ENUM_Replacementservice getENUM_Replacementorcopies()
	{
		return getENUM_Replacementorcopies(getContext());
	}

	/**
	 * @param context
	 * @return value of ENUM_Replacementorcopies
	 */
	public final myfirstmodule.proxies.ENUM_Replacementservice getENUM_Replacementorcopies(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ENUM_Replacementorcopies.toString());
		if (obj == null)
			return null;

		return myfirstmodule.proxies.ENUM_Replacementservice.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ENUM_Replacementorcopies
	 * @param enum_replacementorcopies
	 */
	public final void setENUM_Replacementorcopies(myfirstmodule.proxies.ENUM_Replacementservice enum_replacementorcopies)
	{
		setENUM_Replacementorcopies(getContext(), enum_replacementorcopies);
	}

	/**
	 * Set value of ENUM_Replacementorcopies
	 * @param context
	 * @param enum_replacementorcopies
	 */
	public final void setENUM_Replacementorcopies(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.ENUM_Replacementservice enum_replacementorcopies)
	{
		if (enum_replacementorcopies != null)
			getMendixObject().setValue(context, MemberNames.ENUM_Replacementorcopies.toString(), enum_replacementorcopies.toString());
		else
			getMendixObject().setValue(context, MemberNames.ENUM_Replacementorcopies.toString(), null);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return serviceMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Service that = (myfirstmodule.proxies.Service) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.Service";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
