// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package requestforpreliminaryregistrationofafacility_hospital.proxies;

public class BedsAllocation
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject bedsAllocationMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "RequestforPreliminaryRegistrationofaFacility_Hospital.BedsAllocation";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Category("Category"),
		BedType("BedType"),
		NumberOfBeds("NumberOfBeds"),
		BedsAllocation_Preliminary("RequestforPreliminaryRegistrationofaFacility_Hospital.BedsAllocation_Preliminary"),
		BedsAllocation_Bed_catagory("RequestforPreliminaryRegistrationofaFacility_Hospital.BedsAllocation_Bed_catagory"),
		BedsAllocation_Bed_Type("RequestforPreliminaryRegistrationofaFacility_Hospital.BedsAllocation_Bed_Type");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public BedsAllocation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "RequestforPreliminaryRegistrationofaFacility_Hospital.BedsAllocation"));
	}

	protected BedsAllocation(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject bedsAllocationMendixObject)
	{
		if (bedsAllocationMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("RequestforPreliminaryRegistrationofaFacility_Hospital.BedsAllocation", bedsAllocationMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a RequestforPreliminaryRegistrationofaFacility_Hospital.BedsAllocation");

		this.bedsAllocationMendixObject = bedsAllocationMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'BedsAllocation.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static requestforpreliminaryregistrationofafacility_hospital.proxies.BedsAllocation initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return requestforpreliminaryregistrationofafacility_hospital.proxies.BedsAllocation.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static requestforpreliminaryregistrationofafacility_hospital.proxies.BedsAllocation initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new requestforpreliminaryregistrationofafacility_hospital.proxies.BedsAllocation(context, mendixObject);
	}

	public static requestforpreliminaryregistrationofafacility_hospital.proxies.BedsAllocation load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return requestforpreliminaryregistrationofafacility_hospital.proxies.BedsAllocation.initialize(context, mendixObject);
	}

	public static java.util.List<requestforpreliminaryregistrationofafacility_hospital.proxies.BedsAllocation> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<requestforpreliminaryregistrationofafacility_hospital.proxies.BedsAllocation> result = new java.util.ArrayList<requestforpreliminaryregistrationofafacility_hospital.proxies.BedsAllocation>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//RequestforPreliminaryRegistrationofaFacility_Hospital.BedsAllocation" + xpathConstraint))
			result.add(requestforpreliminaryregistrationofafacility_hospital.proxies.BedsAllocation.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Category
	 */
	public final java.lang.String getCategory()
	{
		return getCategory(getContext());
	}

	/**
	 * @param context
	 * @return value of Category
	 */
	public final java.lang.String getCategory(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Category.toString());
	}

	/**
	 * Set value of Category
	 * @param category
	 */
	public final void setCategory(java.lang.String category)
	{
		setCategory(getContext(), category);
	}

	/**
	 * Set value of Category
	 * @param context
	 * @param category
	 */
	public final void setCategory(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String category)
	{
		getMendixObject().setValue(context, MemberNames.Category.toString(), category);
	}

	/**
	 * @return value of BedType
	 */
	public final java.lang.String getBedType()
	{
		return getBedType(getContext());
	}

	/**
	 * @param context
	 * @return value of BedType
	 */
	public final java.lang.String getBedType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.BedType.toString());
	}

	/**
	 * Set value of BedType
	 * @param bedtype
	 */
	public final void setBedType(java.lang.String bedtype)
	{
		setBedType(getContext(), bedtype);
	}

	/**
	 * Set value of BedType
	 * @param context
	 * @param bedtype
	 */
	public final void setBedType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String bedtype)
	{
		getMendixObject().setValue(context, MemberNames.BedType.toString(), bedtype);
	}

	/**
	 * @return value of NumberOfBeds
	 */
	public final java.lang.Integer getNumberOfBeds()
	{
		return getNumberOfBeds(getContext());
	}

	/**
	 * @param context
	 * @return value of NumberOfBeds
	 */
	public final java.lang.Integer getNumberOfBeds(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.NumberOfBeds.toString());
	}

	/**
	 * Set value of NumberOfBeds
	 * @param numberofbeds
	 */
	public final void setNumberOfBeds(java.lang.Integer numberofbeds)
	{
		setNumberOfBeds(getContext(), numberofbeds);
	}

	/**
	 * Set value of NumberOfBeds
	 * @param context
	 * @param numberofbeds
	 */
	public final void setNumberOfBeds(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer numberofbeds)
	{
		getMendixObject().setValue(context, MemberNames.NumberOfBeds.toString(), numberofbeds);
	}

	/**
	 * @return value of BedsAllocation_Preliminary
	 */
	public final requestforpreliminaryregistrationofafacility_hospital.proxies.Preliminary getBedsAllocation_Preliminary() throws com.mendix.core.CoreException
	{
		return getBedsAllocation_Preliminary(getContext());
	}

	/**
	 * @param context
	 * @return value of BedsAllocation_Preliminary
	 */
	public final requestforpreliminaryregistrationofafacility_hospital.proxies.Preliminary getBedsAllocation_Preliminary(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		requestforpreliminaryregistrationofafacility_hospital.proxies.Preliminary result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.BedsAllocation_Preliminary.toString());
		if (identifier != null)
			result = requestforpreliminaryregistrationofafacility_hospital.proxies.Preliminary.load(context, identifier);
		return result;
	}

	/**
	 * Set value of BedsAllocation_Preliminary
	 * @param bedsallocation_preliminary
	 */
	public final void setBedsAllocation_Preliminary(requestforpreliminaryregistrationofafacility_hospital.proxies.Preliminary bedsallocation_preliminary)
	{
		setBedsAllocation_Preliminary(getContext(), bedsallocation_preliminary);
	}

	/**
	 * Set value of BedsAllocation_Preliminary
	 * @param context
	 * @param bedsallocation_preliminary
	 */
	public final void setBedsAllocation_Preliminary(com.mendix.systemwideinterfaces.core.IContext context, requestforpreliminaryregistrationofafacility_hospital.proxies.Preliminary bedsallocation_preliminary)
	{
		if (bedsallocation_preliminary == null)
			getMendixObject().setValue(context, MemberNames.BedsAllocation_Preliminary.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.BedsAllocation_Preliminary.toString(), bedsallocation_preliminary.getMendixObject().getId());
	}

	/**
	 * @return value of BedsAllocation_Bed_catagory
	 */
	public final requestforpreliminaryregistrationofafacility_hospital.proxies.Bed_catagory getBedsAllocation_Bed_catagory() throws com.mendix.core.CoreException
	{
		return getBedsAllocation_Bed_catagory(getContext());
	}

	/**
	 * @param context
	 * @return value of BedsAllocation_Bed_catagory
	 */
	public final requestforpreliminaryregistrationofafacility_hospital.proxies.Bed_catagory getBedsAllocation_Bed_catagory(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		requestforpreliminaryregistrationofafacility_hospital.proxies.Bed_catagory result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.BedsAllocation_Bed_catagory.toString());
		if (identifier != null)
			result = requestforpreliminaryregistrationofafacility_hospital.proxies.Bed_catagory.load(context, identifier);
		return result;
	}

	/**
	 * Set value of BedsAllocation_Bed_catagory
	 * @param bedsallocation_bed_catagory
	 */
	public final void setBedsAllocation_Bed_catagory(requestforpreliminaryregistrationofafacility_hospital.proxies.Bed_catagory bedsallocation_bed_catagory)
	{
		setBedsAllocation_Bed_catagory(getContext(), bedsallocation_bed_catagory);
	}

	/**
	 * Set value of BedsAllocation_Bed_catagory
	 * @param context
	 * @param bedsallocation_bed_catagory
	 */
	public final void setBedsAllocation_Bed_catagory(com.mendix.systemwideinterfaces.core.IContext context, requestforpreliminaryregistrationofafacility_hospital.proxies.Bed_catagory bedsallocation_bed_catagory)
	{
		if (bedsallocation_bed_catagory == null)
			getMendixObject().setValue(context, MemberNames.BedsAllocation_Bed_catagory.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.BedsAllocation_Bed_catagory.toString(), bedsallocation_bed_catagory.getMendixObject().getId());
	}

	/**
	 * @return value of BedsAllocation_Bed_Type
	 */
	public final requestforpreliminaryregistrationofafacility_hospital.proxies.Bed_Type getBedsAllocation_Bed_Type() throws com.mendix.core.CoreException
	{
		return getBedsAllocation_Bed_Type(getContext());
	}

	/**
	 * @param context
	 * @return value of BedsAllocation_Bed_Type
	 */
	public final requestforpreliminaryregistrationofafacility_hospital.proxies.Bed_Type getBedsAllocation_Bed_Type(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		requestforpreliminaryregistrationofafacility_hospital.proxies.Bed_Type result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.BedsAllocation_Bed_Type.toString());
		if (identifier != null)
			result = requestforpreliminaryregistrationofafacility_hospital.proxies.Bed_Type.load(context, identifier);
		return result;
	}

	/**
	 * Set value of BedsAllocation_Bed_Type
	 * @param bedsallocation_bed_type
	 */
	public final void setBedsAllocation_Bed_Type(requestforpreliminaryregistrationofafacility_hospital.proxies.Bed_Type bedsallocation_bed_type)
	{
		setBedsAllocation_Bed_Type(getContext(), bedsallocation_bed_type);
	}

	/**
	 * Set value of BedsAllocation_Bed_Type
	 * @param context
	 * @param bedsallocation_bed_type
	 */
	public final void setBedsAllocation_Bed_Type(com.mendix.systemwideinterfaces.core.IContext context, requestforpreliminaryregistrationofafacility_hospital.proxies.Bed_Type bedsallocation_bed_type)
	{
		if (bedsallocation_bed_type == null)
			getMendixObject().setValue(context, MemberNames.BedsAllocation_Bed_Type.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.BedsAllocation_Bed_Type.toString(), bedsallocation_bed_type.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return bedsAllocationMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final requestforpreliminaryregistrationofafacility_hospital.proxies.BedsAllocation that = (requestforpreliminaryregistrationofafacility_hospital.proxies.BedsAllocation) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "RequestforPreliminaryRegistrationofaFacility_Hospital.BedsAllocation";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
