// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package requestforpreliminaryregistrationofafacility_hospital.proxies;

public enum ENUM_InpatientServices
{
	Maternity_Emergency_Department(new java.lang.String[][] { new java.lang.String[] { "en_US", "Maternity Emergency Department" } }),
	Urgent_Care_Centers(new java.lang.String[][] { new java.lang.String[] { "en_US", "Urgent Care Centers" } }),
	Pediatric_Emergency_Department(new java.lang.String[][] { new java.lang.String[] { "en_US", "Pediatric Emergency Department" } }),
	Remote_Emergency_Department(new java.lang.String[][] { new java.lang.String[] { "en_US", "Remote Emergency Department" } }),
	Emergency_Department(new java.lang.String[][] { new java.lang.String[] { "en_US", "Emergency Department" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private ENUM_InpatientServices(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
