// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package requestforpreliminaryregistrationofafacility_hospital.proxies;

public enum ENUM_Status
{
	In_Progress(new java.lang.String[][] { new java.lang.String[] { "en_US", "In Progress" } }),
	Reviewed_by_Committee(new java.lang.String[][] { new java.lang.String[] { "en_US", "Reviewed by Committee" } }),
	Reviewed_by_ICMD(new java.lang.String[][] { new java.lang.String[] { "en_US", "Reviewed by ICMD" } }),
	Approved_by_Committee_Chairman(new java.lang.String[][] { new java.lang.String[] { "en_US", "Approved by Committee Chairman" } }),
	Approved_by_Department_Manager(new java.lang.String[][] { new java.lang.String[] { "en_US", "Approved by Department Manager" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private ENUM_Status(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
