// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package requestforpreliminaryregistrationofafacility_hospital.proxies;

public class HospitalDetails
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject hospitalDetailsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "RequestforPreliminaryRegistrationofaFacility_Hospital.HospitalDetails";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		InpatientServices("InpatientServices"),
		RecoveryRoom("RecoveryRoom"),
		DeliveryRoom("DeliveryRoom"),
		CSSDRoom("CSSDRoom"),
		Endoscopy("Endoscopy"),
		OperationTheatreUnit("OperationTheatreUnit"),
		MinorOTRooms("MinorOTRooms"),
		MajorOTRooms("MajorOTRooms"),
		XRayMedicalDiagnostic("XRayMedicalDiagnostic"),
		MedicalLaboratory("MedicalLaboratory"),
		maternity("maternity"),
		Pediatric("Pediatric"),
		Remote("Remote"),
		Emergency("Emergency"),
		Urgent("Urgent"),
		Consultant("Consultant"),
		Treatment("Treatment"),
		HospitalDetails_Preliminary("RequestforPreliminaryRegistrationofaFacility_Hospital.HospitalDetails_Preliminary");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public HospitalDetails(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "RequestforPreliminaryRegistrationofaFacility_Hospital.HospitalDetails"));
	}

	protected HospitalDetails(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject hospitalDetailsMendixObject)
	{
		if (hospitalDetailsMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("RequestforPreliminaryRegistrationofaFacility_Hospital.HospitalDetails", hospitalDetailsMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a RequestforPreliminaryRegistrationofaFacility_Hospital.HospitalDetails");

		this.hospitalDetailsMendixObject = hospitalDetailsMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'HospitalDetails.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static requestforpreliminaryregistrationofafacility_hospital.proxies.HospitalDetails initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return requestforpreliminaryregistrationofafacility_hospital.proxies.HospitalDetails.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static requestforpreliminaryregistrationofafacility_hospital.proxies.HospitalDetails initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new requestforpreliminaryregistrationofafacility_hospital.proxies.HospitalDetails(context, mendixObject);
	}

	public static requestforpreliminaryregistrationofafacility_hospital.proxies.HospitalDetails load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return requestforpreliminaryregistrationofafacility_hospital.proxies.HospitalDetails.initialize(context, mendixObject);
	}

	public static java.util.List<requestforpreliminaryregistrationofafacility_hospital.proxies.HospitalDetails> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<requestforpreliminaryregistrationofafacility_hospital.proxies.HospitalDetails> result = new java.util.ArrayList<requestforpreliminaryregistrationofafacility_hospital.proxies.HospitalDetails>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//RequestforPreliminaryRegistrationofaFacility_Hospital.HospitalDetails" + xpathConstraint))
			result.add(requestforpreliminaryregistrationofafacility_hospital.proxies.HospitalDetails.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * Set value of InpatientServices
	 * @param inpatientservices
	 */
	public final requestforpreliminaryregistrationofafacility_hospital.proxies.ENUM_InpatientServices getInpatientServices()
	{
		return getInpatientServices(getContext());
	}

	/**
	 * @param context
	 * @return value of InpatientServices
	 */
	public final requestforpreliminaryregistrationofafacility_hospital.proxies.ENUM_InpatientServices getInpatientServices(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.InpatientServices.toString());
		if (obj == null)
			return null;

		return requestforpreliminaryregistrationofafacility_hospital.proxies.ENUM_InpatientServices.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of InpatientServices
	 * @param inpatientservices
	 */
	public final void setInpatientServices(requestforpreliminaryregistrationofafacility_hospital.proxies.ENUM_InpatientServices inpatientservices)
	{
		setInpatientServices(getContext(), inpatientservices);
	}

	/**
	 * Set value of InpatientServices
	 * @param context
	 * @param inpatientservices
	 */
	public final void setInpatientServices(com.mendix.systemwideinterfaces.core.IContext context, requestforpreliminaryregistrationofafacility_hospital.proxies.ENUM_InpatientServices inpatientservices)
	{
		if (inpatientservices != null)
			getMendixObject().setValue(context, MemberNames.InpatientServices.toString(), inpatientservices.toString());
		else
			getMendixObject().setValue(context, MemberNames.InpatientServices.toString(), null);
	}

	/**
	 * @return value of RecoveryRoom
	 */
	public final java.lang.Integer getRecoveryRoom()
	{
		return getRecoveryRoom(getContext());
	}

	/**
	 * @param context
	 * @return value of RecoveryRoom
	 */
	public final java.lang.Integer getRecoveryRoom(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.RecoveryRoom.toString());
	}

	/**
	 * Set value of RecoveryRoom
	 * @param recoveryroom
	 */
	public final void setRecoveryRoom(java.lang.Integer recoveryroom)
	{
		setRecoveryRoom(getContext(), recoveryroom);
	}

	/**
	 * Set value of RecoveryRoom
	 * @param context
	 * @param recoveryroom
	 */
	public final void setRecoveryRoom(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer recoveryroom)
	{
		getMendixObject().setValue(context, MemberNames.RecoveryRoom.toString(), recoveryroom);
	}

	/**
	 * @return value of DeliveryRoom
	 */
	public final java.lang.Integer getDeliveryRoom()
	{
		return getDeliveryRoom(getContext());
	}

	/**
	 * @param context
	 * @return value of DeliveryRoom
	 */
	public final java.lang.Integer getDeliveryRoom(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.DeliveryRoom.toString());
	}

	/**
	 * Set value of DeliveryRoom
	 * @param deliveryroom
	 */
	public final void setDeliveryRoom(java.lang.Integer deliveryroom)
	{
		setDeliveryRoom(getContext(), deliveryroom);
	}

	/**
	 * Set value of DeliveryRoom
	 * @param context
	 * @param deliveryroom
	 */
	public final void setDeliveryRoom(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer deliveryroom)
	{
		getMendixObject().setValue(context, MemberNames.DeliveryRoom.toString(), deliveryroom);
	}

	/**
	 * @return value of CSSDRoom
	 */
	public final java.lang.Integer getCSSDRoom()
	{
		return getCSSDRoom(getContext());
	}

	/**
	 * @param context
	 * @return value of CSSDRoom
	 */
	public final java.lang.Integer getCSSDRoom(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.CSSDRoom.toString());
	}

	/**
	 * Set value of CSSDRoom
	 * @param cssdroom
	 */
	public final void setCSSDRoom(java.lang.Integer cssdroom)
	{
		setCSSDRoom(getContext(), cssdroom);
	}

	/**
	 * Set value of CSSDRoom
	 * @param context
	 * @param cssdroom
	 */
	public final void setCSSDRoom(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer cssdroom)
	{
		getMendixObject().setValue(context, MemberNames.CSSDRoom.toString(), cssdroom);
	}

	/**
	 * @return value of Endoscopy
	 */
	public final java.lang.Integer getEndoscopy()
	{
		return getEndoscopy(getContext());
	}

	/**
	 * @param context
	 * @return value of Endoscopy
	 */
	public final java.lang.Integer getEndoscopy(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Endoscopy.toString());
	}

	/**
	 * Set value of Endoscopy
	 * @param endoscopy
	 */
	public final void setEndoscopy(java.lang.Integer endoscopy)
	{
		setEndoscopy(getContext(), endoscopy);
	}

	/**
	 * Set value of Endoscopy
	 * @param context
	 * @param endoscopy
	 */
	public final void setEndoscopy(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer endoscopy)
	{
		getMendixObject().setValue(context, MemberNames.Endoscopy.toString(), endoscopy);
	}

	/**
	 * @return value of OperationTheatreUnit
	 */
	public final java.lang.Boolean getOperationTheatreUnit()
	{
		return getOperationTheatreUnit(getContext());
	}

	/**
	 * @param context
	 * @return value of OperationTheatreUnit
	 */
	public final java.lang.Boolean getOperationTheatreUnit(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.OperationTheatreUnit.toString());
	}

	/**
	 * Set value of OperationTheatreUnit
	 * @param operationtheatreunit
	 */
	public final void setOperationTheatreUnit(java.lang.Boolean operationtheatreunit)
	{
		setOperationTheatreUnit(getContext(), operationtheatreunit);
	}

	/**
	 * Set value of OperationTheatreUnit
	 * @param context
	 * @param operationtheatreunit
	 */
	public final void setOperationTheatreUnit(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean operationtheatreunit)
	{
		getMendixObject().setValue(context, MemberNames.OperationTheatreUnit.toString(), operationtheatreunit);
	}

	/**
	 * @return value of MinorOTRooms
	 */
	public final java.lang.Integer getMinorOTRooms()
	{
		return getMinorOTRooms(getContext());
	}

	/**
	 * @param context
	 * @return value of MinorOTRooms
	 */
	public final java.lang.Integer getMinorOTRooms(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.MinorOTRooms.toString());
	}

	/**
	 * Set value of MinorOTRooms
	 * @param minorotrooms
	 */
	public final void setMinorOTRooms(java.lang.Integer minorotrooms)
	{
		setMinorOTRooms(getContext(), minorotrooms);
	}

	/**
	 * Set value of MinorOTRooms
	 * @param context
	 * @param minorotrooms
	 */
	public final void setMinorOTRooms(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer minorotrooms)
	{
		getMendixObject().setValue(context, MemberNames.MinorOTRooms.toString(), minorotrooms);
	}

	/**
	 * @return value of MajorOTRooms
	 */
	public final java.lang.Integer getMajorOTRooms()
	{
		return getMajorOTRooms(getContext());
	}

	/**
	 * @param context
	 * @return value of MajorOTRooms
	 */
	public final java.lang.Integer getMajorOTRooms(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.MajorOTRooms.toString());
	}

	/**
	 * Set value of MajorOTRooms
	 * @param majorotrooms
	 */
	public final void setMajorOTRooms(java.lang.Integer majorotrooms)
	{
		setMajorOTRooms(getContext(), majorotrooms);
	}

	/**
	 * Set value of MajorOTRooms
	 * @param context
	 * @param majorotrooms
	 */
	public final void setMajorOTRooms(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer majorotrooms)
	{
		getMendixObject().setValue(context, MemberNames.MajorOTRooms.toString(), majorotrooms);
	}

	/**
	 * @return value of XRayMedicalDiagnostic
	 */
	public final java.lang.Boolean getXRayMedicalDiagnostic()
	{
		return getXRayMedicalDiagnostic(getContext());
	}

	/**
	 * @param context
	 * @return value of XRayMedicalDiagnostic
	 */
	public final java.lang.Boolean getXRayMedicalDiagnostic(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.XRayMedicalDiagnostic.toString());
	}

	/**
	 * Set value of XRayMedicalDiagnostic
	 * @param xraymedicaldiagnostic
	 */
	public final void setXRayMedicalDiagnostic(java.lang.Boolean xraymedicaldiagnostic)
	{
		setXRayMedicalDiagnostic(getContext(), xraymedicaldiagnostic);
	}

	/**
	 * Set value of XRayMedicalDiagnostic
	 * @param context
	 * @param xraymedicaldiagnostic
	 */
	public final void setXRayMedicalDiagnostic(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean xraymedicaldiagnostic)
	{
		getMendixObject().setValue(context, MemberNames.XRayMedicalDiagnostic.toString(), xraymedicaldiagnostic);
	}

	/**
	 * @return value of MedicalLaboratory
	 */
	public final java.lang.Boolean getMedicalLaboratory()
	{
		return getMedicalLaboratory(getContext());
	}

	/**
	 * @param context
	 * @return value of MedicalLaboratory
	 */
	public final java.lang.Boolean getMedicalLaboratory(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.MedicalLaboratory.toString());
	}

	/**
	 * Set value of MedicalLaboratory
	 * @param medicallaboratory
	 */
	public final void setMedicalLaboratory(java.lang.Boolean medicallaboratory)
	{
		setMedicalLaboratory(getContext(), medicallaboratory);
	}

	/**
	 * Set value of MedicalLaboratory
	 * @param context
	 * @param medicallaboratory
	 */
	public final void setMedicalLaboratory(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean medicallaboratory)
	{
		getMendixObject().setValue(context, MemberNames.MedicalLaboratory.toString(), medicallaboratory);
	}

	/**
	 * @return value of maternity
	 */
	public final java.lang.Boolean getmaternity()
	{
		return getmaternity(getContext());
	}

	/**
	 * @param context
	 * @return value of maternity
	 */
	public final java.lang.Boolean getmaternity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.maternity.toString());
	}

	/**
	 * Set value of maternity
	 * @param maternity
	 */
	public final void setmaternity(java.lang.Boolean maternity)
	{
		setmaternity(getContext(), maternity);
	}

	/**
	 * Set value of maternity
	 * @param context
	 * @param maternity
	 */
	public final void setmaternity(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean maternity)
	{
		getMendixObject().setValue(context, MemberNames.maternity.toString(), maternity);
	}

	/**
	 * @return value of Pediatric
	 */
	public final java.lang.Boolean getPediatric()
	{
		return getPediatric(getContext());
	}

	/**
	 * @param context
	 * @return value of Pediatric
	 */
	public final java.lang.Boolean getPediatric(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Pediatric.toString());
	}

	/**
	 * Set value of Pediatric
	 * @param pediatric
	 */
	public final void setPediatric(java.lang.Boolean pediatric)
	{
		setPediatric(getContext(), pediatric);
	}

	/**
	 * Set value of Pediatric
	 * @param context
	 * @param pediatric
	 */
	public final void setPediatric(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean pediatric)
	{
		getMendixObject().setValue(context, MemberNames.Pediatric.toString(), pediatric);
	}

	/**
	 * @return value of Remote
	 */
	public final java.lang.Boolean getRemote()
	{
		return getRemote(getContext());
	}

	/**
	 * @param context
	 * @return value of Remote
	 */
	public final java.lang.Boolean getRemote(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Remote.toString());
	}

	/**
	 * Set value of Remote
	 * @param remote
	 */
	public final void setRemote(java.lang.Boolean remote)
	{
		setRemote(getContext(), remote);
	}

	/**
	 * Set value of Remote
	 * @param context
	 * @param remote
	 */
	public final void setRemote(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean remote)
	{
		getMendixObject().setValue(context, MemberNames.Remote.toString(), remote);
	}

	/**
	 * @return value of Emergency
	 */
	public final java.lang.Boolean getEmergency()
	{
		return getEmergency(getContext());
	}

	/**
	 * @param context
	 * @return value of Emergency
	 */
	public final java.lang.Boolean getEmergency(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Emergency.toString());
	}

	/**
	 * Set value of Emergency
	 * @param emergency
	 */
	public final void setEmergency(java.lang.Boolean emergency)
	{
		setEmergency(getContext(), emergency);
	}

	/**
	 * Set value of Emergency
	 * @param context
	 * @param emergency
	 */
	public final void setEmergency(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean emergency)
	{
		getMendixObject().setValue(context, MemberNames.Emergency.toString(), emergency);
	}

	/**
	 * @return value of Urgent
	 */
	public final java.lang.Boolean getUrgent()
	{
		return getUrgent(getContext());
	}

	/**
	 * @param context
	 * @return value of Urgent
	 */
	public final java.lang.Boolean getUrgent(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Urgent.toString());
	}

	/**
	 * Set value of Urgent
	 * @param urgent
	 */
	public final void setUrgent(java.lang.Boolean urgent)
	{
		setUrgent(getContext(), urgent);
	}

	/**
	 * Set value of Urgent
	 * @param context
	 * @param urgent
	 */
	public final void setUrgent(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean urgent)
	{
		getMendixObject().setValue(context, MemberNames.Urgent.toString(), urgent);
	}

	/**
	 * @return value of Consultant
	 */
	public final java.lang.Integer getConsultant()
	{
		return getConsultant(getContext());
	}

	/**
	 * @param context
	 * @return value of Consultant
	 */
	public final java.lang.Integer getConsultant(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Consultant.toString());
	}

	/**
	 * Set value of Consultant
	 * @param consultant
	 */
	public final void setConsultant(java.lang.Integer consultant)
	{
		setConsultant(getContext(), consultant);
	}

	/**
	 * Set value of Consultant
	 * @param context
	 * @param consultant
	 */
	public final void setConsultant(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer consultant)
	{
		getMendixObject().setValue(context, MemberNames.Consultant.toString(), consultant);
	}

	/**
	 * @return value of Treatment
	 */
	public final java.lang.Integer getTreatment()
	{
		return getTreatment(getContext());
	}

	/**
	 * @param context
	 * @return value of Treatment
	 */
	public final java.lang.Integer getTreatment(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Treatment.toString());
	}

	/**
	 * Set value of Treatment
	 * @param treatment
	 */
	public final void setTreatment(java.lang.Integer treatment)
	{
		setTreatment(getContext(), treatment);
	}

	/**
	 * Set value of Treatment
	 * @param context
	 * @param treatment
	 */
	public final void setTreatment(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer treatment)
	{
		getMendixObject().setValue(context, MemberNames.Treatment.toString(), treatment);
	}

	/**
	 * @return value of HospitalDetails_Preliminary
	 */
	public final requestforpreliminaryregistrationofafacility_hospital.proxies.Preliminary getHospitalDetails_Preliminary() throws com.mendix.core.CoreException
	{
		return getHospitalDetails_Preliminary(getContext());
	}

	/**
	 * @param context
	 * @return value of HospitalDetails_Preliminary
	 */
	public final requestforpreliminaryregistrationofafacility_hospital.proxies.Preliminary getHospitalDetails_Preliminary(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		requestforpreliminaryregistrationofafacility_hospital.proxies.Preliminary result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.HospitalDetails_Preliminary.toString());
		if (identifier != null)
			result = requestforpreliminaryregistrationofafacility_hospital.proxies.Preliminary.load(context, identifier);
		return result;
	}

	/**
	 * Set value of HospitalDetails_Preliminary
	 * @param hospitaldetails_preliminary
	 */
	public final void setHospitalDetails_Preliminary(requestforpreliminaryregistrationofafacility_hospital.proxies.Preliminary hospitaldetails_preliminary)
	{
		setHospitalDetails_Preliminary(getContext(), hospitaldetails_preliminary);
	}

	/**
	 * Set value of HospitalDetails_Preliminary
	 * @param context
	 * @param hospitaldetails_preliminary
	 */
	public final void setHospitalDetails_Preliminary(com.mendix.systemwideinterfaces.core.IContext context, requestforpreliminaryregistrationofafacility_hospital.proxies.Preliminary hospitaldetails_preliminary)
	{
		if (hospitaldetails_preliminary == null)
			getMendixObject().setValue(context, MemberNames.HospitalDetails_Preliminary.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.HospitalDetails_Preliminary.toString(), hospitaldetails_preliminary.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return hospitalDetailsMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final requestforpreliminaryregistrationofafacility_hospital.proxies.HospitalDetails that = (requestforpreliminaryregistrationofafacility_hospital.proxies.HospitalDetails) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "RequestforPreliminaryRegistrationofaFacility_Hospital.HospitalDetails";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
