// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package requestforpreliminaryregistrationofafacility_hospital.proxies;

public class Medical_Vocation
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject medical_VocationMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "RequestforPreliminaryRegistrationofaFacility_Hospital.Medical_Vocation";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Catagory("Catagory"),
		Major("Major"),
		Profession("Profession"),
		MinimumNoOfStaffs("MinimumNoOfStaffs"),
		ProposedStaff("ProposedStaff"),
		Medical_Vocation_Specialiti("RequestforPreliminaryRegistrationofaFacility_Hospital.Medical_Vocation_Specialiti"),
		Medical_Vocation_Servies("RequestforPreliminaryRegistrationofaFacility_Hospital.Medical_Vocation_Servies"),
		Medical_Vocation_Preliminary("RequestforPreliminaryRegistrationofaFacility_Hospital.Medical_Vocation_Preliminary");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Medical_Vocation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "RequestforPreliminaryRegistrationofaFacility_Hospital.Medical_Vocation"));
	}

	protected Medical_Vocation(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject medical_VocationMendixObject)
	{
		if (medical_VocationMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("RequestforPreliminaryRegistrationofaFacility_Hospital.Medical_Vocation", medical_VocationMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a RequestforPreliminaryRegistrationofaFacility_Hospital.Medical_Vocation");

		this.medical_VocationMendixObject = medical_VocationMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Medical_Vocation.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static requestforpreliminaryregistrationofafacility_hospital.proxies.Medical_Vocation initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return requestforpreliminaryregistrationofafacility_hospital.proxies.Medical_Vocation.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static requestforpreliminaryregistrationofafacility_hospital.proxies.Medical_Vocation initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new requestforpreliminaryregistrationofafacility_hospital.proxies.Medical_Vocation(context, mendixObject);
	}

	public static requestforpreliminaryregistrationofafacility_hospital.proxies.Medical_Vocation load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return requestforpreliminaryregistrationofafacility_hospital.proxies.Medical_Vocation.initialize(context, mendixObject);
	}

	public static java.util.List<requestforpreliminaryregistrationofafacility_hospital.proxies.Medical_Vocation> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<requestforpreliminaryregistrationofafacility_hospital.proxies.Medical_Vocation> result = new java.util.ArrayList<requestforpreliminaryregistrationofafacility_hospital.proxies.Medical_Vocation>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//RequestforPreliminaryRegistrationofaFacility_Hospital.Medical_Vocation" + xpathConstraint))
			result.add(requestforpreliminaryregistrationofafacility_hospital.proxies.Medical_Vocation.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Catagory
	 */
	public final java.lang.String getCatagory()
	{
		return getCatagory(getContext());
	}

	/**
	 * @param context
	 * @return value of Catagory
	 */
	public final java.lang.String getCatagory(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Catagory.toString());
	}

	/**
	 * Set value of Catagory
	 * @param catagory
	 */
	public final void setCatagory(java.lang.String catagory)
	{
		setCatagory(getContext(), catagory);
	}

	/**
	 * Set value of Catagory
	 * @param context
	 * @param catagory
	 */
	public final void setCatagory(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String catagory)
	{
		getMendixObject().setValue(context, MemberNames.Catagory.toString(), catagory);
	}

	/**
	 * @return value of Major
	 */
	public final java.lang.String getMajor()
	{
		return getMajor(getContext());
	}

	/**
	 * @param context
	 * @return value of Major
	 */
	public final java.lang.String getMajor(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Major.toString());
	}

	/**
	 * Set value of Major
	 * @param major
	 */
	public final void setMajor(java.lang.String major)
	{
		setMajor(getContext(), major);
	}

	/**
	 * Set value of Major
	 * @param context
	 * @param major
	 */
	public final void setMajor(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String major)
	{
		getMendixObject().setValue(context, MemberNames.Major.toString(), major);
	}

	/**
	 * @return value of Profession
	 */
	public final java.lang.String getProfession()
	{
		return getProfession(getContext());
	}

	/**
	 * @param context
	 * @return value of Profession
	 */
	public final java.lang.String getProfession(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Profession.toString());
	}

	/**
	 * Set value of Profession
	 * @param profession
	 */
	public final void setProfession(java.lang.String profession)
	{
		setProfession(getContext(), profession);
	}

	/**
	 * Set value of Profession
	 * @param context
	 * @param profession
	 */
	public final void setProfession(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String profession)
	{
		getMendixObject().setValue(context, MemberNames.Profession.toString(), profession);
	}

	/**
	 * @return value of MinimumNoOfStaffs
	 */
	public final java.lang.Integer getMinimumNoOfStaffs()
	{
		return getMinimumNoOfStaffs(getContext());
	}

	/**
	 * @param context
	 * @return value of MinimumNoOfStaffs
	 */
	public final java.lang.Integer getMinimumNoOfStaffs(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.MinimumNoOfStaffs.toString());
	}

	/**
	 * Set value of MinimumNoOfStaffs
	 * @param minimumnoofstaffs
	 */
	public final void setMinimumNoOfStaffs(java.lang.Integer minimumnoofstaffs)
	{
		setMinimumNoOfStaffs(getContext(), minimumnoofstaffs);
	}

	/**
	 * Set value of MinimumNoOfStaffs
	 * @param context
	 * @param minimumnoofstaffs
	 */
	public final void setMinimumNoOfStaffs(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer minimumnoofstaffs)
	{
		getMendixObject().setValue(context, MemberNames.MinimumNoOfStaffs.toString(), minimumnoofstaffs);
	}

	/**
	 * @return value of ProposedStaff
	 */
	public final java.lang.Integer getProposedStaff()
	{
		return getProposedStaff(getContext());
	}

	/**
	 * @param context
	 * @return value of ProposedStaff
	 */
	public final java.lang.Integer getProposedStaff(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ProposedStaff.toString());
	}

	/**
	 * Set value of ProposedStaff
	 * @param proposedstaff
	 */
	public final void setProposedStaff(java.lang.Integer proposedstaff)
	{
		setProposedStaff(getContext(), proposedstaff);
	}

	/**
	 * Set value of ProposedStaff
	 * @param context
	 * @param proposedstaff
	 */
	public final void setProposedStaff(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer proposedstaff)
	{
		getMendixObject().setValue(context, MemberNames.ProposedStaff.toString(), proposedstaff);
	}

	/**
	 * @return value of Medical_Vocation_Specialiti
	 */
	public final requestforpreliminaryregistrationofafacility_hospital.proxies.Specialiti getMedical_Vocation_Specialiti() throws com.mendix.core.CoreException
	{
		return getMedical_Vocation_Specialiti(getContext());
	}

	/**
	 * @param context
	 * @return value of Medical_Vocation_Specialiti
	 */
	public final requestforpreliminaryregistrationofafacility_hospital.proxies.Specialiti getMedical_Vocation_Specialiti(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		requestforpreliminaryregistrationofafacility_hospital.proxies.Specialiti result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Medical_Vocation_Specialiti.toString());
		if (identifier != null)
			result = requestforpreliminaryregistrationofafacility_hospital.proxies.Specialiti.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Medical_Vocation_Specialiti
	 * @param medical_vocation_specialiti
	 */
	public final void setMedical_Vocation_Specialiti(requestforpreliminaryregistrationofafacility_hospital.proxies.Specialiti medical_vocation_specialiti)
	{
		setMedical_Vocation_Specialiti(getContext(), medical_vocation_specialiti);
	}

	/**
	 * Set value of Medical_Vocation_Specialiti
	 * @param context
	 * @param medical_vocation_specialiti
	 */
	public final void setMedical_Vocation_Specialiti(com.mendix.systemwideinterfaces.core.IContext context, requestforpreliminaryregistrationofafacility_hospital.proxies.Specialiti medical_vocation_specialiti)
	{
		if (medical_vocation_specialiti == null)
			getMendixObject().setValue(context, MemberNames.Medical_Vocation_Specialiti.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Medical_Vocation_Specialiti.toString(), medical_vocation_specialiti.getMendixObject().getId());
	}

	/**
	 * @return value of Medical_Vocation_Servies
	 */
	public final requestforpreliminaryregistrationofafacility_hospital.proxies.Servies getMedical_Vocation_Servies() throws com.mendix.core.CoreException
	{
		return getMedical_Vocation_Servies(getContext());
	}

	/**
	 * @param context
	 * @return value of Medical_Vocation_Servies
	 */
	public final requestforpreliminaryregistrationofafacility_hospital.proxies.Servies getMedical_Vocation_Servies(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		requestforpreliminaryregistrationofafacility_hospital.proxies.Servies result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Medical_Vocation_Servies.toString());
		if (identifier != null)
			result = requestforpreliminaryregistrationofafacility_hospital.proxies.Servies.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Medical_Vocation_Servies
	 * @param medical_vocation_servies
	 */
	public final void setMedical_Vocation_Servies(requestforpreliminaryregistrationofafacility_hospital.proxies.Servies medical_vocation_servies)
	{
		setMedical_Vocation_Servies(getContext(), medical_vocation_servies);
	}

	/**
	 * Set value of Medical_Vocation_Servies
	 * @param context
	 * @param medical_vocation_servies
	 */
	public final void setMedical_Vocation_Servies(com.mendix.systemwideinterfaces.core.IContext context, requestforpreliminaryregistrationofafacility_hospital.proxies.Servies medical_vocation_servies)
	{
		if (medical_vocation_servies == null)
			getMendixObject().setValue(context, MemberNames.Medical_Vocation_Servies.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Medical_Vocation_Servies.toString(), medical_vocation_servies.getMendixObject().getId());
	}

	/**
	 * @return value of Medical_Vocation_Preliminary
	 */
	public final requestforpreliminaryregistrationofafacility_hospital.proxies.Preliminary getMedical_Vocation_Preliminary() throws com.mendix.core.CoreException
	{
		return getMedical_Vocation_Preliminary(getContext());
	}

	/**
	 * @param context
	 * @return value of Medical_Vocation_Preliminary
	 */
	public final requestforpreliminaryregistrationofafacility_hospital.proxies.Preliminary getMedical_Vocation_Preliminary(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		requestforpreliminaryregistrationofafacility_hospital.proxies.Preliminary result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Medical_Vocation_Preliminary.toString());
		if (identifier != null)
			result = requestforpreliminaryregistrationofafacility_hospital.proxies.Preliminary.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Medical_Vocation_Preliminary
	 * @param medical_vocation_preliminary
	 */
	public final void setMedical_Vocation_Preliminary(requestforpreliminaryregistrationofafacility_hospital.proxies.Preliminary medical_vocation_preliminary)
	{
		setMedical_Vocation_Preliminary(getContext(), medical_vocation_preliminary);
	}

	/**
	 * Set value of Medical_Vocation_Preliminary
	 * @param context
	 * @param medical_vocation_preliminary
	 */
	public final void setMedical_Vocation_Preliminary(com.mendix.systemwideinterfaces.core.IContext context, requestforpreliminaryregistrationofafacility_hospital.proxies.Preliminary medical_vocation_preliminary)
	{
		if (medical_vocation_preliminary == null)
			getMendixObject().setValue(context, MemberNames.Medical_Vocation_Preliminary.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Medical_Vocation_Preliminary.toString(), medical_vocation_preliminary.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return medical_VocationMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final requestforpreliminaryregistrationofafacility_hospital.proxies.Medical_Vocation that = (requestforpreliminaryregistrationofafacility_hospital.proxies.Medical_Vocation) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "RequestforPreliminaryRegistrationofaFacility_Hospital.Medical_Vocation";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
