// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package requestforpreliminaryregistrationofafacility_hospital.proxies;

public class Payment
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject paymentMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "RequestforPreliminaryRegistrationofaFacility_Hospital.Payment";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		EstimatedValueinAED("EstimatedValueinAED"),
		ApplicationFees("ApplicationFees");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Payment(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "RequestforPreliminaryRegistrationofaFacility_Hospital.Payment"));
	}

	protected Payment(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject paymentMendixObject)
	{
		if (paymentMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("RequestforPreliminaryRegistrationofaFacility_Hospital.Payment", paymentMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a RequestforPreliminaryRegistrationofaFacility_Hospital.Payment");

		this.paymentMendixObject = paymentMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Payment.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static requestforpreliminaryregistrationofafacility_hospital.proxies.Payment initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return requestforpreliminaryregistrationofafacility_hospital.proxies.Payment.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static requestforpreliminaryregistrationofafacility_hospital.proxies.Payment initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new requestforpreliminaryregistrationofafacility_hospital.proxies.Payment(context, mendixObject);
	}

	public static requestforpreliminaryregistrationofafacility_hospital.proxies.Payment load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return requestforpreliminaryregistrationofafacility_hospital.proxies.Payment.initialize(context, mendixObject);
	}

	public static java.util.List<requestforpreliminaryregistrationofafacility_hospital.proxies.Payment> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<requestforpreliminaryregistrationofafacility_hospital.proxies.Payment> result = new java.util.ArrayList<requestforpreliminaryregistrationofafacility_hospital.proxies.Payment>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//RequestforPreliminaryRegistrationofaFacility_Hospital.Payment" + xpathConstraint))
			result.add(requestforpreliminaryregistrationofafacility_hospital.proxies.Payment.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of EstimatedValueinAED
	 */
	public final java.lang.Integer getEstimatedValueinAED()
	{
		return getEstimatedValueinAED(getContext());
	}

	/**
	 * @param context
	 * @return value of EstimatedValueinAED
	 */
	public final java.lang.Integer getEstimatedValueinAED(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.EstimatedValueinAED.toString());
	}

	/**
	 * Set value of EstimatedValueinAED
	 * @param estimatedvalueinaed
	 */
	public final void setEstimatedValueinAED(java.lang.Integer estimatedvalueinaed)
	{
		setEstimatedValueinAED(getContext(), estimatedvalueinaed);
	}

	/**
	 * Set value of EstimatedValueinAED
	 * @param context
	 * @param estimatedvalueinaed
	 */
	public final void setEstimatedValueinAED(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer estimatedvalueinaed)
	{
		getMendixObject().setValue(context, MemberNames.EstimatedValueinAED.toString(), estimatedvalueinaed);
	}

	/**
	 * @return value of ApplicationFees
	 */
	public final java.lang.Integer getApplicationFees()
	{
		return getApplicationFees(getContext());
	}

	/**
	 * @param context
	 * @return value of ApplicationFees
	 */
	public final java.lang.Integer getApplicationFees(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ApplicationFees.toString());
	}

	/**
	 * Set value of ApplicationFees
	 * @param applicationfees
	 */
	public final void setApplicationFees(java.lang.Integer applicationfees)
	{
		setApplicationFees(getContext(), applicationfees);
	}

	/**
	 * Set value of ApplicationFees
	 * @param context
	 * @param applicationfees
	 */
	public final void setApplicationFees(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer applicationfees)
	{
		getMendixObject().setValue(context, MemberNames.ApplicationFees.toString(), applicationfees);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return paymentMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final requestforpreliminaryregistrationofafacility_hospital.proxies.Payment that = (requestforpreliminaryregistrationofafacility_hospital.proxies.Payment) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "RequestforPreliminaryRegistrationofaFacility_Hospital.Payment";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
