// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package requestforpreliminaryregistrationofafacility_hospital.proxies;

public class PharmaService
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject pharmaServiceMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "RequestforPreliminaryRegistrationofaFacility_Hospital.PharmaService";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		WorkingHours("WorkingHours"),
		HourService24("HourService24"),
		Requirement1("Requirement1"),
		Requirement2("Requirement2"),
		Requirement3("Requirement3"),
		R1Reason("R1Reason"),
		R2Reason("R2Reason"),
		R3Reason("R3Reason"),
		Preliminary_PharmaService("RequestforPreliminaryRegistrationofaFacility_Hospital.Preliminary_PharmaService");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public PharmaService(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "RequestforPreliminaryRegistrationofaFacility_Hospital.PharmaService"));
	}

	protected PharmaService(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject pharmaServiceMendixObject)
	{
		if (pharmaServiceMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("RequestforPreliminaryRegistrationofaFacility_Hospital.PharmaService", pharmaServiceMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a RequestforPreliminaryRegistrationofaFacility_Hospital.PharmaService");

		this.pharmaServiceMendixObject = pharmaServiceMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'PharmaService.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static requestforpreliminaryregistrationofafacility_hospital.proxies.PharmaService initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return requestforpreliminaryregistrationofafacility_hospital.proxies.PharmaService.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static requestforpreliminaryregistrationofafacility_hospital.proxies.PharmaService initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new requestforpreliminaryregistrationofafacility_hospital.proxies.PharmaService(context, mendixObject);
	}

	public static requestforpreliminaryregistrationofafacility_hospital.proxies.PharmaService load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return requestforpreliminaryregistrationofafacility_hospital.proxies.PharmaService.initialize(context, mendixObject);
	}

	public static java.util.List<requestforpreliminaryregistrationofafacility_hospital.proxies.PharmaService> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<requestforpreliminaryregistrationofafacility_hospital.proxies.PharmaService> result = new java.util.ArrayList<requestforpreliminaryregistrationofafacility_hospital.proxies.PharmaService>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//RequestforPreliminaryRegistrationofaFacility_Hospital.PharmaService" + xpathConstraint))
			result.add(requestforpreliminaryregistrationofafacility_hospital.proxies.PharmaService.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * Set value of WorkingHours
	 * @param workinghours
	 */
	public final requestforpreliminaryregistrationofafacility_hospital.proxies.EnumWorkingHours getWorkingHours()
	{
		return getWorkingHours(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkingHours
	 */
	public final requestforpreliminaryregistrationofafacility_hospital.proxies.EnumWorkingHours getWorkingHours(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.WorkingHours.toString());
		if (obj == null)
			return null;

		return requestforpreliminaryregistrationofafacility_hospital.proxies.EnumWorkingHours.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of WorkingHours
	 * @param workinghours
	 */
	public final void setWorkingHours(requestforpreliminaryregistrationofafacility_hospital.proxies.EnumWorkingHours workinghours)
	{
		setWorkingHours(getContext(), workinghours);
	}

	/**
	 * Set value of WorkingHours
	 * @param context
	 * @param workinghours
	 */
	public final void setWorkingHours(com.mendix.systemwideinterfaces.core.IContext context, requestforpreliminaryregistrationofafacility_hospital.proxies.EnumWorkingHours workinghours)
	{
		if (workinghours != null)
			getMendixObject().setValue(context, MemberNames.WorkingHours.toString(), workinghours.toString());
		else
			getMendixObject().setValue(context, MemberNames.WorkingHours.toString(), null);
	}

	/**
	 * @return value of HourService24
	 */
	public final java.lang.Boolean getHourService24()
	{
		return getHourService24(getContext());
	}

	/**
	 * @param context
	 * @return value of HourService24
	 */
	public final java.lang.Boolean getHourService24(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.HourService24.toString());
	}

	/**
	 * Set value of HourService24
	 * @param hourservice24
	 */
	public final void setHourService24(java.lang.Boolean hourservice24)
	{
		setHourService24(getContext(), hourservice24);
	}

	/**
	 * Set value of HourService24
	 * @param context
	 * @param hourservice24
	 */
	public final void setHourService24(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean hourservice24)
	{
		getMendixObject().setValue(context, MemberNames.HourService24.toString(), hourservice24);
	}

	/**
	 * @return value of Requirement1
	 */
	public final java.lang.Boolean getRequirement1()
	{
		return getRequirement1(getContext());
	}

	/**
	 * @param context
	 * @return value of Requirement1
	 */
	public final java.lang.Boolean getRequirement1(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Requirement1.toString());
	}

	/**
	 * Set value of Requirement1
	 * @param requirement1
	 */
	public final void setRequirement1(java.lang.Boolean requirement1)
	{
		setRequirement1(getContext(), requirement1);
	}

	/**
	 * Set value of Requirement1
	 * @param context
	 * @param requirement1
	 */
	public final void setRequirement1(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean requirement1)
	{
		getMendixObject().setValue(context, MemberNames.Requirement1.toString(), requirement1);
	}

	/**
	 * @return value of Requirement2
	 */
	public final java.lang.Boolean getRequirement2()
	{
		return getRequirement2(getContext());
	}

	/**
	 * @param context
	 * @return value of Requirement2
	 */
	public final java.lang.Boolean getRequirement2(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Requirement2.toString());
	}

	/**
	 * Set value of Requirement2
	 * @param requirement2
	 */
	public final void setRequirement2(java.lang.Boolean requirement2)
	{
		setRequirement2(getContext(), requirement2);
	}

	/**
	 * Set value of Requirement2
	 * @param context
	 * @param requirement2
	 */
	public final void setRequirement2(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean requirement2)
	{
		getMendixObject().setValue(context, MemberNames.Requirement2.toString(), requirement2);
	}

	/**
	 * @return value of Requirement3
	 */
	public final java.lang.Boolean getRequirement3()
	{
		return getRequirement3(getContext());
	}

	/**
	 * @param context
	 * @return value of Requirement3
	 */
	public final java.lang.Boolean getRequirement3(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Requirement3.toString());
	}

	/**
	 * Set value of Requirement3
	 * @param requirement3
	 */
	public final void setRequirement3(java.lang.Boolean requirement3)
	{
		setRequirement3(getContext(), requirement3);
	}

	/**
	 * Set value of Requirement3
	 * @param context
	 * @param requirement3
	 */
	public final void setRequirement3(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean requirement3)
	{
		getMendixObject().setValue(context, MemberNames.Requirement3.toString(), requirement3);
	}

	/**
	 * @return value of R1Reason
	 */
	public final java.lang.String getR1Reason()
	{
		return getR1Reason(getContext());
	}

	/**
	 * @param context
	 * @return value of R1Reason
	 */
	public final java.lang.String getR1Reason(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.R1Reason.toString());
	}

	/**
	 * Set value of R1Reason
	 * @param r1reason
	 */
	public final void setR1Reason(java.lang.String r1reason)
	{
		setR1Reason(getContext(), r1reason);
	}

	/**
	 * Set value of R1Reason
	 * @param context
	 * @param r1reason
	 */
	public final void setR1Reason(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String r1reason)
	{
		getMendixObject().setValue(context, MemberNames.R1Reason.toString(), r1reason);
	}

	/**
	 * @return value of R2Reason
	 */
	public final java.lang.String getR2Reason()
	{
		return getR2Reason(getContext());
	}

	/**
	 * @param context
	 * @return value of R2Reason
	 */
	public final java.lang.String getR2Reason(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.R2Reason.toString());
	}

	/**
	 * Set value of R2Reason
	 * @param r2reason
	 */
	public final void setR2Reason(java.lang.String r2reason)
	{
		setR2Reason(getContext(), r2reason);
	}

	/**
	 * Set value of R2Reason
	 * @param context
	 * @param r2reason
	 */
	public final void setR2Reason(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String r2reason)
	{
		getMendixObject().setValue(context, MemberNames.R2Reason.toString(), r2reason);
	}

	/**
	 * @return value of R3Reason
	 */
	public final java.lang.String getR3Reason()
	{
		return getR3Reason(getContext());
	}

	/**
	 * @param context
	 * @return value of R3Reason
	 */
	public final java.lang.String getR3Reason(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.R3Reason.toString());
	}

	/**
	 * Set value of R3Reason
	 * @param r3reason
	 */
	public final void setR3Reason(java.lang.String r3reason)
	{
		setR3Reason(getContext(), r3reason);
	}

	/**
	 * Set value of R3Reason
	 * @param context
	 * @param r3reason
	 */
	public final void setR3Reason(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String r3reason)
	{
		getMendixObject().setValue(context, MemberNames.R3Reason.toString(), r3reason);
	}

	/**
	 * @return value of Preliminary_PharmaService
	 */
	public final requestforpreliminaryregistrationofafacility_hospital.proxies.Preliminary getPreliminary_PharmaService() throws com.mendix.core.CoreException
	{
		return getPreliminary_PharmaService(getContext());
	}

	/**
	 * @param context
	 * @return value of Preliminary_PharmaService
	 */
	public final requestforpreliminaryregistrationofafacility_hospital.proxies.Preliminary getPreliminary_PharmaService(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		requestforpreliminaryregistrationofafacility_hospital.proxies.Preliminary result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Preliminary_PharmaService.toString());
		if (identifier != null)
			result = requestforpreliminaryregistrationofafacility_hospital.proxies.Preliminary.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Preliminary_PharmaService
	 * @param preliminary_pharmaservice
	 */
	public final void setPreliminary_PharmaService(requestforpreliminaryregistrationofafacility_hospital.proxies.Preliminary preliminary_pharmaservice)
	{
		setPreliminary_PharmaService(getContext(), preliminary_pharmaservice);
	}

	/**
	 * Set value of Preliminary_PharmaService
	 * @param context
	 * @param preliminary_pharmaservice
	 */
	public final void setPreliminary_PharmaService(com.mendix.systemwideinterfaces.core.IContext context, requestforpreliminaryregistrationofafacility_hospital.proxies.Preliminary preliminary_pharmaservice)
	{
		if (preliminary_pharmaservice == null)
			getMendixObject().setValue(context, MemberNames.Preliminary_PharmaService.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Preliminary_PharmaService.toString(), preliminary_pharmaservice.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return pharmaServiceMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final requestforpreliminaryregistrationofafacility_hospital.proxies.PharmaService that = (requestforpreliminaryregistrationofafacility_hospital.proxies.PharmaService) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "RequestforPreliminaryRegistrationofaFacility_Hospital.PharmaService";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
