// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package requestforpreliminaryregistrationofafacility_hospital.proxies;

public class Prelim_Specialist
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject prelim_SpecialistMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "RequestforPreliminaryRegistrationofaFacility_Hospital.Prelim_Specialist";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		No_of_Staffs("No_of_Staffs"),
		Prelim_Specialist_Specialiti("RequestforPreliminaryRegistrationofaFacility_Hospital.Prelim_Specialist_Specialiti"),
		Prelim_Specialist_SubSpecality("RequestforPreliminaryRegistrationofaFacility_Hospital.Prelim_Specialist_SubSpecality"),
		Prelim_Specialist_Preliminary("RequestforPreliminaryRegistrationofaFacility_Hospital.Prelim_Specialist_Preliminary");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Prelim_Specialist(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "RequestforPreliminaryRegistrationofaFacility_Hospital.Prelim_Specialist"));
	}

	protected Prelim_Specialist(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject prelim_SpecialistMendixObject)
	{
		if (prelim_SpecialistMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("RequestforPreliminaryRegistrationofaFacility_Hospital.Prelim_Specialist", prelim_SpecialistMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a RequestforPreliminaryRegistrationofaFacility_Hospital.Prelim_Specialist");

		this.prelim_SpecialistMendixObject = prelim_SpecialistMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Prelim_Specialist.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static requestforpreliminaryregistrationofafacility_hospital.proxies.Prelim_Specialist initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return requestforpreliminaryregistrationofafacility_hospital.proxies.Prelim_Specialist.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static requestforpreliminaryregistrationofafacility_hospital.proxies.Prelim_Specialist initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new requestforpreliminaryregistrationofafacility_hospital.proxies.Prelim_Specialist(context, mendixObject);
	}

	public static requestforpreliminaryregistrationofafacility_hospital.proxies.Prelim_Specialist load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return requestforpreliminaryregistrationofafacility_hospital.proxies.Prelim_Specialist.initialize(context, mendixObject);
	}

	public static java.util.List<requestforpreliminaryregistrationofafacility_hospital.proxies.Prelim_Specialist> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<requestforpreliminaryregistrationofafacility_hospital.proxies.Prelim_Specialist> result = new java.util.ArrayList<requestforpreliminaryregistrationofafacility_hospital.proxies.Prelim_Specialist>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//RequestforPreliminaryRegistrationofaFacility_Hospital.Prelim_Specialist" + xpathConstraint))
			result.add(requestforpreliminaryregistrationofafacility_hospital.proxies.Prelim_Specialist.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of No_of_Staffs
	 */
	public final java.lang.Integer getNo_of_Staffs()
	{
		return getNo_of_Staffs(getContext());
	}

	/**
	 * @param context
	 * @return value of No_of_Staffs
	 */
	public final java.lang.Integer getNo_of_Staffs(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.No_of_Staffs.toString());
	}

	/**
	 * Set value of No_of_Staffs
	 * @param no_of_staffs
	 */
	public final void setNo_of_Staffs(java.lang.Integer no_of_staffs)
	{
		setNo_of_Staffs(getContext(), no_of_staffs);
	}

	/**
	 * Set value of No_of_Staffs
	 * @param context
	 * @param no_of_staffs
	 */
	public final void setNo_of_Staffs(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer no_of_staffs)
	{
		getMendixObject().setValue(context, MemberNames.No_of_Staffs.toString(), no_of_staffs);
	}

	/**
	 * @return value of Prelim_Specialist_Specialiti
	 */
	public final requestforpreliminaryregistrationofafacility_hospital.proxies.Specialiti getPrelim_Specialist_Specialiti() throws com.mendix.core.CoreException
	{
		return getPrelim_Specialist_Specialiti(getContext());
	}

	/**
	 * @param context
	 * @return value of Prelim_Specialist_Specialiti
	 */
	public final requestforpreliminaryregistrationofafacility_hospital.proxies.Specialiti getPrelim_Specialist_Specialiti(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		requestforpreliminaryregistrationofafacility_hospital.proxies.Specialiti result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Prelim_Specialist_Specialiti.toString());
		if (identifier != null)
			result = requestforpreliminaryregistrationofafacility_hospital.proxies.Specialiti.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Prelim_Specialist_Specialiti
	 * @param prelim_specialist_specialiti
	 */
	public final void setPrelim_Specialist_Specialiti(requestforpreliminaryregistrationofafacility_hospital.proxies.Specialiti prelim_specialist_specialiti)
	{
		setPrelim_Specialist_Specialiti(getContext(), prelim_specialist_specialiti);
	}

	/**
	 * Set value of Prelim_Specialist_Specialiti
	 * @param context
	 * @param prelim_specialist_specialiti
	 */
	public final void setPrelim_Specialist_Specialiti(com.mendix.systemwideinterfaces.core.IContext context, requestforpreliminaryregistrationofafacility_hospital.proxies.Specialiti prelim_specialist_specialiti)
	{
		if (prelim_specialist_specialiti == null)
			getMendixObject().setValue(context, MemberNames.Prelim_Specialist_Specialiti.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Prelim_Specialist_Specialiti.toString(), prelim_specialist_specialiti.getMendixObject().getId());
	}

	/**
	 * @return value of Prelim_Specialist_SubSpecality
	 */
	public final requestforpreliminaryregistrationofafacility_hospital.proxies.SubSpecality getPrelim_Specialist_SubSpecality() throws com.mendix.core.CoreException
	{
		return getPrelim_Specialist_SubSpecality(getContext());
	}

	/**
	 * @param context
	 * @return value of Prelim_Specialist_SubSpecality
	 */
	public final requestforpreliminaryregistrationofafacility_hospital.proxies.SubSpecality getPrelim_Specialist_SubSpecality(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		requestforpreliminaryregistrationofafacility_hospital.proxies.SubSpecality result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Prelim_Specialist_SubSpecality.toString());
		if (identifier != null)
			result = requestforpreliminaryregistrationofafacility_hospital.proxies.SubSpecality.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Prelim_Specialist_SubSpecality
	 * @param prelim_specialist_subspecality
	 */
	public final void setPrelim_Specialist_SubSpecality(requestforpreliminaryregistrationofafacility_hospital.proxies.SubSpecality prelim_specialist_subspecality)
	{
		setPrelim_Specialist_SubSpecality(getContext(), prelim_specialist_subspecality);
	}

	/**
	 * Set value of Prelim_Specialist_SubSpecality
	 * @param context
	 * @param prelim_specialist_subspecality
	 */
	public final void setPrelim_Specialist_SubSpecality(com.mendix.systemwideinterfaces.core.IContext context, requestforpreliminaryregistrationofafacility_hospital.proxies.SubSpecality prelim_specialist_subspecality)
	{
		if (prelim_specialist_subspecality == null)
			getMendixObject().setValue(context, MemberNames.Prelim_Specialist_SubSpecality.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Prelim_Specialist_SubSpecality.toString(), prelim_specialist_subspecality.getMendixObject().getId());
	}

	/**
	 * @return value of Prelim_Specialist_Preliminary
	 */
	public final requestforpreliminaryregistrationofafacility_hospital.proxies.Preliminary getPrelim_Specialist_Preliminary() throws com.mendix.core.CoreException
	{
		return getPrelim_Specialist_Preliminary(getContext());
	}

	/**
	 * @param context
	 * @return value of Prelim_Specialist_Preliminary
	 */
	public final requestforpreliminaryregistrationofafacility_hospital.proxies.Preliminary getPrelim_Specialist_Preliminary(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		requestforpreliminaryregistrationofafacility_hospital.proxies.Preliminary result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Prelim_Specialist_Preliminary.toString());
		if (identifier != null)
			result = requestforpreliminaryregistrationofafacility_hospital.proxies.Preliminary.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Prelim_Specialist_Preliminary
	 * @param prelim_specialist_preliminary
	 */
	public final void setPrelim_Specialist_Preliminary(requestforpreliminaryregistrationofafacility_hospital.proxies.Preliminary prelim_specialist_preliminary)
	{
		setPrelim_Specialist_Preliminary(getContext(), prelim_specialist_preliminary);
	}

	/**
	 * Set value of Prelim_Specialist_Preliminary
	 * @param context
	 * @param prelim_specialist_preliminary
	 */
	public final void setPrelim_Specialist_Preliminary(com.mendix.systemwideinterfaces.core.IContext context, requestforpreliminaryregistrationofafacility_hospital.proxies.Preliminary prelim_specialist_preliminary)
	{
		if (prelim_specialist_preliminary == null)
			getMendixObject().setValue(context, MemberNames.Prelim_Specialist_Preliminary.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Prelim_Specialist_Preliminary.toString(), prelim_specialist_preliminary.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return prelim_SpecialistMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final requestforpreliminaryregistrationofafacility_hospital.proxies.Prelim_Specialist that = (requestforpreliminaryregistrationofafacility_hospital.proxies.Prelim_Specialist) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "RequestforPreliminaryRegistrationofaFacility_Hospital.Prelim_Specialist";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
