// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package requestforpreliminaryregistrationofafacility_hospital.proxies;

public class Preliminary
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject preliminaryMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "RequestforPreliminaryRegistrationofaFacility_Hospital.Preliminary";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		DEDLicenseNumber("DEDLicenseNumber"),
		FacilityCategory("FacilityCategory"),
		FacilityType("FacilityType"),
		PublicFacility("PublicFacility"),
		FacilitySubType("FacilitySubType"),
		HaveCommercialDEDLicense("HaveCommercialDEDLicense"),
		FacilityName_En("FacilityName_En"),
		FacilityName_Ar("FacilityName_Ar"),
		DEDLicenseExpirationDate("DEDLicenseExpirationDate"),
		Region("Region"),
		City("City"),
		Address_En("Address_En"),
		Address_Ar("Address_Ar"),
		Latitude("Latitude"),
		Longitude("Longitude"),
		BuildingType("BuildingType"),
		BuildingConstructionType("BuildingConstructionType"),
		Fax("Fax"),
		POBox("POBox"),
		EmailAddress("EmailAddress"),
		Telephone("Telephone"),
		ExpectedStartDate("ExpectedStartDate"),
		ExpectedCompletedDate("ExpectedCompletedDate"),
		ExpectedCompletionYears("ExpectedCompletionYears"),
		ExpectedCompletionMonths("ExpectedCompletionMonths"),
		ApplicationReferrenceNo("ApplicationReferrenceNo"),
		SelfPay("SelfPay"),
		TradeNumber("TradeNumber"),
		Estimated_Value("Estimated_Value"),
		Status("Status"),
		WorkingHours("WorkingHours"),
		Preliminary_NewOwner("RequestforPreliminaryRegistrationofaFacility_Hospital.Preliminary_NewOwner"),
		Preliminary_PharmaService("RequestforPreliminaryRegistrationofaFacility_Hospital.Preliminary_PharmaService"),
		Servies_Preliminary("RequestforPreliminaryRegistrationofaFacility_Hospital.Servies_Preliminary"),
		School_clinic_details_Preliminary("RequestforPreliminaryRegistrationofaFacility_Hospital.School_clinic_details_Preliminary"),
		Preliminary_FacilityType("RequestforPreliminaryRegistrationofaFacility_Hospital.Preliminary_FacilityType"),
		Preliminary_FacilitySubtype("RequestforPreliminaryRegistrationofaFacility_Hospital.Preliminary_FacilitySubtype"),
		RehabilitationSubtypes_Preliminary("RequestforPreliminaryRegistrationofaFacility_Hospital.RehabilitationSubtypes_Preliminary"),
		HospitalDetails_Preliminary("RequestforPreliminaryRegistrationofaFacility_Hospital.HospitalDetails_Preliminary"),
		Preliminary_Diagonist_Servies("RequestforPreliminaryRegistrationofaFacility_Hospital.Preliminary_Diagonist_Servies"),
		Preliminary_Account("RequestforPreliminaryRegistrationofaFacility_Hospital.Preliminary_Account");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Preliminary(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "RequestforPreliminaryRegistrationofaFacility_Hospital.Preliminary"));
	}

	protected Preliminary(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject preliminaryMendixObject)
	{
		if (preliminaryMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("RequestforPreliminaryRegistrationofaFacility_Hospital.Preliminary", preliminaryMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a RequestforPreliminaryRegistrationofaFacility_Hospital.Preliminary");

		this.preliminaryMendixObject = preliminaryMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Preliminary.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static requestforpreliminaryregistrationofafacility_hospital.proxies.Preliminary initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return requestforpreliminaryregistrationofafacility_hospital.proxies.Preliminary.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static requestforpreliminaryregistrationofafacility_hospital.proxies.Preliminary initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new requestforpreliminaryregistrationofafacility_hospital.proxies.Preliminary(context, mendixObject);
	}

	public static requestforpreliminaryregistrationofafacility_hospital.proxies.Preliminary load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return requestforpreliminaryregistrationofafacility_hospital.proxies.Preliminary.initialize(context, mendixObject);
	}

	public static java.util.List<requestforpreliminaryregistrationofafacility_hospital.proxies.Preliminary> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<requestforpreliminaryregistrationofafacility_hospital.proxies.Preliminary> result = new java.util.ArrayList<requestforpreliminaryregistrationofafacility_hospital.proxies.Preliminary>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//RequestforPreliminaryRegistrationofaFacility_Hospital.Preliminary" + xpathConstraint))
			result.add(requestforpreliminaryregistrationofafacility_hospital.proxies.Preliminary.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of DEDLicenseNumber
	 */
	public final java.lang.String getDEDLicenseNumber()
	{
		return getDEDLicenseNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of DEDLicenseNumber
	 */
	public final java.lang.String getDEDLicenseNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DEDLicenseNumber.toString());
	}

	/**
	 * Set value of DEDLicenseNumber
	 * @param dedlicensenumber
	 */
	public final void setDEDLicenseNumber(java.lang.String dedlicensenumber)
	{
		setDEDLicenseNumber(getContext(), dedlicensenumber);
	}

	/**
	 * Set value of DEDLicenseNumber
	 * @param context
	 * @param dedlicensenumber
	 */
	public final void setDEDLicenseNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String dedlicensenumber)
	{
		getMendixObject().setValue(context, MemberNames.DEDLicenseNumber.toString(), dedlicensenumber);
	}

	/**
	 * Set value of FacilityCategory
	 * @param facilitycategory
	 */
	public final requestforpreliminaryregistrationofafacility_hospital.proxies.ENUM_FacilityCategory getFacilityCategory()
	{
		return getFacilityCategory(getContext());
	}

	/**
	 * @param context
	 * @return value of FacilityCategory
	 */
	public final requestforpreliminaryregistrationofafacility_hospital.proxies.ENUM_FacilityCategory getFacilityCategory(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.FacilityCategory.toString());
		if (obj == null)
			return null;

		return requestforpreliminaryregistrationofafacility_hospital.proxies.ENUM_FacilityCategory.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of FacilityCategory
	 * @param facilitycategory
	 */
	public final void setFacilityCategory(requestforpreliminaryregistrationofafacility_hospital.proxies.ENUM_FacilityCategory facilitycategory)
	{
		setFacilityCategory(getContext(), facilitycategory);
	}

	/**
	 * Set value of FacilityCategory
	 * @param context
	 * @param facilitycategory
	 */
	public final void setFacilityCategory(com.mendix.systemwideinterfaces.core.IContext context, requestforpreliminaryregistrationofafacility_hospital.proxies.ENUM_FacilityCategory facilitycategory)
	{
		if (facilitycategory != null)
			getMendixObject().setValue(context, MemberNames.FacilityCategory.toString(), facilitycategory.toString());
		else
			getMendixObject().setValue(context, MemberNames.FacilityCategory.toString(), null);
	}

	/**
	 * Set value of FacilityType
	 * @param facilitytype
	 */
	public final requestforpreliminaryregistrationofafacility_hospital.proxies.ENUM_FacilityType getFacilityType()
	{
		return getFacilityType(getContext());
	}

	/**
	 * @param context
	 * @return value of FacilityType
	 */
	public final requestforpreliminaryregistrationofafacility_hospital.proxies.ENUM_FacilityType getFacilityType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.FacilityType.toString());
		if (obj == null)
			return null;

		return requestforpreliminaryregistrationofafacility_hospital.proxies.ENUM_FacilityType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of FacilityType
	 * @param facilitytype
	 */
	public final void setFacilityType(requestforpreliminaryregistrationofafacility_hospital.proxies.ENUM_FacilityType facilitytype)
	{
		setFacilityType(getContext(), facilitytype);
	}

	/**
	 * Set value of FacilityType
	 * @param context
	 * @param facilitytype
	 */
	public final void setFacilityType(com.mendix.systemwideinterfaces.core.IContext context, requestforpreliminaryregistrationofafacility_hospital.proxies.ENUM_FacilityType facilitytype)
	{
		if (facilitytype != null)
			getMendixObject().setValue(context, MemberNames.FacilityType.toString(), facilitytype.toString());
		else
			getMendixObject().setValue(context, MemberNames.FacilityType.toString(), null);
	}

	/**
	 * @return value of PublicFacility
	 */
	public final java.lang.Boolean getPublicFacility()
	{
		return getPublicFacility(getContext());
	}

	/**
	 * @param context
	 * @return value of PublicFacility
	 */
	public final java.lang.Boolean getPublicFacility(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.PublicFacility.toString());
	}

	/**
	 * Set value of PublicFacility
	 * @param publicfacility
	 */
	public final void setPublicFacility(java.lang.Boolean publicfacility)
	{
		setPublicFacility(getContext(), publicfacility);
	}

	/**
	 * Set value of PublicFacility
	 * @param context
	 * @param publicfacility
	 */
	public final void setPublicFacility(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean publicfacility)
	{
		getMendixObject().setValue(context, MemberNames.PublicFacility.toString(), publicfacility);
	}

	/**
	 * Set value of FacilitySubType
	 * @param facilitysubtype
	 */
	public final requestforpreliminaryregistrationofafacility_hospital.proxies.ENUM_FacilitySubType getFacilitySubType()
	{
		return getFacilitySubType(getContext());
	}

	/**
	 * @param context
	 * @return value of FacilitySubType
	 */
	public final requestforpreliminaryregistrationofafacility_hospital.proxies.ENUM_FacilitySubType getFacilitySubType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.FacilitySubType.toString());
		if (obj == null)
			return null;

		return requestforpreliminaryregistrationofafacility_hospital.proxies.ENUM_FacilitySubType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of FacilitySubType
	 * @param facilitysubtype
	 */
	public final void setFacilitySubType(requestforpreliminaryregistrationofafacility_hospital.proxies.ENUM_FacilitySubType facilitysubtype)
	{
		setFacilitySubType(getContext(), facilitysubtype);
	}

	/**
	 * Set value of FacilitySubType
	 * @param context
	 * @param facilitysubtype
	 */
	public final void setFacilitySubType(com.mendix.systemwideinterfaces.core.IContext context, requestforpreliminaryregistrationofafacility_hospital.proxies.ENUM_FacilitySubType facilitysubtype)
	{
		if (facilitysubtype != null)
			getMendixObject().setValue(context, MemberNames.FacilitySubType.toString(), facilitysubtype.toString());
		else
			getMendixObject().setValue(context, MemberNames.FacilitySubType.toString(), null);
	}

	/**
	 * @return value of HaveCommercialDEDLicense
	 */
	public final java.lang.Boolean getHaveCommercialDEDLicense()
	{
		return getHaveCommercialDEDLicense(getContext());
	}

	/**
	 * @param context
	 * @return value of HaveCommercialDEDLicense
	 */
	public final java.lang.Boolean getHaveCommercialDEDLicense(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.HaveCommercialDEDLicense.toString());
	}

	/**
	 * Set value of HaveCommercialDEDLicense
	 * @param havecommercialdedlicense
	 */
	public final void setHaveCommercialDEDLicense(java.lang.Boolean havecommercialdedlicense)
	{
		setHaveCommercialDEDLicense(getContext(), havecommercialdedlicense);
	}

	/**
	 * Set value of HaveCommercialDEDLicense
	 * @param context
	 * @param havecommercialdedlicense
	 */
	public final void setHaveCommercialDEDLicense(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean havecommercialdedlicense)
	{
		getMendixObject().setValue(context, MemberNames.HaveCommercialDEDLicense.toString(), havecommercialdedlicense);
	}

	/**
	 * @return value of FacilityName_En
	 */
	public final java.lang.String getFacilityName_En()
	{
		return getFacilityName_En(getContext());
	}

	/**
	 * @param context
	 * @return value of FacilityName_En
	 */
	public final java.lang.String getFacilityName_En(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FacilityName_En.toString());
	}

	/**
	 * Set value of FacilityName_En
	 * @param facilityname_en
	 */
	public final void setFacilityName_En(java.lang.String facilityname_en)
	{
		setFacilityName_En(getContext(), facilityname_en);
	}

	/**
	 * Set value of FacilityName_En
	 * @param context
	 * @param facilityname_en
	 */
	public final void setFacilityName_En(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String facilityname_en)
	{
		getMendixObject().setValue(context, MemberNames.FacilityName_En.toString(), facilityname_en);
	}

	/**
	 * @return value of FacilityName_Ar
	 */
	public final java.lang.String getFacilityName_Ar()
	{
		return getFacilityName_Ar(getContext());
	}

	/**
	 * @param context
	 * @return value of FacilityName_Ar
	 */
	public final java.lang.String getFacilityName_Ar(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FacilityName_Ar.toString());
	}

	/**
	 * Set value of FacilityName_Ar
	 * @param facilityname_ar
	 */
	public final void setFacilityName_Ar(java.lang.String facilityname_ar)
	{
		setFacilityName_Ar(getContext(), facilityname_ar);
	}

	/**
	 * Set value of FacilityName_Ar
	 * @param context
	 * @param facilityname_ar
	 */
	public final void setFacilityName_Ar(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String facilityname_ar)
	{
		getMendixObject().setValue(context, MemberNames.FacilityName_Ar.toString(), facilityname_ar);
	}

	/**
	 * @return value of DEDLicenseExpirationDate
	 */
	public final java.util.Date getDEDLicenseExpirationDate()
	{
		return getDEDLicenseExpirationDate(getContext());
	}

	/**
	 * @param context
	 * @return value of DEDLicenseExpirationDate
	 */
	public final java.util.Date getDEDLicenseExpirationDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DEDLicenseExpirationDate.toString());
	}

	/**
	 * Set value of DEDLicenseExpirationDate
	 * @param dedlicenseexpirationdate
	 */
	public final void setDEDLicenseExpirationDate(java.util.Date dedlicenseexpirationdate)
	{
		setDEDLicenseExpirationDate(getContext(), dedlicenseexpirationdate);
	}

	/**
	 * Set value of DEDLicenseExpirationDate
	 * @param context
	 * @param dedlicenseexpirationdate
	 */
	public final void setDEDLicenseExpirationDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date dedlicenseexpirationdate)
	{
		getMendixObject().setValue(context, MemberNames.DEDLicenseExpirationDate.toString(), dedlicenseexpirationdate);
	}

	/**
	 * @return value of Region
	 */
	public final java.lang.String getRegion()
	{
		return getRegion(getContext());
	}

	/**
	 * @param context
	 * @return value of Region
	 */
	public final java.lang.String getRegion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Region.toString());
	}

	/**
	 * Set value of Region
	 * @param region
	 */
	public final void setRegion(java.lang.String region)
	{
		setRegion(getContext(), region);
	}

	/**
	 * Set value of Region
	 * @param context
	 * @param region
	 */
	public final void setRegion(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String region)
	{
		getMendixObject().setValue(context, MemberNames.Region.toString(), region);
	}

	/**
	 * @return value of City
	 */
	public final java.lang.String getCity()
	{
		return getCity(getContext());
	}

	/**
	 * @param context
	 * @return value of City
	 */
	public final java.lang.String getCity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.City.toString());
	}

	/**
	 * Set value of City
	 * @param city
	 */
	public final void setCity(java.lang.String city)
	{
		setCity(getContext(), city);
	}

	/**
	 * Set value of City
	 * @param context
	 * @param city
	 */
	public final void setCity(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String city)
	{
		getMendixObject().setValue(context, MemberNames.City.toString(), city);
	}

	/**
	 * @return value of Address_En
	 */
	public final java.lang.String getAddress_En()
	{
		return getAddress_En(getContext());
	}

	/**
	 * @param context
	 * @return value of Address_En
	 */
	public final java.lang.String getAddress_En(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Address_En.toString());
	}

	/**
	 * Set value of Address_En
	 * @param address_en
	 */
	public final void setAddress_En(java.lang.String address_en)
	{
		setAddress_En(getContext(), address_en);
	}

	/**
	 * Set value of Address_En
	 * @param context
	 * @param address_en
	 */
	public final void setAddress_En(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String address_en)
	{
		getMendixObject().setValue(context, MemberNames.Address_En.toString(), address_en);
	}

	/**
	 * @return value of Address_Ar
	 */
	public final java.lang.String getAddress_Ar()
	{
		return getAddress_Ar(getContext());
	}

	/**
	 * @param context
	 * @return value of Address_Ar
	 */
	public final java.lang.String getAddress_Ar(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Address_Ar.toString());
	}

	/**
	 * Set value of Address_Ar
	 * @param address_ar
	 */
	public final void setAddress_Ar(java.lang.String address_ar)
	{
		setAddress_Ar(getContext(), address_ar);
	}

	/**
	 * Set value of Address_Ar
	 * @param context
	 * @param address_ar
	 */
	public final void setAddress_Ar(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String address_ar)
	{
		getMendixObject().setValue(context, MemberNames.Address_Ar.toString(), address_ar);
	}

	/**
	 * @return value of Latitude
	 */
	public final java.lang.Long getLatitude()
	{
		return getLatitude(getContext());
	}

	/**
	 * @param context
	 * @return value of Latitude
	 */
	public final java.lang.Long getLatitude(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.Latitude.toString());
	}

	/**
	 * Set value of Latitude
	 * @param latitude
	 */
	public final void setLatitude(java.lang.Long latitude)
	{
		setLatitude(getContext(), latitude);
	}

	/**
	 * Set value of Latitude
	 * @param context
	 * @param latitude
	 */
	public final void setLatitude(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long latitude)
	{
		getMendixObject().setValue(context, MemberNames.Latitude.toString(), latitude);
	}

	/**
	 * @return value of Longitude
	 */
	public final java.lang.Long getLongitude()
	{
		return getLongitude(getContext());
	}

	/**
	 * @param context
	 * @return value of Longitude
	 */
	public final java.lang.Long getLongitude(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.Longitude.toString());
	}

	/**
	 * Set value of Longitude
	 * @param longitude
	 */
	public final void setLongitude(java.lang.Long longitude)
	{
		setLongitude(getContext(), longitude);
	}

	/**
	 * Set value of Longitude
	 * @param context
	 * @param longitude
	 */
	public final void setLongitude(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long longitude)
	{
		getMendixObject().setValue(context, MemberNames.Longitude.toString(), longitude);
	}

	/**
	 * Set value of BuildingType
	 * @param buildingtype
	 */
	public final requestforpreliminaryregistrationofafacility_hospital.proxies.EnumBuildingType getBuildingType()
	{
		return getBuildingType(getContext());
	}

	/**
	 * @param context
	 * @return value of BuildingType
	 */
	public final requestforpreliminaryregistrationofafacility_hospital.proxies.EnumBuildingType getBuildingType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.BuildingType.toString());
		if (obj == null)
			return null;

		return requestforpreliminaryregistrationofafacility_hospital.proxies.EnumBuildingType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of BuildingType
	 * @param buildingtype
	 */
	public final void setBuildingType(requestforpreliminaryregistrationofafacility_hospital.proxies.EnumBuildingType buildingtype)
	{
		setBuildingType(getContext(), buildingtype);
	}

	/**
	 * Set value of BuildingType
	 * @param context
	 * @param buildingtype
	 */
	public final void setBuildingType(com.mendix.systemwideinterfaces.core.IContext context, requestforpreliminaryregistrationofafacility_hospital.proxies.EnumBuildingType buildingtype)
	{
		if (buildingtype != null)
			getMendixObject().setValue(context, MemberNames.BuildingType.toString(), buildingtype.toString());
		else
			getMendixObject().setValue(context, MemberNames.BuildingType.toString(), null);
	}

	/**
	 * Set value of BuildingConstructionType
	 * @param buildingconstructiontype
	 */
	public final requestforpreliminaryregistrationofafacility_hospital.proxies.EnumConstructionType getBuildingConstructionType()
	{
		return getBuildingConstructionType(getContext());
	}

	/**
	 * @param context
	 * @return value of BuildingConstructionType
	 */
	public final requestforpreliminaryregistrationofafacility_hospital.proxies.EnumConstructionType getBuildingConstructionType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.BuildingConstructionType.toString());
		if (obj == null)
			return null;

		return requestforpreliminaryregistrationofafacility_hospital.proxies.EnumConstructionType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of BuildingConstructionType
	 * @param buildingconstructiontype
	 */
	public final void setBuildingConstructionType(requestforpreliminaryregistrationofafacility_hospital.proxies.EnumConstructionType buildingconstructiontype)
	{
		setBuildingConstructionType(getContext(), buildingconstructiontype);
	}

	/**
	 * Set value of BuildingConstructionType
	 * @param context
	 * @param buildingconstructiontype
	 */
	public final void setBuildingConstructionType(com.mendix.systemwideinterfaces.core.IContext context, requestforpreliminaryregistrationofafacility_hospital.proxies.EnumConstructionType buildingconstructiontype)
	{
		if (buildingconstructiontype != null)
			getMendixObject().setValue(context, MemberNames.BuildingConstructionType.toString(), buildingconstructiontype.toString());
		else
			getMendixObject().setValue(context, MemberNames.BuildingConstructionType.toString(), null);
	}

	/**
	 * @return value of Fax
	 */
	public final java.lang.Long getFax()
	{
		return getFax(getContext());
	}

	/**
	 * @param context
	 * @return value of Fax
	 */
	public final java.lang.Long getFax(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.Fax.toString());
	}

	/**
	 * Set value of Fax
	 * @param fax
	 */
	public final void setFax(java.lang.Long fax)
	{
		setFax(getContext(), fax);
	}

	/**
	 * Set value of Fax
	 * @param context
	 * @param fax
	 */
	public final void setFax(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long fax)
	{
		getMendixObject().setValue(context, MemberNames.Fax.toString(), fax);
	}

	/**
	 * @return value of POBox
	 */
	public final java.lang.Integer getPOBox()
	{
		return getPOBox(getContext());
	}

	/**
	 * @param context
	 * @return value of POBox
	 */
	public final java.lang.Integer getPOBox(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.POBox.toString());
	}

	/**
	 * Set value of POBox
	 * @param pobox
	 */
	public final void setPOBox(java.lang.Integer pobox)
	{
		setPOBox(getContext(), pobox);
	}

	/**
	 * Set value of POBox
	 * @param context
	 * @param pobox
	 */
	public final void setPOBox(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer pobox)
	{
		getMendixObject().setValue(context, MemberNames.POBox.toString(), pobox);
	}

	/**
	 * @return value of EmailAddress
	 */
	public final java.lang.String getEmailAddress()
	{
		return getEmailAddress(getContext());
	}

	/**
	 * @param context
	 * @return value of EmailAddress
	 */
	public final java.lang.String getEmailAddress(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EmailAddress.toString());
	}

	/**
	 * Set value of EmailAddress
	 * @param emailaddress
	 */
	public final void setEmailAddress(java.lang.String emailaddress)
	{
		setEmailAddress(getContext(), emailaddress);
	}

	/**
	 * Set value of EmailAddress
	 * @param context
	 * @param emailaddress
	 */
	public final void setEmailAddress(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String emailaddress)
	{
		getMendixObject().setValue(context, MemberNames.EmailAddress.toString(), emailaddress);
	}

	/**
	 * @return value of Telephone
	 */
	public final java.lang.Long getTelephone()
	{
		return getTelephone(getContext());
	}

	/**
	 * @param context
	 * @return value of Telephone
	 */
	public final java.lang.Long getTelephone(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.Telephone.toString());
	}

	/**
	 * Set value of Telephone
	 * @param telephone
	 */
	public final void setTelephone(java.lang.Long telephone)
	{
		setTelephone(getContext(), telephone);
	}

	/**
	 * Set value of Telephone
	 * @param context
	 * @param telephone
	 */
	public final void setTelephone(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long telephone)
	{
		getMendixObject().setValue(context, MemberNames.Telephone.toString(), telephone);
	}

	/**
	 * @return value of ExpectedStartDate
	 */
	public final java.util.Date getExpectedStartDate()
	{
		return getExpectedStartDate(getContext());
	}

	/**
	 * @param context
	 * @return value of ExpectedStartDate
	 */
	public final java.util.Date getExpectedStartDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.ExpectedStartDate.toString());
	}

	/**
	 * Set value of ExpectedStartDate
	 * @param expectedstartdate
	 */
	public final void setExpectedStartDate(java.util.Date expectedstartdate)
	{
		setExpectedStartDate(getContext(), expectedstartdate);
	}

	/**
	 * Set value of ExpectedStartDate
	 * @param context
	 * @param expectedstartdate
	 */
	public final void setExpectedStartDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date expectedstartdate)
	{
		getMendixObject().setValue(context, MemberNames.ExpectedStartDate.toString(), expectedstartdate);
	}

	/**
	 * @return value of ExpectedCompletedDate
	 */
	public final java.util.Date getExpectedCompletedDate()
	{
		return getExpectedCompletedDate(getContext());
	}

	/**
	 * @param context
	 * @return value of ExpectedCompletedDate
	 */
	public final java.util.Date getExpectedCompletedDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.ExpectedCompletedDate.toString());
	}

	/**
	 * Set value of ExpectedCompletedDate
	 * @param expectedcompleteddate
	 */
	public final void setExpectedCompletedDate(java.util.Date expectedcompleteddate)
	{
		setExpectedCompletedDate(getContext(), expectedcompleteddate);
	}

	/**
	 * Set value of ExpectedCompletedDate
	 * @param context
	 * @param expectedcompleteddate
	 */
	public final void setExpectedCompletedDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date expectedcompleteddate)
	{
		getMendixObject().setValue(context, MemberNames.ExpectedCompletedDate.toString(), expectedcompleteddate);
	}

	/**
	 * @return value of ExpectedCompletionYears
	 */
	public final java.lang.Integer getExpectedCompletionYears()
	{
		return getExpectedCompletionYears(getContext());
	}

	/**
	 * @param context
	 * @return value of ExpectedCompletionYears
	 */
	public final java.lang.Integer getExpectedCompletionYears(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ExpectedCompletionYears.toString());
	}

	/**
	 * Set value of ExpectedCompletionYears
	 * @param expectedcompletionyears
	 */
	public final void setExpectedCompletionYears(java.lang.Integer expectedcompletionyears)
	{
		setExpectedCompletionYears(getContext(), expectedcompletionyears);
	}

	/**
	 * Set value of ExpectedCompletionYears
	 * @param context
	 * @param expectedcompletionyears
	 */
	public final void setExpectedCompletionYears(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer expectedcompletionyears)
	{
		getMendixObject().setValue(context, MemberNames.ExpectedCompletionYears.toString(), expectedcompletionyears);
	}

	/**
	 * @return value of ExpectedCompletionMonths
	 */
	public final java.lang.Integer getExpectedCompletionMonths()
	{
		return getExpectedCompletionMonths(getContext());
	}

	/**
	 * @param context
	 * @return value of ExpectedCompletionMonths
	 */
	public final java.lang.Integer getExpectedCompletionMonths(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ExpectedCompletionMonths.toString());
	}

	/**
	 * Set value of ExpectedCompletionMonths
	 * @param expectedcompletionmonths
	 */
	public final void setExpectedCompletionMonths(java.lang.Integer expectedcompletionmonths)
	{
		setExpectedCompletionMonths(getContext(), expectedcompletionmonths);
	}

	/**
	 * Set value of ExpectedCompletionMonths
	 * @param context
	 * @param expectedcompletionmonths
	 */
	public final void setExpectedCompletionMonths(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer expectedcompletionmonths)
	{
		getMendixObject().setValue(context, MemberNames.ExpectedCompletionMonths.toString(), expectedcompletionmonths);
	}

	/**
	 * @return value of ApplicationReferrenceNo
	 */
	public final java.lang.String getApplicationReferrenceNo()
	{
		return getApplicationReferrenceNo(getContext());
	}

	/**
	 * @param context
	 * @return value of ApplicationReferrenceNo
	 */
	public final java.lang.String getApplicationReferrenceNo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ApplicationReferrenceNo.toString());
	}

	/**
	 * Set value of ApplicationReferrenceNo
	 * @param applicationreferrenceno
	 */
	public final void setApplicationReferrenceNo(java.lang.String applicationreferrenceno)
	{
		setApplicationReferrenceNo(getContext(), applicationreferrenceno);
	}

	/**
	 * Set value of ApplicationReferrenceNo
	 * @param context
	 * @param applicationreferrenceno
	 */
	public final void setApplicationReferrenceNo(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String applicationreferrenceno)
	{
		getMendixObject().setValue(context, MemberNames.ApplicationReferrenceNo.toString(), applicationreferrenceno);
	}

	/**
	 * @return value of SelfPay
	 */
	public final java.lang.Boolean getSelfPay()
	{
		return getSelfPay(getContext());
	}

	/**
	 * @param context
	 * @return value of SelfPay
	 */
	public final java.lang.Boolean getSelfPay(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.SelfPay.toString());
	}

	/**
	 * Set value of SelfPay
	 * @param selfpay
	 */
	public final void setSelfPay(java.lang.Boolean selfpay)
	{
		setSelfPay(getContext(), selfpay);
	}

	/**
	 * Set value of SelfPay
	 * @param context
	 * @param selfpay
	 */
	public final void setSelfPay(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean selfpay)
	{
		getMendixObject().setValue(context, MemberNames.SelfPay.toString(), selfpay);
	}

	/**
	 * @return value of TradeNumber
	 */
	public final java.lang.String getTradeNumber()
	{
		return getTradeNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of TradeNumber
	 */
	public final java.lang.String getTradeNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TradeNumber.toString());
	}

	/**
	 * Set value of TradeNumber
	 * @param tradenumber
	 */
	public final void setTradeNumber(java.lang.String tradenumber)
	{
		setTradeNumber(getContext(), tradenumber);
	}

	/**
	 * Set value of TradeNumber
	 * @param context
	 * @param tradenumber
	 */
	public final void setTradeNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String tradenumber)
	{
		getMendixObject().setValue(context, MemberNames.TradeNumber.toString(), tradenumber);
	}

	/**
	 * @return value of Estimated_Value
	 */
	public final java.math.BigDecimal getEstimated_Value()
	{
		return getEstimated_Value(getContext());
	}

	/**
	 * @param context
	 * @return value of Estimated_Value
	 */
	public final java.math.BigDecimal getEstimated_Value(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Estimated_Value.toString());
	}

	/**
	 * Set value of Estimated_Value
	 * @param estimated_value
	 */
	public final void setEstimated_Value(java.math.BigDecimal estimated_value)
	{
		setEstimated_Value(getContext(), estimated_value);
	}

	/**
	 * Set value of Estimated_Value
	 * @param context
	 * @param estimated_value
	 */
	public final void setEstimated_Value(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal estimated_value)
	{
		getMendixObject().setValue(context, MemberNames.Estimated_Value.toString(), estimated_value);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final requestforpreliminaryregistrationofafacility_hospital.proxies.ENUM_Status getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final requestforpreliminaryregistrationofafacility_hospital.proxies.ENUM_Status getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Status.toString());
		if (obj == null)
			return null;

		return requestforpreliminaryregistrationofafacility_hospital.proxies.ENUM_Status.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(requestforpreliminaryregistrationofafacility_hospital.proxies.ENUM_Status status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, requestforpreliminaryregistrationofafacility_hospital.proxies.ENUM_Status status)
	{
		if (status != null)
			getMendixObject().setValue(context, MemberNames.Status.toString(), status.toString());
		else
			getMendixObject().setValue(context, MemberNames.Status.toString(), null);
	}

	/**
	 * @return value of WorkingHours
	 */
	public final java.lang.String getWorkingHours()
	{
		return getWorkingHours(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkingHours
	 */
	public final java.lang.String getWorkingHours(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.WorkingHours.toString());
	}

	/**
	 * Set value of WorkingHours
	 * @param workinghours
	 */
	public final void setWorkingHours(java.lang.String workinghours)
	{
		setWorkingHours(getContext(), workinghours);
	}

	/**
	 * Set value of WorkingHours
	 * @param context
	 * @param workinghours
	 */
	public final void setWorkingHours(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String workinghours)
	{
		getMendixObject().setValue(context, MemberNames.WorkingHours.toString(), workinghours);
	}

	/**
	 * @return value of Preliminary_NewOwner
	 */
	public final requestforpreliminaryregistrationofafacility_hospital.proxies.NewOwner getPreliminary_NewOwner() throws com.mendix.core.CoreException
	{
		return getPreliminary_NewOwner(getContext());
	}

	/**
	 * @param context
	 * @return value of Preliminary_NewOwner
	 */
	public final requestforpreliminaryregistrationofafacility_hospital.proxies.NewOwner getPreliminary_NewOwner(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		requestforpreliminaryregistrationofafacility_hospital.proxies.NewOwner result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Preliminary_NewOwner.toString());
		if (identifier != null)
			result = requestforpreliminaryregistrationofafacility_hospital.proxies.NewOwner.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Preliminary_NewOwner
	 * @param preliminary_newowner
	 */
	public final void setPreliminary_NewOwner(requestforpreliminaryregistrationofafacility_hospital.proxies.NewOwner preliminary_newowner)
	{
		setPreliminary_NewOwner(getContext(), preliminary_newowner);
	}

	/**
	 * Set value of Preliminary_NewOwner
	 * @param context
	 * @param preliminary_newowner
	 */
	public final void setPreliminary_NewOwner(com.mendix.systemwideinterfaces.core.IContext context, requestforpreliminaryregistrationofafacility_hospital.proxies.NewOwner preliminary_newowner)
	{
		if (preliminary_newowner == null)
			getMendixObject().setValue(context, MemberNames.Preliminary_NewOwner.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Preliminary_NewOwner.toString(), preliminary_newowner.getMendixObject().getId());
	}

	/**
	 * @return value of Preliminary_PharmaService
	 */
	public final requestforpreliminaryregistrationofafacility_hospital.proxies.PharmaService getPreliminary_PharmaService() throws com.mendix.core.CoreException
	{
		return getPreliminary_PharmaService(getContext());
	}

	/**
	 * @param context
	 * @return value of Preliminary_PharmaService
	 */
	public final requestforpreliminaryregistrationofafacility_hospital.proxies.PharmaService getPreliminary_PharmaService(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		requestforpreliminaryregistrationofafacility_hospital.proxies.PharmaService result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Preliminary_PharmaService.toString());
		if (identifier != null)
			result = requestforpreliminaryregistrationofafacility_hospital.proxies.PharmaService.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Preliminary_PharmaService
	 * @param preliminary_pharmaservice
	 */
	public final void setPreliminary_PharmaService(requestforpreliminaryregistrationofafacility_hospital.proxies.PharmaService preliminary_pharmaservice)
	{
		setPreliminary_PharmaService(getContext(), preliminary_pharmaservice);
	}

	/**
	 * Set value of Preliminary_PharmaService
	 * @param context
	 * @param preliminary_pharmaservice
	 */
	public final void setPreliminary_PharmaService(com.mendix.systemwideinterfaces.core.IContext context, requestforpreliminaryregistrationofafacility_hospital.proxies.PharmaService preliminary_pharmaservice)
	{
		if (preliminary_pharmaservice == null)
			getMendixObject().setValue(context, MemberNames.Preliminary_PharmaService.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Preliminary_PharmaService.toString(), preliminary_pharmaservice.getMendixObject().getId());
	}

	/**
	 * @return value of Servies_Preliminary
	 */
	public final java.util.List<requestforpreliminaryregistrationofafacility_hospital.proxies.Servies> getServies_Preliminary() throws com.mendix.core.CoreException
	{
		return getServies_Preliminary(getContext());
	}

	/**
	 * @param context
	 * @return value of Servies_Preliminary
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<requestforpreliminaryregistrationofafacility_hospital.proxies.Servies> getServies_Preliminary(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<requestforpreliminaryregistrationofafacility_hospital.proxies.Servies> result = new java.util.ArrayList<requestforpreliminaryregistrationofafacility_hospital.proxies.Servies>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.Servies_Preliminary.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(requestforpreliminaryregistrationofafacility_hospital.proxies.Servies.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of Servies_Preliminary
	 * @param servies_preliminary
	 */
	public final void setServies_Preliminary(java.util.List<requestforpreliminaryregistrationofafacility_hospital.proxies.Servies> servies_preliminary)
	{
		setServies_Preliminary(getContext(), servies_preliminary);
	}

	/**
	 * Set value of Servies_Preliminary
	 * @param context
	 * @param servies_preliminary
	 */
	public final void setServies_Preliminary(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<requestforpreliminaryregistrationofafacility_hospital.proxies.Servies> servies_preliminary)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (requestforpreliminaryregistrationofafacility_hospital.proxies.Servies proxyObject : servies_preliminary)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.Servies_Preliminary.toString(), identifiers);
	}

	/**
	 * @return value of School_clinic_details_Preliminary
	 */
	public final requestforpreliminaryregistrationofafacility_hospital.proxies.School_clinic_details getSchool_clinic_details_Preliminary() throws com.mendix.core.CoreException
	{
		return getSchool_clinic_details_Preliminary(getContext());
	}

	/**
	 * @param context
	 * @return value of School_clinic_details_Preliminary
	 */
	public final requestforpreliminaryregistrationofafacility_hospital.proxies.School_clinic_details getSchool_clinic_details_Preliminary(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		requestforpreliminaryregistrationofafacility_hospital.proxies.School_clinic_details result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.School_clinic_details_Preliminary.toString());
		if (identifier != null)
			result = requestforpreliminaryregistrationofafacility_hospital.proxies.School_clinic_details.load(context, identifier);
		return result;
	}

	/**
	 * Set value of School_clinic_details_Preliminary
	 * @param school_clinic_details_preliminary
	 */
	public final void setSchool_clinic_details_Preliminary(requestforpreliminaryregistrationofafacility_hospital.proxies.School_clinic_details school_clinic_details_preliminary)
	{
		setSchool_clinic_details_Preliminary(getContext(), school_clinic_details_preliminary);
	}

	/**
	 * Set value of School_clinic_details_Preliminary
	 * @param context
	 * @param school_clinic_details_preliminary
	 */
	public final void setSchool_clinic_details_Preliminary(com.mendix.systemwideinterfaces.core.IContext context, requestforpreliminaryregistrationofafacility_hospital.proxies.School_clinic_details school_clinic_details_preliminary)
	{
		if (school_clinic_details_preliminary == null)
			getMendixObject().setValue(context, MemberNames.School_clinic_details_Preliminary.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.School_clinic_details_Preliminary.toString(), school_clinic_details_preliminary.getMendixObject().getId());
	}

	/**
	 * @return value of Preliminary_FacilityType
	 */
	public final requestforpreliminaryregistrationofafacility_hospital.proxies.FacilityType getPreliminary_FacilityType() throws com.mendix.core.CoreException
	{
		return getPreliminary_FacilityType(getContext());
	}

	/**
	 * @param context
	 * @return value of Preliminary_FacilityType
	 */
	public final requestforpreliminaryregistrationofafacility_hospital.proxies.FacilityType getPreliminary_FacilityType(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		requestforpreliminaryregistrationofafacility_hospital.proxies.FacilityType result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Preliminary_FacilityType.toString());
		if (identifier != null)
			result = requestforpreliminaryregistrationofafacility_hospital.proxies.FacilityType.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Preliminary_FacilityType
	 * @param preliminary_facilitytype
	 */
	public final void setPreliminary_FacilityType(requestforpreliminaryregistrationofafacility_hospital.proxies.FacilityType preliminary_facilitytype)
	{
		setPreliminary_FacilityType(getContext(), preliminary_facilitytype);
	}

	/**
	 * Set value of Preliminary_FacilityType
	 * @param context
	 * @param preliminary_facilitytype
	 */
	public final void setPreliminary_FacilityType(com.mendix.systemwideinterfaces.core.IContext context, requestforpreliminaryregistrationofafacility_hospital.proxies.FacilityType preliminary_facilitytype)
	{
		if (preliminary_facilitytype == null)
			getMendixObject().setValue(context, MemberNames.Preliminary_FacilityType.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Preliminary_FacilityType.toString(), preliminary_facilitytype.getMendixObject().getId());
	}

	/**
	 * @return value of Preliminary_FacilitySubtype
	 */
	public final requestforpreliminaryregistrationofafacility_hospital.proxies.FacilitySubtype getPreliminary_FacilitySubtype() throws com.mendix.core.CoreException
	{
		return getPreliminary_FacilitySubtype(getContext());
	}

	/**
	 * @param context
	 * @return value of Preliminary_FacilitySubtype
	 */
	public final requestforpreliminaryregistrationofafacility_hospital.proxies.FacilitySubtype getPreliminary_FacilitySubtype(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		requestforpreliminaryregistrationofafacility_hospital.proxies.FacilitySubtype result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Preliminary_FacilitySubtype.toString());
		if (identifier != null)
			result = requestforpreliminaryregistrationofafacility_hospital.proxies.FacilitySubtype.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Preliminary_FacilitySubtype
	 * @param preliminary_facilitysubtype
	 */
	public final void setPreliminary_FacilitySubtype(requestforpreliminaryregistrationofafacility_hospital.proxies.FacilitySubtype preliminary_facilitysubtype)
	{
		setPreliminary_FacilitySubtype(getContext(), preliminary_facilitysubtype);
	}

	/**
	 * Set value of Preliminary_FacilitySubtype
	 * @param context
	 * @param preliminary_facilitysubtype
	 */
	public final void setPreliminary_FacilitySubtype(com.mendix.systemwideinterfaces.core.IContext context, requestforpreliminaryregistrationofafacility_hospital.proxies.FacilitySubtype preliminary_facilitysubtype)
	{
		if (preliminary_facilitysubtype == null)
			getMendixObject().setValue(context, MemberNames.Preliminary_FacilitySubtype.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Preliminary_FacilitySubtype.toString(), preliminary_facilitysubtype.getMendixObject().getId());
	}

	/**
	 * @return value of RehabilitationSubtypes_Preliminary
	 */
	public final java.util.List<requestforpreliminaryregistrationofafacility_hospital.proxies.RehabilitationSubtypes> getRehabilitationSubtypes_Preliminary() throws com.mendix.core.CoreException
	{
		return getRehabilitationSubtypes_Preliminary(getContext());
	}

	/**
	 * @param context
	 * @return value of RehabilitationSubtypes_Preliminary
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<requestforpreliminaryregistrationofafacility_hospital.proxies.RehabilitationSubtypes> getRehabilitationSubtypes_Preliminary(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<requestforpreliminaryregistrationofafacility_hospital.proxies.RehabilitationSubtypes> result = new java.util.ArrayList<requestforpreliminaryregistrationofafacility_hospital.proxies.RehabilitationSubtypes>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.RehabilitationSubtypes_Preliminary.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(requestforpreliminaryregistrationofafacility_hospital.proxies.RehabilitationSubtypes.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of RehabilitationSubtypes_Preliminary
	 * @param rehabilitationsubtypes_preliminary
	 */
	public final void setRehabilitationSubtypes_Preliminary(java.util.List<requestforpreliminaryregistrationofafacility_hospital.proxies.RehabilitationSubtypes> rehabilitationsubtypes_preliminary)
	{
		setRehabilitationSubtypes_Preliminary(getContext(), rehabilitationsubtypes_preliminary);
	}

	/**
	 * Set value of RehabilitationSubtypes_Preliminary
	 * @param context
	 * @param rehabilitationsubtypes_preliminary
	 */
	public final void setRehabilitationSubtypes_Preliminary(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<requestforpreliminaryregistrationofafacility_hospital.proxies.RehabilitationSubtypes> rehabilitationsubtypes_preliminary)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (requestforpreliminaryregistrationofafacility_hospital.proxies.RehabilitationSubtypes proxyObject : rehabilitationsubtypes_preliminary)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.RehabilitationSubtypes_Preliminary.toString(), identifiers);
	}

	/**
	 * @return value of HospitalDetails_Preliminary
	 */
	public final requestforpreliminaryregistrationofafacility_hospital.proxies.HospitalDetails getHospitalDetails_Preliminary() throws com.mendix.core.CoreException
	{
		return getHospitalDetails_Preliminary(getContext());
	}

	/**
	 * @param context
	 * @return value of HospitalDetails_Preliminary
	 */
	public final requestforpreliminaryregistrationofafacility_hospital.proxies.HospitalDetails getHospitalDetails_Preliminary(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		requestforpreliminaryregistrationofafacility_hospital.proxies.HospitalDetails result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.HospitalDetails_Preliminary.toString());
		if (identifier != null)
			result = requestforpreliminaryregistrationofafacility_hospital.proxies.HospitalDetails.load(context, identifier);
		return result;
	}

	/**
	 * Set value of HospitalDetails_Preliminary
	 * @param hospitaldetails_preliminary
	 */
	public final void setHospitalDetails_Preliminary(requestforpreliminaryregistrationofafacility_hospital.proxies.HospitalDetails hospitaldetails_preliminary)
	{
		setHospitalDetails_Preliminary(getContext(), hospitaldetails_preliminary);
	}

	/**
	 * Set value of HospitalDetails_Preliminary
	 * @param context
	 * @param hospitaldetails_preliminary
	 */
	public final void setHospitalDetails_Preliminary(com.mendix.systemwideinterfaces.core.IContext context, requestforpreliminaryregistrationofafacility_hospital.proxies.HospitalDetails hospitaldetails_preliminary)
	{
		if (hospitaldetails_preliminary == null)
			getMendixObject().setValue(context, MemberNames.HospitalDetails_Preliminary.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.HospitalDetails_Preliminary.toString(), hospitaldetails_preliminary.getMendixObject().getId());
	}

	/**
	 * @return value of Preliminary_Diagonist_Servies
	 */
	public final java.util.List<requestforpreliminaryregistrationofafacility_hospital.proxies.Servies> getPreliminary_Diagonist_Servies() throws com.mendix.core.CoreException
	{
		return getPreliminary_Diagonist_Servies(getContext());
	}

	/**
	 * @param context
	 * @return value of Preliminary_Diagonist_Servies
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<requestforpreliminaryregistrationofafacility_hospital.proxies.Servies> getPreliminary_Diagonist_Servies(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<requestforpreliminaryregistrationofafacility_hospital.proxies.Servies> result = new java.util.ArrayList<requestforpreliminaryregistrationofafacility_hospital.proxies.Servies>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.Preliminary_Diagonist_Servies.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(requestforpreliminaryregistrationofafacility_hospital.proxies.Servies.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of Preliminary_Diagonist_Servies
	 * @param preliminary_diagonist_servies
	 */
	public final void setPreliminary_Diagonist_Servies(java.util.List<requestforpreliminaryregistrationofafacility_hospital.proxies.Servies> preliminary_diagonist_servies)
	{
		setPreliminary_Diagonist_Servies(getContext(), preliminary_diagonist_servies);
	}

	/**
	 * Set value of Preliminary_Diagonist_Servies
	 * @param context
	 * @param preliminary_diagonist_servies
	 */
	public final void setPreliminary_Diagonist_Servies(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<requestforpreliminaryregistrationofafacility_hospital.proxies.Servies> preliminary_diagonist_servies)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (requestforpreliminaryregistrationofafacility_hospital.proxies.Servies proxyObject : preliminary_diagonist_servies)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.Preliminary_Diagonist_Servies.toString(), identifiers);
	}

	/**
	 * @return value of Preliminary_Account
	 */
	public final administration.proxies.Account getPreliminary_Account() throws com.mendix.core.CoreException
	{
		return getPreliminary_Account(getContext());
	}

	/**
	 * @param context
	 * @return value of Preliminary_Account
	 */
	public final administration.proxies.Account getPreliminary_Account(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		administration.proxies.Account result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Preliminary_Account.toString());
		if (identifier != null)
			result = administration.proxies.Account.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Preliminary_Account
	 * @param preliminary_account
	 */
	public final void setPreliminary_Account(administration.proxies.Account preliminary_account)
	{
		setPreliminary_Account(getContext(), preliminary_account);
	}

	/**
	 * Set value of Preliminary_Account
	 * @param context
	 * @param preliminary_account
	 */
	public final void setPreliminary_Account(com.mendix.systemwideinterfaces.core.IContext context, administration.proxies.Account preliminary_account)
	{
		if (preliminary_account == null)
			getMendixObject().setValue(context, MemberNames.Preliminary_Account.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Preliminary_Account.toString(), preliminary_account.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return preliminaryMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final requestforpreliminaryregistrationofafacility_hospital.proxies.Preliminary that = (requestforpreliminaryregistrationofafacility_hospital.proxies.Preliminary) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "RequestforPreliminaryRegistrationofaFacility_Hospital.Preliminary";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
