// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package requestforpreliminaryregistrationofafacility_hospital.proxies;

public class ScopeServices
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject scopeServicesMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "RequestforPreliminaryRegistrationofaFacility_Hospital.ScopeServices";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		AnatomicPathology("AnatomicPathology"),
		BloodBankandTransf("BloodBankandTransf"),
		ClinicalChemistry("ClinicalChemistry"),
		ClinicalPathology("ClinicalPathology"),
		Cytogenetics("Cytogenetics"),
		Hematology("Hematology"),
		Histocompatibility("Histocompatibility"),
		Immunology_Serology("Immunology_Serology"),
		Microbiology("Microbiology"),
		MolecularBiology("MolecularBiology"),
		Virology("Virology"),
		ScopeServices_SupportServices("RequestforPreliminaryRegistrationofaFacility_Hospital.ScopeServices_SupportServices");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ScopeServices(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "RequestforPreliminaryRegistrationofaFacility_Hospital.ScopeServices"));
	}

	protected ScopeServices(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject scopeServicesMendixObject)
	{
		if (scopeServicesMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("RequestforPreliminaryRegistrationofaFacility_Hospital.ScopeServices", scopeServicesMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a RequestforPreliminaryRegistrationofaFacility_Hospital.ScopeServices");

		this.scopeServicesMendixObject = scopeServicesMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'ScopeServices.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static requestforpreliminaryregistrationofafacility_hospital.proxies.ScopeServices initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return requestforpreliminaryregistrationofafacility_hospital.proxies.ScopeServices.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static requestforpreliminaryregistrationofafacility_hospital.proxies.ScopeServices initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new requestforpreliminaryregistrationofafacility_hospital.proxies.ScopeServices(context, mendixObject);
	}

	public static requestforpreliminaryregistrationofafacility_hospital.proxies.ScopeServices load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return requestforpreliminaryregistrationofafacility_hospital.proxies.ScopeServices.initialize(context, mendixObject);
	}

	public static java.util.List<requestforpreliminaryregistrationofafacility_hospital.proxies.ScopeServices> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<requestforpreliminaryregistrationofafacility_hospital.proxies.ScopeServices> result = new java.util.ArrayList<requestforpreliminaryregistrationofafacility_hospital.proxies.ScopeServices>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//RequestforPreliminaryRegistrationofaFacility_Hospital.ScopeServices" + xpathConstraint))
			result.add(requestforpreliminaryregistrationofafacility_hospital.proxies.ScopeServices.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of AnatomicPathology
	 */
	public final java.lang.Boolean getAnatomicPathology()
	{
		return getAnatomicPathology(getContext());
	}

	/**
	 * @param context
	 * @return value of AnatomicPathology
	 */
	public final java.lang.Boolean getAnatomicPathology(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.AnatomicPathology.toString());
	}

	/**
	 * Set value of AnatomicPathology
	 * @param anatomicpathology
	 */
	public final void setAnatomicPathology(java.lang.Boolean anatomicpathology)
	{
		setAnatomicPathology(getContext(), anatomicpathology);
	}

	/**
	 * Set value of AnatomicPathology
	 * @param context
	 * @param anatomicpathology
	 */
	public final void setAnatomicPathology(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean anatomicpathology)
	{
		getMendixObject().setValue(context, MemberNames.AnatomicPathology.toString(), anatomicpathology);
	}

	/**
	 * @return value of BloodBankandTransf
	 */
	public final java.lang.Boolean getBloodBankandTransf()
	{
		return getBloodBankandTransf(getContext());
	}

	/**
	 * @param context
	 * @return value of BloodBankandTransf
	 */
	public final java.lang.Boolean getBloodBankandTransf(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.BloodBankandTransf.toString());
	}

	/**
	 * Set value of BloodBankandTransf
	 * @param bloodbankandtransf
	 */
	public final void setBloodBankandTransf(java.lang.Boolean bloodbankandtransf)
	{
		setBloodBankandTransf(getContext(), bloodbankandtransf);
	}

	/**
	 * Set value of BloodBankandTransf
	 * @param context
	 * @param bloodbankandtransf
	 */
	public final void setBloodBankandTransf(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean bloodbankandtransf)
	{
		getMendixObject().setValue(context, MemberNames.BloodBankandTransf.toString(), bloodbankandtransf);
	}

	/**
	 * @return value of ClinicalChemistry
	 */
	public final java.lang.Boolean getClinicalChemistry()
	{
		return getClinicalChemistry(getContext());
	}

	/**
	 * @param context
	 * @return value of ClinicalChemistry
	 */
	public final java.lang.Boolean getClinicalChemistry(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ClinicalChemistry.toString());
	}

	/**
	 * Set value of ClinicalChemistry
	 * @param clinicalchemistry
	 */
	public final void setClinicalChemistry(java.lang.Boolean clinicalchemistry)
	{
		setClinicalChemistry(getContext(), clinicalchemistry);
	}

	/**
	 * Set value of ClinicalChemistry
	 * @param context
	 * @param clinicalchemistry
	 */
	public final void setClinicalChemistry(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean clinicalchemistry)
	{
		getMendixObject().setValue(context, MemberNames.ClinicalChemistry.toString(), clinicalchemistry);
	}

	/**
	 * @return value of ClinicalPathology
	 */
	public final java.lang.Boolean getClinicalPathology()
	{
		return getClinicalPathology(getContext());
	}

	/**
	 * @param context
	 * @return value of ClinicalPathology
	 */
	public final java.lang.Boolean getClinicalPathology(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ClinicalPathology.toString());
	}

	/**
	 * Set value of ClinicalPathology
	 * @param clinicalpathology
	 */
	public final void setClinicalPathology(java.lang.Boolean clinicalpathology)
	{
		setClinicalPathology(getContext(), clinicalpathology);
	}

	/**
	 * Set value of ClinicalPathology
	 * @param context
	 * @param clinicalpathology
	 */
	public final void setClinicalPathology(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean clinicalpathology)
	{
		getMendixObject().setValue(context, MemberNames.ClinicalPathology.toString(), clinicalpathology);
	}

	/**
	 * @return value of Cytogenetics
	 */
	public final java.lang.Boolean getCytogenetics()
	{
		return getCytogenetics(getContext());
	}

	/**
	 * @param context
	 * @return value of Cytogenetics
	 */
	public final java.lang.Boolean getCytogenetics(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Cytogenetics.toString());
	}

	/**
	 * Set value of Cytogenetics
	 * @param cytogenetics
	 */
	public final void setCytogenetics(java.lang.Boolean cytogenetics)
	{
		setCytogenetics(getContext(), cytogenetics);
	}

	/**
	 * Set value of Cytogenetics
	 * @param context
	 * @param cytogenetics
	 */
	public final void setCytogenetics(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean cytogenetics)
	{
		getMendixObject().setValue(context, MemberNames.Cytogenetics.toString(), cytogenetics);
	}

	/**
	 * @return value of Hematology
	 */
	public final java.lang.Boolean getHematology()
	{
		return getHematology(getContext());
	}

	/**
	 * @param context
	 * @return value of Hematology
	 */
	public final java.lang.Boolean getHematology(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Hematology.toString());
	}

	/**
	 * Set value of Hematology
	 * @param hematology
	 */
	public final void setHematology(java.lang.Boolean hematology)
	{
		setHematology(getContext(), hematology);
	}

	/**
	 * Set value of Hematology
	 * @param context
	 * @param hematology
	 */
	public final void setHematology(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean hematology)
	{
		getMendixObject().setValue(context, MemberNames.Hematology.toString(), hematology);
	}

	/**
	 * @return value of Histocompatibility
	 */
	public final java.lang.Boolean getHistocompatibility()
	{
		return getHistocompatibility(getContext());
	}

	/**
	 * @param context
	 * @return value of Histocompatibility
	 */
	public final java.lang.Boolean getHistocompatibility(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Histocompatibility.toString());
	}

	/**
	 * Set value of Histocompatibility
	 * @param histocompatibility
	 */
	public final void setHistocompatibility(java.lang.Boolean histocompatibility)
	{
		setHistocompatibility(getContext(), histocompatibility);
	}

	/**
	 * Set value of Histocompatibility
	 * @param context
	 * @param histocompatibility
	 */
	public final void setHistocompatibility(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean histocompatibility)
	{
		getMendixObject().setValue(context, MemberNames.Histocompatibility.toString(), histocompatibility);
	}

	/**
	 * @return value of Immunology_Serology
	 */
	public final java.lang.Boolean getImmunology_Serology()
	{
		return getImmunology_Serology(getContext());
	}

	/**
	 * @param context
	 * @return value of Immunology_Serology
	 */
	public final java.lang.Boolean getImmunology_Serology(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Immunology_Serology.toString());
	}

	/**
	 * Set value of Immunology_Serology
	 * @param immunology_serology
	 */
	public final void setImmunology_Serology(java.lang.Boolean immunology_serology)
	{
		setImmunology_Serology(getContext(), immunology_serology);
	}

	/**
	 * Set value of Immunology_Serology
	 * @param context
	 * @param immunology_serology
	 */
	public final void setImmunology_Serology(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean immunology_serology)
	{
		getMendixObject().setValue(context, MemberNames.Immunology_Serology.toString(), immunology_serology);
	}

	/**
	 * @return value of Microbiology
	 */
	public final java.lang.Boolean getMicrobiology()
	{
		return getMicrobiology(getContext());
	}

	/**
	 * @param context
	 * @return value of Microbiology
	 */
	public final java.lang.Boolean getMicrobiology(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Microbiology.toString());
	}

	/**
	 * Set value of Microbiology
	 * @param microbiology
	 */
	public final void setMicrobiology(java.lang.Boolean microbiology)
	{
		setMicrobiology(getContext(), microbiology);
	}

	/**
	 * Set value of Microbiology
	 * @param context
	 * @param microbiology
	 */
	public final void setMicrobiology(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean microbiology)
	{
		getMendixObject().setValue(context, MemberNames.Microbiology.toString(), microbiology);
	}

	/**
	 * @return value of MolecularBiology
	 */
	public final java.lang.Boolean getMolecularBiology()
	{
		return getMolecularBiology(getContext());
	}

	/**
	 * @param context
	 * @return value of MolecularBiology
	 */
	public final java.lang.Boolean getMolecularBiology(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.MolecularBiology.toString());
	}

	/**
	 * Set value of MolecularBiology
	 * @param molecularbiology
	 */
	public final void setMolecularBiology(java.lang.Boolean molecularbiology)
	{
		setMolecularBiology(getContext(), molecularbiology);
	}

	/**
	 * Set value of MolecularBiology
	 * @param context
	 * @param molecularbiology
	 */
	public final void setMolecularBiology(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean molecularbiology)
	{
		getMendixObject().setValue(context, MemberNames.MolecularBiology.toString(), molecularbiology);
	}

	/**
	 * @return value of Virology
	 */
	public final java.lang.Boolean getVirology()
	{
		return getVirology(getContext());
	}

	/**
	 * @param context
	 * @return value of Virology
	 */
	public final java.lang.Boolean getVirology(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Virology.toString());
	}

	/**
	 * Set value of Virology
	 * @param virology
	 */
	public final void setVirology(java.lang.Boolean virology)
	{
		setVirology(getContext(), virology);
	}

	/**
	 * Set value of Virology
	 * @param context
	 * @param virology
	 */
	public final void setVirology(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean virology)
	{
		getMendixObject().setValue(context, MemberNames.Virology.toString(), virology);
	}

	/**
	 * @return value of ScopeServices_SupportServices
	 */
	public final requestforpreliminaryregistrationofafacility_hospital.proxies.SupportServices getScopeServices_SupportServices() throws com.mendix.core.CoreException
	{
		return getScopeServices_SupportServices(getContext());
	}

	/**
	 * @param context
	 * @return value of ScopeServices_SupportServices
	 */
	public final requestforpreliminaryregistrationofafacility_hospital.proxies.SupportServices getScopeServices_SupportServices(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		requestforpreliminaryregistrationofafacility_hospital.proxies.SupportServices result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ScopeServices_SupportServices.toString());
		if (identifier != null)
			result = requestforpreliminaryregistrationofafacility_hospital.proxies.SupportServices.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ScopeServices_SupportServices
	 * @param scopeservices_supportservices
	 */
	public final void setScopeServices_SupportServices(requestforpreliminaryregistrationofafacility_hospital.proxies.SupportServices scopeservices_supportservices)
	{
		setScopeServices_SupportServices(getContext(), scopeservices_supportservices);
	}

	/**
	 * Set value of ScopeServices_SupportServices
	 * @param context
	 * @param scopeservices_supportservices
	 */
	public final void setScopeServices_SupportServices(com.mendix.systemwideinterfaces.core.IContext context, requestforpreliminaryregistrationofafacility_hospital.proxies.SupportServices scopeservices_supportservices)
	{
		if (scopeservices_supportservices == null)
			getMendixObject().setValue(context, MemberNames.ScopeServices_SupportServices.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ScopeServices_SupportServices.toString(), scopeservices_supportservices.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return scopeServicesMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final requestforpreliminaryregistrationofafacility_hospital.proxies.ScopeServices that = (requestforpreliminaryregistrationofafacility_hospital.proxies.ScopeServices) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "RequestforPreliminaryRegistrationofaFacility_Hospital.ScopeServices";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
