// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package requestforpreliminaryregistrationofafacility_hospital.proxies;

public class Specialities
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject specialitiesMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "RequestforPreliminaryRegistrationofaFacility_Hospital.Specialities";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Speciality("Speciality"),
		SubSpeciality("SubSpeciality"),
		NumberOfStaffs("NumberOfStaffs");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Specialities(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "RequestforPreliminaryRegistrationofaFacility_Hospital.Specialities"));
	}

	protected Specialities(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject specialitiesMendixObject)
	{
		if (specialitiesMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("RequestforPreliminaryRegistrationofaFacility_Hospital.Specialities", specialitiesMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a RequestforPreliminaryRegistrationofaFacility_Hospital.Specialities");

		this.specialitiesMendixObject = specialitiesMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Specialities.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static requestforpreliminaryregistrationofafacility_hospital.proxies.Specialities initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return requestforpreliminaryregistrationofafacility_hospital.proxies.Specialities.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static requestforpreliminaryregistrationofafacility_hospital.proxies.Specialities initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new requestforpreliminaryregistrationofafacility_hospital.proxies.Specialities(context, mendixObject);
	}

	public static requestforpreliminaryregistrationofafacility_hospital.proxies.Specialities load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return requestforpreliminaryregistrationofafacility_hospital.proxies.Specialities.initialize(context, mendixObject);
	}

	public static java.util.List<requestforpreliminaryregistrationofafacility_hospital.proxies.Specialities> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<requestforpreliminaryregistrationofafacility_hospital.proxies.Specialities> result = new java.util.ArrayList<requestforpreliminaryregistrationofafacility_hospital.proxies.Specialities>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//RequestforPreliminaryRegistrationofaFacility_Hospital.Specialities" + xpathConstraint))
			result.add(requestforpreliminaryregistrationofafacility_hospital.proxies.Specialities.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Speciality
	 */
	public final java.lang.String getSpeciality()
	{
		return getSpeciality(getContext());
	}

	/**
	 * @param context
	 * @return value of Speciality
	 */
	public final java.lang.String getSpeciality(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Speciality.toString());
	}

	/**
	 * Set value of Speciality
	 * @param speciality
	 */
	public final void setSpeciality(java.lang.String speciality)
	{
		setSpeciality(getContext(), speciality);
	}

	/**
	 * Set value of Speciality
	 * @param context
	 * @param speciality
	 */
	public final void setSpeciality(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String speciality)
	{
		getMendixObject().setValue(context, MemberNames.Speciality.toString(), speciality);
	}

	/**
	 * @return value of SubSpeciality
	 */
	public final java.lang.String getSubSpeciality()
	{
		return getSubSpeciality(getContext());
	}

	/**
	 * @param context
	 * @return value of SubSpeciality
	 */
	public final java.lang.String getSubSpeciality(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SubSpeciality.toString());
	}

	/**
	 * Set value of SubSpeciality
	 * @param subspeciality
	 */
	public final void setSubSpeciality(java.lang.String subspeciality)
	{
		setSubSpeciality(getContext(), subspeciality);
	}

	/**
	 * Set value of SubSpeciality
	 * @param context
	 * @param subspeciality
	 */
	public final void setSubSpeciality(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String subspeciality)
	{
		getMendixObject().setValue(context, MemberNames.SubSpeciality.toString(), subspeciality);
	}

	/**
	 * @return value of NumberOfStaffs
	 */
	public final java.lang.Integer getNumberOfStaffs()
	{
		return getNumberOfStaffs(getContext());
	}

	/**
	 * @param context
	 * @return value of NumberOfStaffs
	 */
	public final java.lang.Integer getNumberOfStaffs(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.NumberOfStaffs.toString());
	}

	/**
	 * Set value of NumberOfStaffs
	 * @param numberofstaffs
	 */
	public final void setNumberOfStaffs(java.lang.Integer numberofstaffs)
	{
		setNumberOfStaffs(getContext(), numberofstaffs);
	}

	/**
	 * Set value of NumberOfStaffs
	 * @param context
	 * @param numberofstaffs
	 */
	public final void setNumberOfStaffs(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer numberofstaffs)
	{
		getMendixObject().setValue(context, MemberNames.NumberOfStaffs.toString(), numberofstaffs);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return specialitiesMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final requestforpreliminaryregistrationofafacility_hospital.proxies.Specialities that = (requestforpreliminaryregistrationofafacility_hospital.proxies.Specialities) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "RequestforPreliminaryRegistrationofaFacility_Hospital.Specialities";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
