// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package requestforpreliminaryregistrationofafacility_hospital.proxies;

public class SupportServices
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject supportServicesMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "RequestforPreliminaryRegistrationofaFacility_Hospital.SupportServices";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ERG_EOG_VOP("ERG_EOG_VOP"),
		HealthEducation("HealthEducation"),
		SocialWork("SocialWork"),
		ScopeServices_SupportServices("RequestforPreliminaryRegistrationofaFacility_Hospital.ScopeServices_SupportServices"),
		SupportServices_Preliminary("RequestforPreliminaryRegistrationofaFacility_Hospital.SupportServices_Preliminary");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SupportServices(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "RequestforPreliminaryRegistrationofaFacility_Hospital.SupportServices"));
	}

	protected SupportServices(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject supportServicesMendixObject)
	{
		if (supportServicesMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("RequestforPreliminaryRegistrationofaFacility_Hospital.SupportServices", supportServicesMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a RequestforPreliminaryRegistrationofaFacility_Hospital.SupportServices");

		this.supportServicesMendixObject = supportServicesMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'SupportServices.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static requestforpreliminaryregistrationofafacility_hospital.proxies.SupportServices initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return requestforpreliminaryregistrationofafacility_hospital.proxies.SupportServices.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static requestforpreliminaryregistrationofafacility_hospital.proxies.SupportServices initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new requestforpreliminaryregistrationofafacility_hospital.proxies.SupportServices(context, mendixObject);
	}

	public static requestforpreliminaryregistrationofafacility_hospital.proxies.SupportServices load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return requestforpreliminaryregistrationofafacility_hospital.proxies.SupportServices.initialize(context, mendixObject);
	}

	public static java.util.List<requestforpreliminaryregistrationofafacility_hospital.proxies.SupportServices> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<requestforpreliminaryregistrationofafacility_hospital.proxies.SupportServices> result = new java.util.ArrayList<requestforpreliminaryregistrationofafacility_hospital.proxies.SupportServices>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//RequestforPreliminaryRegistrationofaFacility_Hospital.SupportServices" + xpathConstraint))
			result.add(requestforpreliminaryregistrationofafacility_hospital.proxies.SupportServices.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of ERG_EOG_VOP
	 */
	public final java.lang.Boolean getERG_EOG_VOP()
	{
		return getERG_EOG_VOP(getContext());
	}

	/**
	 * @param context
	 * @return value of ERG_EOG_VOP
	 */
	public final java.lang.Boolean getERG_EOG_VOP(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ERG_EOG_VOP.toString());
	}

	/**
	 * Set value of ERG_EOG_VOP
	 * @param erg_eog_vop
	 */
	public final void setERG_EOG_VOP(java.lang.Boolean erg_eog_vop)
	{
		setERG_EOG_VOP(getContext(), erg_eog_vop);
	}

	/**
	 * Set value of ERG_EOG_VOP
	 * @param context
	 * @param erg_eog_vop
	 */
	public final void setERG_EOG_VOP(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean erg_eog_vop)
	{
		getMendixObject().setValue(context, MemberNames.ERG_EOG_VOP.toString(), erg_eog_vop);
	}

	/**
	 * @return value of HealthEducation
	 */
	public final java.lang.Boolean getHealthEducation()
	{
		return getHealthEducation(getContext());
	}

	/**
	 * @param context
	 * @return value of HealthEducation
	 */
	public final java.lang.Boolean getHealthEducation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.HealthEducation.toString());
	}

	/**
	 * Set value of HealthEducation
	 * @param healtheducation
	 */
	public final void setHealthEducation(java.lang.Boolean healtheducation)
	{
		setHealthEducation(getContext(), healtheducation);
	}

	/**
	 * Set value of HealthEducation
	 * @param context
	 * @param healtheducation
	 */
	public final void setHealthEducation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean healtheducation)
	{
		getMendixObject().setValue(context, MemberNames.HealthEducation.toString(), healtheducation);
	}

	/**
	 * @return value of SocialWork
	 */
	public final java.lang.Boolean getSocialWork()
	{
		return getSocialWork(getContext());
	}

	/**
	 * @param context
	 * @return value of SocialWork
	 */
	public final java.lang.Boolean getSocialWork(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.SocialWork.toString());
	}

	/**
	 * Set value of SocialWork
	 * @param socialwork
	 */
	public final void setSocialWork(java.lang.Boolean socialwork)
	{
		setSocialWork(getContext(), socialwork);
	}

	/**
	 * Set value of SocialWork
	 * @param context
	 * @param socialwork
	 */
	public final void setSocialWork(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean socialwork)
	{
		getMendixObject().setValue(context, MemberNames.SocialWork.toString(), socialwork);
	}

	/**
	 * @return value of ScopeServices_SupportServices
	 */
	public final requestforpreliminaryregistrationofafacility_hospital.proxies.ScopeServices getScopeServices_SupportServices() throws com.mendix.core.CoreException
	{
		return getScopeServices_SupportServices(getContext());
	}

	/**
	 * @param context
	 * @return value of ScopeServices_SupportServices
	 */
	public final requestforpreliminaryregistrationofafacility_hospital.proxies.ScopeServices getScopeServices_SupportServices(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		requestforpreliminaryregistrationofafacility_hospital.proxies.ScopeServices result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ScopeServices_SupportServices.toString());
		if (identifier != null)
			result = requestforpreliminaryregistrationofafacility_hospital.proxies.ScopeServices.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ScopeServices_SupportServices
	 * @param scopeservices_supportservices
	 */
	public final void setScopeServices_SupportServices(requestforpreliminaryregistrationofafacility_hospital.proxies.ScopeServices scopeservices_supportservices)
	{
		setScopeServices_SupportServices(getContext(), scopeservices_supportservices);
	}

	/**
	 * Set value of ScopeServices_SupportServices
	 * @param context
	 * @param scopeservices_supportservices
	 */
	public final void setScopeServices_SupportServices(com.mendix.systemwideinterfaces.core.IContext context, requestforpreliminaryregistrationofafacility_hospital.proxies.ScopeServices scopeservices_supportservices)
	{
		if (scopeservices_supportservices == null)
			getMendixObject().setValue(context, MemberNames.ScopeServices_SupportServices.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ScopeServices_SupportServices.toString(), scopeservices_supportservices.getMendixObject().getId());
	}

	/**
	 * @return value of SupportServices_Preliminary
	 */
	public final requestforpreliminaryregistrationofafacility_hospital.proxies.Preliminary getSupportServices_Preliminary() throws com.mendix.core.CoreException
	{
		return getSupportServices_Preliminary(getContext());
	}

	/**
	 * @param context
	 * @return value of SupportServices_Preliminary
	 */
	public final requestforpreliminaryregistrationofafacility_hospital.proxies.Preliminary getSupportServices_Preliminary(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		requestforpreliminaryregistrationofafacility_hospital.proxies.Preliminary result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SupportServices_Preliminary.toString());
		if (identifier != null)
			result = requestforpreliminaryregistrationofafacility_hospital.proxies.Preliminary.load(context, identifier);
		return result;
	}

	/**
	 * Set value of SupportServices_Preliminary
	 * @param supportservices_preliminary
	 */
	public final void setSupportServices_Preliminary(requestforpreliminaryregistrationofafacility_hospital.proxies.Preliminary supportservices_preliminary)
	{
		setSupportServices_Preliminary(getContext(), supportservices_preliminary);
	}

	/**
	 * Set value of SupportServices_Preliminary
	 * @param context
	 * @param supportservices_preliminary
	 */
	public final void setSupportServices_Preliminary(com.mendix.systemwideinterfaces.core.IContext context, requestforpreliminaryregistrationofafacility_hospital.proxies.Preliminary supportservices_preliminary)
	{
		if (supportservices_preliminary == null)
			getMendixObject().setValue(context, MemberNames.SupportServices_Preliminary.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.SupportServices_Preliminary.toString(), supportservices_preliminary.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return supportServicesMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final requestforpreliminaryregistrationofafacility_hospital.proxies.SupportServices that = (requestforpreliminaryregistrationofafacility_hospital.proxies.SupportServices) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "RequestforPreliminaryRegistrationofaFacility_Hospital.SupportServices";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
