// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package ded_sevice.proxies;

public class DED
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject dEDMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DED_sevice.DED";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		DED_License_no("DED_License_no"),
		AddressInEnglish("AddressInEnglish"),
		AddressInArabic("AddressInArabic"),
		Building_Type("Building_Type"),
		Building_Construction_Type("Building_Construction_Type"),
		FAX("FAX"),
		PO_Box("PO_Box"),
		Email("Email"),
		Telephone("Telephone"),
		DED_ExpiryDate("DED_ExpiryDate"),
		FacilityNameArabic("FacilityNameArabic"),
		FacilityNameEnglish("FacilityNameEnglish"),
		DED_Activities("DED_sevice.DED_Activities");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DED(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "DED_sevice.DED"));
	}

	protected DED(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject dEDMendixObject)
	{
		if (dEDMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("DED_sevice.DED", dEDMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a DED_sevice.DED");

		this.dEDMendixObject = dEDMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'DED.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static ded_sevice.proxies.DED initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return ded_sevice.proxies.DED.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static ded_sevice.proxies.DED initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new ded_sevice.proxies.DED(context, mendixObject);
	}

	public static ded_sevice.proxies.DED load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return ded_sevice.proxies.DED.initialize(context, mendixObject);
	}

	public static java.util.List<ded_sevice.proxies.DED> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<ded_sevice.proxies.DED> result = new java.util.ArrayList<ded_sevice.proxies.DED>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//DED_sevice.DED" + xpathConstraint))
			result.add(ded_sevice.proxies.DED.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of DED_License_no
	 */
	public final java.lang.String getDED_License_no()
	{
		return getDED_License_no(getContext());
	}

	/**
	 * @param context
	 * @return value of DED_License_no
	 */
	public final java.lang.String getDED_License_no(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DED_License_no.toString());
	}

	/**
	 * Set value of DED_License_no
	 * @param ded_license_no
	 */
	public final void setDED_License_no(java.lang.String ded_license_no)
	{
		setDED_License_no(getContext(), ded_license_no);
	}

	/**
	 * Set value of DED_License_no
	 * @param context
	 * @param ded_license_no
	 */
	public final void setDED_License_no(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String ded_license_no)
	{
		getMendixObject().setValue(context, MemberNames.DED_License_no.toString(), ded_license_no);
	}

	/**
	 * @return value of AddressInEnglish
	 */
	public final java.lang.String getAddressInEnglish()
	{
		return getAddressInEnglish(getContext());
	}

	/**
	 * @param context
	 * @return value of AddressInEnglish
	 */
	public final java.lang.String getAddressInEnglish(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AddressInEnglish.toString());
	}

	/**
	 * Set value of AddressInEnglish
	 * @param addressinenglish
	 */
	public final void setAddressInEnglish(java.lang.String addressinenglish)
	{
		setAddressInEnglish(getContext(), addressinenglish);
	}

	/**
	 * Set value of AddressInEnglish
	 * @param context
	 * @param addressinenglish
	 */
	public final void setAddressInEnglish(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String addressinenglish)
	{
		getMendixObject().setValue(context, MemberNames.AddressInEnglish.toString(), addressinenglish);
	}

	/**
	 * @return value of AddressInArabic
	 */
	public final java.lang.String getAddressInArabic()
	{
		return getAddressInArabic(getContext());
	}

	/**
	 * @param context
	 * @return value of AddressInArabic
	 */
	public final java.lang.String getAddressInArabic(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AddressInArabic.toString());
	}

	/**
	 * Set value of AddressInArabic
	 * @param addressinarabic
	 */
	public final void setAddressInArabic(java.lang.String addressinarabic)
	{
		setAddressInArabic(getContext(), addressinarabic);
	}

	/**
	 * Set value of AddressInArabic
	 * @param context
	 * @param addressinarabic
	 */
	public final void setAddressInArabic(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String addressinarabic)
	{
		getMendixObject().setValue(context, MemberNames.AddressInArabic.toString(), addressinarabic);
	}

	/**
	 * Set value of Building_Type
	 * @param building_type
	 */
	public final ded_sevice.proxies.Enum_Building_type getBuilding_Type()
	{
		return getBuilding_Type(getContext());
	}

	/**
	 * @param context
	 * @return value of Building_Type
	 */
	public final ded_sevice.proxies.Enum_Building_type getBuilding_Type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Building_Type.toString());
		if (obj == null)
			return null;

		return ded_sevice.proxies.Enum_Building_type.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Building_Type
	 * @param building_type
	 */
	public final void setBuilding_Type(ded_sevice.proxies.Enum_Building_type building_type)
	{
		setBuilding_Type(getContext(), building_type);
	}

	/**
	 * Set value of Building_Type
	 * @param context
	 * @param building_type
	 */
	public final void setBuilding_Type(com.mendix.systemwideinterfaces.core.IContext context, ded_sevice.proxies.Enum_Building_type building_type)
	{
		if (building_type != null)
			getMendixObject().setValue(context, MemberNames.Building_Type.toString(), building_type.toString());
		else
			getMendixObject().setValue(context, MemberNames.Building_Type.toString(), null);
	}

	/**
	 * Set value of Building_Construction_Type
	 * @param building_construction_type
	 */
	public final ded_sevice.proxies.Enum_Building_construction_Type getBuilding_Construction_Type()
	{
		return getBuilding_Construction_Type(getContext());
	}

	/**
	 * @param context
	 * @return value of Building_Construction_Type
	 */
	public final ded_sevice.proxies.Enum_Building_construction_Type getBuilding_Construction_Type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Building_Construction_Type.toString());
		if (obj == null)
			return null;

		return ded_sevice.proxies.Enum_Building_construction_Type.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Building_Construction_Type
	 * @param building_construction_type
	 */
	public final void setBuilding_Construction_Type(ded_sevice.proxies.Enum_Building_construction_Type building_construction_type)
	{
		setBuilding_Construction_Type(getContext(), building_construction_type);
	}

	/**
	 * Set value of Building_Construction_Type
	 * @param context
	 * @param building_construction_type
	 */
	public final void setBuilding_Construction_Type(com.mendix.systemwideinterfaces.core.IContext context, ded_sevice.proxies.Enum_Building_construction_Type building_construction_type)
	{
		if (building_construction_type != null)
			getMendixObject().setValue(context, MemberNames.Building_Construction_Type.toString(), building_construction_type.toString());
		else
			getMendixObject().setValue(context, MemberNames.Building_Construction_Type.toString(), null);
	}

	/**
	 * @return value of FAX
	 */
	public final java.lang.Integer getFAX()
	{
		return getFAX(getContext());
	}

	/**
	 * @param context
	 * @return value of FAX
	 */
	public final java.lang.Integer getFAX(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.FAX.toString());
	}

	/**
	 * Set value of FAX
	 * @param fax
	 */
	public final void setFAX(java.lang.Integer fax)
	{
		setFAX(getContext(), fax);
	}

	/**
	 * Set value of FAX
	 * @param context
	 * @param fax
	 */
	public final void setFAX(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer fax)
	{
		getMendixObject().setValue(context, MemberNames.FAX.toString(), fax);
	}

	/**
	 * @return value of PO_Box
	 */
	public final java.lang.Integer getPO_Box()
	{
		return getPO_Box(getContext());
	}

	/**
	 * @param context
	 * @return value of PO_Box
	 */
	public final java.lang.Integer getPO_Box(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.PO_Box.toString());
	}

	/**
	 * Set value of PO_Box
	 * @param po_box
	 */
	public final void setPO_Box(java.lang.Integer po_box)
	{
		setPO_Box(getContext(), po_box);
	}

	/**
	 * Set value of PO_Box
	 * @param context
	 * @param po_box
	 */
	public final void setPO_Box(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer po_box)
	{
		getMendixObject().setValue(context, MemberNames.PO_Box.toString(), po_box);
	}

	/**
	 * @return value of Email
	 */
	public final java.lang.String getEmail()
	{
		return getEmail(getContext());
	}

	/**
	 * @param context
	 * @return value of Email
	 */
	public final java.lang.String getEmail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Email.toString());
	}

	/**
	 * Set value of Email
	 * @param email
	 */
	public final void setEmail(java.lang.String email)
	{
		setEmail(getContext(), email);
	}

	/**
	 * Set value of Email
	 * @param context
	 * @param email
	 */
	public final void setEmail(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String email)
	{
		getMendixObject().setValue(context, MemberNames.Email.toString(), email);
	}

	/**
	 * @return value of Telephone
	 */
	public final java.lang.Integer getTelephone()
	{
		return getTelephone(getContext());
	}

	/**
	 * @param context
	 * @return value of Telephone
	 */
	public final java.lang.Integer getTelephone(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Telephone.toString());
	}

	/**
	 * Set value of Telephone
	 * @param telephone
	 */
	public final void setTelephone(java.lang.Integer telephone)
	{
		setTelephone(getContext(), telephone);
	}

	/**
	 * Set value of Telephone
	 * @param context
	 * @param telephone
	 */
	public final void setTelephone(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer telephone)
	{
		getMendixObject().setValue(context, MemberNames.Telephone.toString(), telephone);
	}

	/**
	 * @return value of DED_ExpiryDate
	 */
	public final java.util.Date getDED_ExpiryDate()
	{
		return getDED_ExpiryDate(getContext());
	}

	/**
	 * @param context
	 * @return value of DED_ExpiryDate
	 */
	public final java.util.Date getDED_ExpiryDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DED_ExpiryDate.toString());
	}

	/**
	 * Set value of DED_ExpiryDate
	 * @param ded_expirydate
	 */
	public final void setDED_ExpiryDate(java.util.Date ded_expirydate)
	{
		setDED_ExpiryDate(getContext(), ded_expirydate);
	}

	/**
	 * Set value of DED_ExpiryDate
	 * @param context
	 * @param ded_expirydate
	 */
	public final void setDED_ExpiryDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date ded_expirydate)
	{
		getMendixObject().setValue(context, MemberNames.DED_ExpiryDate.toString(), ded_expirydate);
	}

	/**
	 * @return value of FacilityNameArabic
	 */
	public final java.lang.String getFacilityNameArabic()
	{
		return getFacilityNameArabic(getContext());
	}

	/**
	 * @param context
	 * @return value of FacilityNameArabic
	 */
	public final java.lang.String getFacilityNameArabic(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FacilityNameArabic.toString());
	}

	/**
	 * Set value of FacilityNameArabic
	 * @param facilitynamearabic
	 */
	public final void setFacilityNameArabic(java.lang.String facilitynamearabic)
	{
		setFacilityNameArabic(getContext(), facilitynamearabic);
	}

	/**
	 * Set value of FacilityNameArabic
	 * @param context
	 * @param facilitynamearabic
	 */
	public final void setFacilityNameArabic(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String facilitynamearabic)
	{
		getMendixObject().setValue(context, MemberNames.FacilityNameArabic.toString(), facilitynamearabic);
	}

	/**
	 * @return value of FacilityNameEnglish
	 */
	public final java.lang.String getFacilityNameEnglish()
	{
		return getFacilityNameEnglish(getContext());
	}

	/**
	 * @param context
	 * @return value of FacilityNameEnglish
	 */
	public final java.lang.String getFacilityNameEnglish(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FacilityNameEnglish.toString());
	}

	/**
	 * Set value of FacilityNameEnglish
	 * @param facilitynameenglish
	 */
	public final void setFacilityNameEnglish(java.lang.String facilitynameenglish)
	{
		setFacilityNameEnglish(getContext(), facilitynameenglish);
	}

	/**
	 * Set value of FacilityNameEnglish
	 * @param context
	 * @param facilitynameenglish
	 */
	public final void setFacilityNameEnglish(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String facilitynameenglish)
	{
		getMendixObject().setValue(context, MemberNames.FacilityNameEnglish.toString(), facilitynameenglish);
	}

	/**
	 * @return value of DED_Activities
	 */
	public final ded_sevice.proxies.Activities getDED_Activities() throws com.mendix.core.CoreException
	{
		return getDED_Activities(getContext());
	}

	/**
	 * @param context
	 * @return value of DED_Activities
	 */
	public final ded_sevice.proxies.Activities getDED_Activities(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		ded_sevice.proxies.Activities result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DED_Activities.toString());
		if (identifier != null)
			result = ded_sevice.proxies.Activities.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DED_Activities
	 * @param ded_activities
	 */
	public final void setDED_Activities(ded_sevice.proxies.Activities ded_activities)
	{
		setDED_Activities(getContext(), ded_activities);
	}

	/**
	 * Set value of DED_Activities
	 * @param context
	 * @param ded_activities
	 */
	public final void setDED_Activities(com.mendix.systemwideinterfaces.core.IContext context, ded_sevice.proxies.Activities ded_activities)
	{
		if (ded_activities == null)
			getMendixObject().setValue(context, MemberNames.DED_Activities.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DED_Activities.toString(), ded_activities.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return dEDMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final ded_sevice.proxies.DED that = (ded_sevice.proxies.DED) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "DED_sevice.DED";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
