// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package audittrail.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the AuditTrail module
	public static boolean bCo_AudittrailSuperClass(IContext context, audittrail.proxies.AudittrailSuperClass _audittrailSuperClass)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("AudittrailSuperClass", _audittrailSuperClass == null ? null : _audittrailSuperClass.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("AuditTrail.BCo_AudittrailSuperClass").withParams(params).execute(context);
	}
	public static boolean bDe_AudittrailSuperClass(IContext context, audittrail.proxies.AudittrailSuperClass _audittrailSuperClass)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("AudittrailSuperClass", _audittrailSuperClass == null ? null : _audittrailSuperClass.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("AuditTrail.BDe_AudittrailSuperClass").withParams(params).execute(context);
	}
	public static java.lang.String cA_CalculatedNewValue(IContext context, audittrail.proxies.LogLine _logLine)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("LogLine", _logLine == null ? null : _logLine.getMendixObject());
		return (java.lang.String) Core.microflowCall("AuditTrail.CA_CalculatedNewValue").withParams(params).execute(context);
	}
	public static java.lang.String cA_CalculatedOldValue(IContext context, audittrail.proxies.LogLine _logLine)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("LogLine", _logLine == null ? null : _logLine.getMendixObject());
		return (java.lang.String) Core.microflowCall("AuditTrail.CA_CalculatedOldValue").withParams(params).execute(context);
	}
	public static java.lang.String cA_Diff(IContext context, audittrail.proxies.LogLine _logLine)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("LogLine", _logLine == null ? null : _logLine.getMendixObject());
		return (java.lang.String) Core.microflowCall("AuditTrail.CA_Diff").withParams(params).execute(context);
	}
	public static java.lang.String calc_LogDescription(IContext context, audittrail.proxies.Log _log)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Log", _log == null ? null : _log.getMendixObject());
		return (java.lang.String) Core.microflowCall("AuditTrail.Calc_LogDescription").withParams(params).execute(context);
	}
	public static audittrail.proxies.UIToggle dSO_ToggleUI(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("AuditTrail.DSO_ToggleUI").withParams(params).execute(context);
		return result == null ? null : audittrail.proxies.UIToggle.initialize(context, result);
	}
	public static java.lang.String new_value_password(IContext context, audittrail.proxies.LogLine _logLine)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("LogLine", _logLine == null ? null : _logLine.getMendixObject());
		return (java.lang.String) Core.microflowCall("AuditTrail.new_value_password").withParams(params).execute(context);
	}
	public static void oCl_ToggleUI(IContext context, audittrail.proxies.UIToggle _uIToggle)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("UIToggle", _uIToggle == null ? null : _uIToggle.getMendixObject());
		Core.microflowCall("AuditTrail.OCl_ToggleUI").withParams(params).execute(context);
	}
	public static java.lang.String old_value_password(IContext context, audittrail.proxies.LogLine _logLine)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("LogLine", _logLine == null ? null : _logLine.getMendixObject());
		return (java.lang.String) Core.microflowCall("AuditTrail.Old_value_password").withParams(params).execute(context);
	}
}