// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package administration.proxies;

public class Account extends system.proxies.User
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Administration.Account";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FullName("FullName"),
		ArabicFullName("ArabicFullName"),
		Email("Email"),
		IsLocalUser("IsLocalUser"),
		IsHealthcareProfessional("IsHealthcareProfessional"),
		Name("Name"),
		Password("Password"),
		LastLogin("LastLogin"),
		Blocked("Blocked"),
		Active("Active"),
		FailedLogins("FailedLogins"),
		WebServiceUser("WebServiceUser"),
		IsAnonymous("IsAnonymous"),
		Account_ProfileImage("Administration.Account_ProfileImage"),
		Account_FacilityAdmin("Administration.Account_FacilityAdmin"),
		Account_Profile("Administration.Account_Profile"),
		Account_Log_2("Administration.Account_Log_2"),
		Account_Signature("Administration.Account_Signature"),
		BirthNotification_ApproverAccount("MyFirstModule.BirthNotification_ApproverAccount"),
		Circulars_Account_2("MyFirstModule.Circulars_Account_2"),
		Preliminary_Account("RequestforPreliminaryRegistrationofaFacility_Hospital.Preliminary_Account"),
		UserRoles("System.UserRoles"),
		User_Language("System.User_Language"),
		User_TimeZone("System.User_TimeZone");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Account(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Administration.Account"));
	}

	protected Account(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject accountMendixObject)
	{
		super(context, accountMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("Administration.Account", accountMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Administration.Account");
	}

	/**
	 * @deprecated Use 'Account.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static administration.proxies.Account initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return administration.proxies.Account.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static administration.proxies.Account initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new administration.proxies.Account(context, mendixObject);
	}

	public static administration.proxies.Account load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return administration.proxies.Account.initialize(context, mendixObject);
	}

	public static java.util.List<administration.proxies.Account> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<administration.proxies.Account> result = new java.util.ArrayList<administration.proxies.Account>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Administration.Account" + xpathConstraint))
			result.add(administration.proxies.Account.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of FullName
	 */
	public final java.lang.String getFullName()
	{
		return getFullName(getContext());
	}

	/**
	 * @param context
	 * @return value of FullName
	 */
	public final java.lang.String getFullName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FullName.toString());
	}

	/**
	 * Set value of FullName
	 * @param fullname
	 */
	public final void setFullName(java.lang.String fullname)
	{
		setFullName(getContext(), fullname);
	}

	/**
	 * Set value of FullName
	 * @param context
	 * @param fullname
	 */
	public final void setFullName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String fullname)
	{
		getMendixObject().setValue(context, MemberNames.FullName.toString(), fullname);
	}

	/**
	 * @return value of ArabicFullName
	 */
	public final java.lang.String getArabicFullName()
	{
		return getArabicFullName(getContext());
	}

	/**
	 * @param context
	 * @return value of ArabicFullName
	 */
	public final java.lang.String getArabicFullName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ArabicFullName.toString());
	}

	/**
	 * Set value of ArabicFullName
	 * @param arabicfullname
	 */
	public final void setArabicFullName(java.lang.String arabicfullname)
	{
		setArabicFullName(getContext(), arabicfullname);
	}

	/**
	 * Set value of ArabicFullName
	 * @param context
	 * @param arabicfullname
	 */
	public final void setArabicFullName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String arabicfullname)
	{
		getMendixObject().setValue(context, MemberNames.ArabicFullName.toString(), arabicfullname);
	}

	/**
	 * @return value of Email
	 */
	public final java.lang.String getEmail()
	{
		return getEmail(getContext());
	}

	/**
	 * @param context
	 * @return value of Email
	 */
	public final java.lang.String getEmail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Email.toString());
	}

	/**
	 * Set value of Email
	 * @param email
	 */
	public final void setEmail(java.lang.String email)
	{
		setEmail(getContext(), email);
	}

	/**
	 * Set value of Email
	 * @param context
	 * @param email
	 */
	public final void setEmail(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String email)
	{
		getMendixObject().setValue(context, MemberNames.Email.toString(), email);
	}

	/**
	 * @return value of IsLocalUser
	 */
	public final java.lang.Boolean getIsLocalUser()
	{
		return getIsLocalUser(getContext());
	}

	/**
	 * @param context
	 * @return value of IsLocalUser
	 */
	public final java.lang.Boolean getIsLocalUser(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsLocalUser.toString());
	}

	/**
	 * Set value of IsLocalUser
	 * @param islocaluser
	 */
	public final void setIsLocalUser(java.lang.Boolean islocaluser)
	{
		setIsLocalUser(getContext(), islocaluser);
	}

	/**
	 * Set value of IsLocalUser
	 * @param context
	 * @param islocaluser
	 */
	public final void setIsLocalUser(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean islocaluser)
	{
		getMendixObject().setValue(context, MemberNames.IsLocalUser.toString(), islocaluser);
	}

	/**
	 * @return value of IsHealthcareProfessional
	 */
	public final java.lang.Boolean getIsHealthcareProfessional()
	{
		return getIsHealthcareProfessional(getContext());
	}

	/**
	 * @param context
	 * @return value of IsHealthcareProfessional
	 */
	public final java.lang.Boolean getIsHealthcareProfessional(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsHealthcareProfessional.toString());
	}

	/**
	 * Set value of IsHealthcareProfessional
	 * @param ishealthcareprofessional
	 */
	public final void setIsHealthcareProfessional(java.lang.Boolean ishealthcareprofessional)
	{
		setIsHealthcareProfessional(getContext(), ishealthcareprofessional);
	}

	/**
	 * Set value of IsHealthcareProfessional
	 * @param context
	 * @param ishealthcareprofessional
	 */
	public final void setIsHealthcareProfessional(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean ishealthcareprofessional)
	{
		getMendixObject().setValue(context, MemberNames.IsHealthcareProfessional.toString(), ishealthcareprofessional);
	}

	/**
	 * @return value of Account_ProfileImage
	 */
	public final administration.proxies.ProfileImage getAccount_ProfileImage() throws com.mendix.core.CoreException
	{
		return getAccount_ProfileImage(getContext());
	}

	/**
	 * @param context
	 * @return value of Account_ProfileImage
	 */
	public final administration.proxies.ProfileImage getAccount_ProfileImage(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		administration.proxies.ProfileImage result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Account_ProfileImage.toString());
		if (identifier != null)
			result = administration.proxies.ProfileImage.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Account_ProfileImage
	 * @param account_profileimage
	 */
	public final void setAccount_ProfileImage(administration.proxies.ProfileImage account_profileimage)
	{
		setAccount_ProfileImage(getContext(), account_profileimage);
	}

	/**
	 * Set value of Account_ProfileImage
	 * @param context
	 * @param account_profileimage
	 */
	public final void setAccount_ProfileImage(com.mendix.systemwideinterfaces.core.IContext context, administration.proxies.ProfileImage account_profileimage)
	{
		if (account_profileimage == null)
			getMendixObject().setValue(context, MemberNames.Account_ProfileImage.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Account_ProfileImage.toString(), account_profileimage.getMendixObject().getId());
	}

	/**
	 * @return value of Account_FacilityAdmin
	 */
	public final administration.proxies.Account getAccount_FacilityAdmin() throws com.mendix.core.CoreException
	{
		return getAccount_FacilityAdmin(getContext());
	}

	/**
	 * @param context
	 * @return value of Account_FacilityAdmin
	 */
	public final administration.proxies.Account getAccount_FacilityAdmin(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		administration.proxies.Account result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Account_FacilityAdmin.toString());
		if (identifier != null)
			result = administration.proxies.Account.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Account_FacilityAdmin
	 * @param account_facilityadmin
	 */
	public final void setAccount_FacilityAdmin(administration.proxies.Account account_facilityadmin)
	{
		setAccount_FacilityAdmin(getContext(), account_facilityadmin);
	}

	/**
	 * Set value of Account_FacilityAdmin
	 * @param context
	 * @param account_facilityadmin
	 */
	public final void setAccount_FacilityAdmin(com.mendix.systemwideinterfaces.core.IContext context, administration.proxies.Account account_facilityadmin)
	{
		if (account_facilityadmin == null)
			getMendixObject().setValue(context, MemberNames.Account_FacilityAdmin.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Account_FacilityAdmin.toString(), account_facilityadmin.getMendixObject().getId());
	}

	/**
	 * @return value of Account_Profile
	 */
	public final myfirstmodule.proxies.Profile getAccount_Profile() throws com.mendix.core.CoreException
	{
		return getAccount_Profile(getContext());
	}

	/**
	 * @param context
	 * @return value of Account_Profile
	 */
	public final myfirstmodule.proxies.Profile getAccount_Profile(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Profile result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Account_Profile.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Profile.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Account_Profile
	 * @param account_profile
	 */
	public final void setAccount_Profile(myfirstmodule.proxies.Profile account_profile)
	{
		setAccount_Profile(getContext(), account_profile);
	}

	/**
	 * Set value of Account_Profile
	 * @param context
	 * @param account_profile
	 */
	public final void setAccount_Profile(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Profile account_profile)
	{
		if (account_profile == null)
			getMendixObject().setValue(context, MemberNames.Account_Profile.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Account_Profile.toString(), account_profile.getMendixObject().getId());
	}

	/**
	 * @return value of Account_Log_2
	 */
	public final java.util.List<audittrail.proxies.Log> getAccount_Log_2() throws com.mendix.core.CoreException
	{
		return getAccount_Log_2(getContext());
	}

	/**
	 * @param context
	 * @return value of Account_Log_2
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<audittrail.proxies.Log> getAccount_Log_2(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<audittrail.proxies.Log> result = new java.util.ArrayList<audittrail.proxies.Log>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.Account_Log_2.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(audittrail.proxies.Log.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of Account_Log_2
	 * @param account_log_2
	 */
	public final void setAccount_Log_2(java.util.List<audittrail.proxies.Log> account_log_2)
	{
		setAccount_Log_2(getContext(), account_log_2);
	}

	/**
	 * Set value of Account_Log_2
	 * @param context
	 * @param account_log_2
	 */
	public final void setAccount_Log_2(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<audittrail.proxies.Log> account_log_2)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (audittrail.proxies.Log proxyObject : account_log_2)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.Account_Log_2.toString(), identifiers);
	}

	/**
	 * @return value of Account_Signature
	 */
	public final myfirstmodule.proxies.Signature getAccount_Signature() throws com.mendix.core.CoreException
	{
		return getAccount_Signature(getContext());
	}

	/**
	 * @param context
	 * @return value of Account_Signature
	 */
	public final myfirstmodule.proxies.Signature getAccount_Signature(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Signature result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Account_Signature.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Signature.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Account_Signature
	 * @param account_signature
	 */
	public final void setAccount_Signature(myfirstmodule.proxies.Signature account_signature)
	{
		setAccount_Signature(getContext(), account_signature);
	}

	/**
	 * Set value of Account_Signature
	 * @param context
	 * @param account_signature
	 */
	public final void setAccount_Signature(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Signature account_signature)
	{
		if (account_signature == null)
			getMendixObject().setValue(context, MemberNames.Account_Signature.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Account_Signature.toString(), account_signature.getMendixObject().getId());
	}

	/**
	 * @return value of BirthNotification_ApproverAccount
	 */
	public final java.util.List<myfirstmodule.proxies.BirthNotification> getBirthNotification_ApproverAccount() throws com.mendix.core.CoreException
	{
		return getBirthNotification_ApproverAccount(getContext());
	}

	/**
	 * @param context
	 * @return value of BirthNotification_ApproverAccount
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<myfirstmodule.proxies.BirthNotification> getBirthNotification_ApproverAccount(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.BirthNotification> result = new java.util.ArrayList<myfirstmodule.proxies.BirthNotification>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.BirthNotification_ApproverAccount.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(myfirstmodule.proxies.BirthNotification.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of BirthNotification_ApproverAccount
	 * @param birthnotification_approveraccount
	 */
	public final void setBirthNotification_ApproverAccount(java.util.List<myfirstmodule.proxies.BirthNotification> birthnotification_approveraccount)
	{
		setBirthNotification_ApproverAccount(getContext(), birthnotification_approveraccount);
	}

	/**
	 * Set value of BirthNotification_ApproverAccount
	 * @param context
	 * @param birthnotification_approveraccount
	 */
	public final void setBirthNotification_ApproverAccount(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<myfirstmodule.proxies.BirthNotification> birthnotification_approveraccount)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (myfirstmodule.proxies.BirthNotification proxyObject : birthnotification_approveraccount)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.BirthNotification_ApproverAccount.toString(), identifiers);
	}

	/**
	 * @return value of Circulars_Account_2
	 */
	public final java.util.List<myfirstmodule.proxies.Circulars> getCirculars_Account_2() throws com.mendix.core.CoreException
	{
		return getCirculars_Account_2(getContext());
	}

	/**
	 * @param context
	 * @return value of Circulars_Account_2
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<myfirstmodule.proxies.Circulars> getCirculars_Account_2(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.Circulars> result = new java.util.ArrayList<myfirstmodule.proxies.Circulars>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.Circulars_Account_2.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(myfirstmodule.proxies.Circulars.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of Circulars_Account_2
	 * @param circulars_account_2
	 */
	public final void setCirculars_Account_2(java.util.List<myfirstmodule.proxies.Circulars> circulars_account_2)
	{
		setCirculars_Account_2(getContext(), circulars_account_2);
	}

	/**
	 * Set value of Circulars_Account_2
	 * @param context
	 * @param circulars_account_2
	 */
	public final void setCirculars_Account_2(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<myfirstmodule.proxies.Circulars> circulars_account_2)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (myfirstmodule.proxies.Circulars proxyObject : circulars_account_2)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.Circulars_Account_2.toString(), identifiers);
	}

	/**
	 * @return value of Preliminary_Account
	 */
	public final requestforpreliminaryregistrationofafacility_hospital.proxies.Preliminary getPreliminary_Account() throws com.mendix.core.CoreException
	{
		return getPreliminary_Account(getContext());
	}

	/**
	 * @param context
	 * @return value of Preliminary_Account
	 */
	public final requestforpreliminaryregistrationofafacility_hospital.proxies.Preliminary getPreliminary_Account(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		requestforpreliminaryregistrationofafacility_hospital.proxies.Preliminary result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Preliminary_Account.toString());
		if (identifier != null)
			result = requestforpreliminaryregistrationofafacility_hospital.proxies.Preliminary.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Preliminary_Account
	 * @param preliminary_account
	 */
	public final void setPreliminary_Account(requestforpreliminaryregistrationofafacility_hospital.proxies.Preliminary preliminary_account)
	{
		setPreliminary_Account(getContext(), preliminary_account);
	}

	/**
	 * Set value of Preliminary_Account
	 * @param context
	 * @param preliminary_account
	 */
	public final void setPreliminary_Account(com.mendix.systemwideinterfaces.core.IContext context, requestforpreliminaryregistrationofafacility_hospital.proxies.Preliminary preliminary_account)
	{
		if (preliminary_account == null)
			getMendixObject().setValue(context, MemberNames.Preliminary_Account.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Preliminary_Account.toString(), preliminary_account.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final administration.proxies.Account that = (administration.proxies.Account) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Administration.Account";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
