// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the MyFirstModule module

	public static java.lang.String getDataSetID_Certificate()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("MyFirstModule.DataSetID_Certificate");
	}

	public static java.lang.String getDataSetID_Notification()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("MyFirstModule.DataSetID_Notification");
	}

	public static java.lang.String getEmbedURL_Notification()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("MyFirstModule.EmbedURL_Notification");
	}

	public static java.lang.String getGroupID()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("MyFirstModule.GroupID");
	}

	public static java.lang.String getReportID_Certificate()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("MyFirstModule.ReportID_Certificate");
	}

	public static java.lang.String getReportID_Notification()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("MyFirstModule.ReportID_Notification");
	}
}