// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package audittrail.proxies;

public enum TypeOfReferenceLog
{
	Added(new java.lang.String[][] { new java.lang.String[] { "en_US", "Added" }, new java.lang.String[] { "ar_AE", "تمت الإضافة" } }),
	No_Change(new java.lang.String[][] { new java.lang.String[] { "en_US", "Unchanged" }, new java.lang.String[] { "ar_AE", "دون تغيير" } }),
	Deleted(new java.lang.String[][] { new java.lang.String[] { "en_US", "Deleted" }, new java.lang.String[] { "ar_AE", "تم المسح" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private TypeOfReferenceLog(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
