// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package emiratesservice.proxies;

public class BirthCerticate
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject birthCerticateMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EmiratesService.BirthCerticate";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		TypeOfIssue("TypeOfIssue"),
		NoOfArabicCopies("NoOfArabicCopies"),
		NoOfEnglishCopies("NoOfEnglishCopies"),
		DeliverThroughEmiratesPost("DeliverThroughEmiratesPost"),
		BirthCerticate_Root("EmiratesService.BirthCerticate_Root");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public BirthCerticate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "EmiratesService.BirthCerticate"));
	}

	protected BirthCerticate(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject birthCerticateMendixObject)
	{
		if (birthCerticateMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("EmiratesService.BirthCerticate", birthCerticateMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a EmiratesService.BirthCerticate");

		this.birthCerticateMendixObject = birthCerticateMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'BirthCerticate.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static emiratesservice.proxies.BirthCerticate initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return emiratesservice.proxies.BirthCerticate.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static emiratesservice.proxies.BirthCerticate initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new emiratesservice.proxies.BirthCerticate(context, mendixObject);
	}

	public static emiratesservice.proxies.BirthCerticate load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return emiratesservice.proxies.BirthCerticate.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of TypeOfIssue
	 */
	public final java.lang.String getTypeOfIssue()
	{
		return getTypeOfIssue(getContext());
	}

	/**
	 * @param context
	 * @return value of TypeOfIssue
	 */
	public final java.lang.String getTypeOfIssue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TypeOfIssue.toString());
	}

	/**
	 * Set value of TypeOfIssue
	 * @param typeofissue
	 */
	public final void setTypeOfIssue(java.lang.String typeofissue)
	{
		setTypeOfIssue(getContext(), typeofissue);
	}

	/**
	 * Set value of TypeOfIssue
	 * @param context
	 * @param typeofissue
	 */
	public final void setTypeOfIssue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String typeofissue)
	{
		getMendixObject().setValue(context, MemberNames.TypeOfIssue.toString(), typeofissue);
	}

	/**
	 * @return value of NoOfArabicCopies
	 */
	public final java.lang.Integer getNoOfArabicCopies()
	{
		return getNoOfArabicCopies(getContext());
	}

	/**
	 * @param context
	 * @return value of NoOfArabicCopies
	 */
	public final java.lang.Integer getNoOfArabicCopies(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.NoOfArabicCopies.toString());
	}

	/**
	 * Set value of NoOfArabicCopies
	 * @param noofarabiccopies
	 */
	public final void setNoOfArabicCopies(java.lang.Integer noofarabiccopies)
	{
		setNoOfArabicCopies(getContext(), noofarabiccopies);
	}

	/**
	 * Set value of NoOfArabicCopies
	 * @param context
	 * @param noofarabiccopies
	 */
	public final void setNoOfArabicCopies(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer noofarabiccopies)
	{
		getMendixObject().setValue(context, MemberNames.NoOfArabicCopies.toString(), noofarabiccopies);
	}

	/**
	 * @return value of NoOfEnglishCopies
	 */
	public final java.lang.Integer getNoOfEnglishCopies()
	{
		return getNoOfEnglishCopies(getContext());
	}

	/**
	 * @param context
	 * @return value of NoOfEnglishCopies
	 */
	public final java.lang.Integer getNoOfEnglishCopies(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.NoOfEnglishCopies.toString());
	}

	/**
	 * Set value of NoOfEnglishCopies
	 * @param noofenglishcopies
	 */
	public final void setNoOfEnglishCopies(java.lang.Integer noofenglishcopies)
	{
		setNoOfEnglishCopies(getContext(), noofenglishcopies);
	}

	/**
	 * Set value of NoOfEnglishCopies
	 * @param context
	 * @param noofenglishcopies
	 */
	public final void setNoOfEnglishCopies(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer noofenglishcopies)
	{
		getMendixObject().setValue(context, MemberNames.NoOfEnglishCopies.toString(), noofenglishcopies);
	}

	/**
	 * @return value of DeliverThroughEmiratesPost
	 */
	public final java.lang.Boolean getDeliverThroughEmiratesPost()
	{
		return getDeliverThroughEmiratesPost(getContext());
	}

	/**
	 * @param context
	 * @return value of DeliverThroughEmiratesPost
	 */
	public final java.lang.Boolean getDeliverThroughEmiratesPost(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.DeliverThroughEmiratesPost.toString());
	}

	/**
	 * Set value of DeliverThroughEmiratesPost
	 * @param deliverthroughemiratespost
	 */
	public final void setDeliverThroughEmiratesPost(java.lang.Boolean deliverthroughemiratespost)
	{
		setDeliverThroughEmiratesPost(getContext(), deliverthroughemiratespost);
	}

	/**
	 * Set value of DeliverThroughEmiratesPost
	 * @param context
	 * @param deliverthroughemiratespost
	 */
	public final void setDeliverThroughEmiratesPost(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean deliverthroughemiratespost)
	{
		getMendixObject().setValue(context, MemberNames.DeliverThroughEmiratesPost.toString(), deliverthroughemiratespost);
	}

	/**
	 * @return value of BirthCerticate_Root
	 */
	public final emiratesservice.proxies.Root getBirthCerticate_Root() throws com.mendix.core.CoreException
	{
		return getBirthCerticate_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of BirthCerticate_Root
	 */
	public final emiratesservice.proxies.Root getBirthCerticate_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		emiratesservice.proxies.Root result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.BirthCerticate_Root.toString());
		if (identifier != null)
			result = emiratesservice.proxies.Root.load(context, identifier);
		return result;
	}

	/**
	 * Set value of BirthCerticate_Root
	 * @param birthcerticate_root
	 */
	public final void setBirthCerticate_Root(emiratesservice.proxies.Root birthcerticate_root)
	{
		setBirthCerticate_Root(getContext(), birthcerticate_root);
	}

	/**
	 * Set value of BirthCerticate_Root
	 * @param context
	 * @param birthcerticate_root
	 */
	public final void setBirthCerticate_Root(com.mendix.systemwideinterfaces.core.IContext context, emiratesservice.proxies.Root birthcerticate_root)
	{
		if (birthcerticate_root == null)
			getMendixObject().setValue(context, MemberNames.BirthCerticate_Root.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.BirthCerticate_Root.toString(), birthcerticate_root.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return birthCerticateMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final emiratesservice.proxies.BirthCerticate that = (emiratesservice.proxies.BirthCerticate) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "EmiratesService.BirthCerticate";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
