// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package emiratesservice.proxies;

public enum ENUM_TYPEOFENUMERATION
{
	Nationality(new java.lang.String[][] { new java.lang.String[] { "en_US", "Nationality" }, new java.lang.String[] { "ar_AE", "الجنسية" } }),
	NotificationType(new java.lang.String[][] { new java.lang.String[] { "en_US", "NotificationType" }, new java.lang.String[] { "ar_AE", "نوع الإشعار" } }),
	PlaceOfBirth(new java.lang.String[][] { new java.lang.String[] { "en_US", "PlaceOfBirth" }, new java.lang.String[] { "ar_AE", "مكان الميلاد" } }),
	Gender(new java.lang.String[][] { new java.lang.String[] { "en_US", "Gender" }, new java.lang.String[] { "ar_AE", "جنس" } }),
	MartialStatus(new java.lang.String[][] { new java.lang.String[] { "en_US", "MartialStatus" }, new java.lang.String[] { "ar_AE", "الحالة الإجتماعية" } }),
	PlaceOfBirthPU(new java.lang.String[][] { new java.lang.String[] { "en_US", "PlaceOfBirthPU" }, new java.lang.String[] { "ar_AE", "مكان الميلاد بو" } }),
	Religion(new java.lang.String[][] { new java.lang.String[] { "en_US", "Religion" }, new java.lang.String[] { "ar_AE", "دين" } }),
	PlaceOfBirthMD(new java.lang.String[][] { new java.lang.String[] { "en_US", "PlaceOfBirthMD" }, new java.lang.String[] { "ar_AE", "مكان الميلاد مد" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private ENUM_TYPEOFENUMERATION(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
