// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package emiratesservice.proxies;

public class Enumerations
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject enumerationsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EmiratesService.Enumerations";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Caption("Caption"),
		Name("Name"),
		EnumType("EnumType"),
		CaptionAR("CaptionAR"),
		Update("Update");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Enumerations(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "EmiratesService.Enumerations"));
	}

	protected Enumerations(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject enumerationsMendixObject)
	{
		if (enumerationsMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("EmiratesService.Enumerations", enumerationsMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a EmiratesService.Enumerations");

		this.enumerationsMendixObject = enumerationsMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Enumerations.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static emiratesservice.proxies.Enumerations initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return emiratesservice.proxies.Enumerations.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static emiratesservice.proxies.Enumerations initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new emiratesservice.proxies.Enumerations(context, mendixObject);
	}

	public static emiratesservice.proxies.Enumerations load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return emiratesservice.proxies.Enumerations.initialize(context, mendixObject);
	}

	public static java.util.List<emiratesservice.proxies.Enumerations> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<emiratesservice.proxies.Enumerations> result = new java.util.ArrayList<emiratesservice.proxies.Enumerations>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//EmiratesService.Enumerations" + xpathConstraint))
			result.add(emiratesservice.proxies.Enumerations.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Caption
	 */
	public final java.lang.String getCaption()
	{
		return getCaption(getContext());
	}

	/**
	 * @param context
	 * @return value of Caption
	 */
	public final java.lang.String getCaption(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Caption.toString());
	}

	/**
	 * Set value of Caption
	 * @param caption
	 */
	public final void setCaption(java.lang.String caption)
	{
		setCaption(getContext(), caption);
	}

	/**
	 * Set value of Caption
	 * @param context
	 * @param caption
	 */
	public final void setCaption(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String caption)
	{
		getMendixObject().setValue(context, MemberNames.Caption.toString(), caption);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * Set value of EnumType
	 * @param enumtype
	 */
	public final emiratesservice.proxies.ENUM_TYPEOFENUMERATION getEnumType()
	{
		return getEnumType(getContext());
	}

	/**
	 * @param context
	 * @return value of EnumType
	 */
	public final emiratesservice.proxies.ENUM_TYPEOFENUMERATION getEnumType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.EnumType.toString());
		if (obj == null)
			return null;

		return emiratesservice.proxies.ENUM_TYPEOFENUMERATION.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of EnumType
	 * @param enumtype
	 */
	public final void setEnumType(emiratesservice.proxies.ENUM_TYPEOFENUMERATION enumtype)
	{
		setEnumType(getContext(), enumtype);
	}

	/**
	 * Set value of EnumType
	 * @param context
	 * @param enumtype
	 */
	public final void setEnumType(com.mendix.systemwideinterfaces.core.IContext context, emiratesservice.proxies.ENUM_TYPEOFENUMERATION enumtype)
	{
		if (enumtype != null)
			getMendixObject().setValue(context, MemberNames.EnumType.toString(), enumtype.toString());
		else
			getMendixObject().setValue(context, MemberNames.EnumType.toString(), null);
	}

	/**
	 * @return value of CaptionAR
	 */
	public final java.lang.String getCaptionAR()
	{
		return getCaptionAR(getContext());
	}

	/**
	 * @param context
	 * @return value of CaptionAR
	 */
	public final java.lang.String getCaptionAR(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CaptionAR.toString());
	}

	/**
	 * Set value of CaptionAR
	 * @param captionar
	 */
	public final void setCaptionAR(java.lang.String captionar)
	{
		setCaptionAR(getContext(), captionar);
	}

	/**
	 * Set value of CaptionAR
	 * @param context
	 * @param captionar
	 */
	public final void setCaptionAR(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String captionar)
	{
		getMendixObject().setValue(context, MemberNames.CaptionAR.toString(), captionar);
	}

	/**
	 * @return value of Update
	 */
	public final java.lang.Boolean getUpdate()
	{
		return getUpdate(getContext());
	}

	/**
	 * @param context
	 * @return value of Update
	 */
	public final java.lang.Boolean getUpdate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Update.toString());
	}

	/**
	 * Set value of Update
	 * @param update
	 */
	public final void setUpdate(java.lang.Boolean update)
	{
		setUpdate(getContext(), update);
	}

	/**
	 * Set value of Update
	 * @param context
	 * @param update
	 */
	public final void setUpdate(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean update)
	{
		getMendixObject().setValue(context, MemberNames.Update.toString(), update);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return enumerationsMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final emiratesservice.proxies.Enumerations that = (emiratesservice.proxies.Enumerations) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "EmiratesService.Enumerations";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
