// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package emiratesservice.proxies;

public class JsonObject
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject jsonObjectMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EmiratesService.JsonObject";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		MotherEmiratesId("MotherEmiratesId"),
		MotherEnglishFullName("MotherEnglishFullName"),
		MotherArabicFullName("MotherArabicFullName"),
		MotherNationality("MotherNationality"),
		MotherReligion("MotherReligion"),
		MotherMartialStatus("MotherMartialStatus"),
		FatherEmiratesId("FatherEmiratesId"),
		FatherEnglishFullName("FatherEnglishFullName"),
		FatherArabicFullName("FatherArabicFullName"),
		FatherNationality("FatherNationality"),
		FatherReligion("FatherReligion"),
		FatherMartialStatus("FatherMartialStatus"),
		InfantNameArabic("InfantNameArabic"),
		InfantNameEnglish("InfantNameEnglish"),
		TimeOfBirth("TimeOfBirth"),
		DateOfBirth("DateOfBirth"),
		DateInHijri("DateInHijri"),
		Gender("Gender"),
		InfantMedicalRecord("InfantMedicalRecord"),
		PlaceOfBirth("PlaceOfBirth"),
		BirthCountry("BirthCountry"),
		BirthOrder("BirthOrder"),
		DOB_Letter("DOB_Letter"),
		DOB_ArabicLetter("DOB_ArabicLetter"),
		Hijri_letter("Hijri_letter"),
		Hijri_ArabicLetter("Hijri_ArabicLetter"),
		JsonObject_Root("EmiratesService.JsonObject_Root"),
		JsonObject_Infants("EmiratesService.JsonObject_Infants");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public JsonObject(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "EmiratesService.JsonObject"));
	}

	protected JsonObject(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject jsonObjectMendixObject)
	{
		if (jsonObjectMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("EmiratesService.JsonObject", jsonObjectMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a EmiratesService.JsonObject");

		this.jsonObjectMendixObject = jsonObjectMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'JsonObject.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static emiratesservice.proxies.JsonObject initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return emiratesservice.proxies.JsonObject.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static emiratesservice.proxies.JsonObject initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new emiratesservice.proxies.JsonObject(context, mendixObject);
	}

	public static emiratesservice.proxies.JsonObject load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return emiratesservice.proxies.JsonObject.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of MotherEmiratesId
	 */
	public final java.lang.String getMotherEmiratesId()
	{
		return getMotherEmiratesId(getContext());
	}

	/**
	 * @param context
	 * @return value of MotherEmiratesId
	 */
	public final java.lang.String getMotherEmiratesId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MotherEmiratesId.toString());
	}

	/**
	 * Set value of MotherEmiratesId
	 * @param motheremiratesid
	 */
	public final void setMotherEmiratesId(java.lang.String motheremiratesid)
	{
		setMotherEmiratesId(getContext(), motheremiratesid);
	}

	/**
	 * Set value of MotherEmiratesId
	 * @param context
	 * @param motheremiratesid
	 */
	public final void setMotherEmiratesId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String motheremiratesid)
	{
		getMendixObject().setValue(context, MemberNames.MotherEmiratesId.toString(), motheremiratesid);
	}

	/**
	 * @return value of MotherEnglishFullName
	 */
	public final java.lang.String getMotherEnglishFullName()
	{
		return getMotherEnglishFullName(getContext());
	}

	/**
	 * @param context
	 * @return value of MotherEnglishFullName
	 */
	public final java.lang.String getMotherEnglishFullName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MotherEnglishFullName.toString());
	}

	/**
	 * Set value of MotherEnglishFullName
	 * @param motherenglishfullname
	 */
	public final void setMotherEnglishFullName(java.lang.String motherenglishfullname)
	{
		setMotherEnglishFullName(getContext(), motherenglishfullname);
	}

	/**
	 * Set value of MotherEnglishFullName
	 * @param context
	 * @param motherenglishfullname
	 */
	public final void setMotherEnglishFullName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String motherenglishfullname)
	{
		getMendixObject().setValue(context, MemberNames.MotherEnglishFullName.toString(), motherenglishfullname);
	}

	/**
	 * @return value of MotherArabicFullName
	 */
	public final java.lang.String getMotherArabicFullName()
	{
		return getMotherArabicFullName(getContext());
	}

	/**
	 * @param context
	 * @return value of MotherArabicFullName
	 */
	public final java.lang.String getMotherArabicFullName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MotherArabicFullName.toString());
	}

	/**
	 * Set value of MotherArabicFullName
	 * @param motherarabicfullname
	 */
	public final void setMotherArabicFullName(java.lang.String motherarabicfullname)
	{
		setMotherArabicFullName(getContext(), motherarabicfullname);
	}

	/**
	 * Set value of MotherArabicFullName
	 * @param context
	 * @param motherarabicfullname
	 */
	public final void setMotherArabicFullName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String motherarabicfullname)
	{
		getMendixObject().setValue(context, MemberNames.MotherArabicFullName.toString(), motherarabicfullname);
	}

	/**
	 * @return value of MotherNationality
	 */
	public final java.lang.String getMotherNationality()
	{
		return getMotherNationality(getContext());
	}

	/**
	 * @param context
	 * @return value of MotherNationality
	 */
	public final java.lang.String getMotherNationality(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MotherNationality.toString());
	}

	/**
	 * Set value of MotherNationality
	 * @param mothernationality
	 */
	public final void setMotherNationality(java.lang.String mothernationality)
	{
		setMotherNationality(getContext(), mothernationality);
	}

	/**
	 * Set value of MotherNationality
	 * @param context
	 * @param mothernationality
	 */
	public final void setMotherNationality(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String mothernationality)
	{
		getMendixObject().setValue(context, MemberNames.MotherNationality.toString(), mothernationality);
	}

	/**
	 * @return value of MotherReligion
	 */
	public final java.lang.String getMotherReligion()
	{
		return getMotherReligion(getContext());
	}

	/**
	 * @param context
	 * @return value of MotherReligion
	 */
	public final java.lang.String getMotherReligion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MotherReligion.toString());
	}

	/**
	 * Set value of MotherReligion
	 * @param motherreligion
	 */
	public final void setMotherReligion(java.lang.String motherreligion)
	{
		setMotherReligion(getContext(), motherreligion);
	}

	/**
	 * Set value of MotherReligion
	 * @param context
	 * @param motherreligion
	 */
	public final void setMotherReligion(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String motherreligion)
	{
		getMendixObject().setValue(context, MemberNames.MotherReligion.toString(), motherreligion);
	}

	/**
	 * @return value of MotherMartialStatus
	 */
	public final java.lang.String getMotherMartialStatus()
	{
		return getMotherMartialStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of MotherMartialStatus
	 */
	public final java.lang.String getMotherMartialStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MotherMartialStatus.toString());
	}

	/**
	 * Set value of MotherMartialStatus
	 * @param mothermartialstatus
	 */
	public final void setMotherMartialStatus(java.lang.String mothermartialstatus)
	{
		setMotherMartialStatus(getContext(), mothermartialstatus);
	}

	/**
	 * Set value of MotherMartialStatus
	 * @param context
	 * @param mothermartialstatus
	 */
	public final void setMotherMartialStatus(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String mothermartialstatus)
	{
		getMendixObject().setValue(context, MemberNames.MotherMartialStatus.toString(), mothermartialstatus);
	}

	/**
	 * @return value of FatherEmiratesId
	 */
	public final java.lang.String getFatherEmiratesId()
	{
		return getFatherEmiratesId(getContext());
	}

	/**
	 * @param context
	 * @return value of FatherEmiratesId
	 */
	public final java.lang.String getFatherEmiratesId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FatherEmiratesId.toString());
	}

	/**
	 * Set value of FatherEmiratesId
	 * @param fatheremiratesid
	 */
	public final void setFatherEmiratesId(java.lang.String fatheremiratesid)
	{
		setFatherEmiratesId(getContext(), fatheremiratesid);
	}

	/**
	 * Set value of FatherEmiratesId
	 * @param context
	 * @param fatheremiratesid
	 */
	public final void setFatherEmiratesId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String fatheremiratesid)
	{
		getMendixObject().setValue(context, MemberNames.FatherEmiratesId.toString(), fatheremiratesid);
	}

	/**
	 * @return value of FatherEnglishFullName
	 */
	public final java.lang.String getFatherEnglishFullName()
	{
		return getFatherEnglishFullName(getContext());
	}

	/**
	 * @param context
	 * @return value of FatherEnglishFullName
	 */
	public final java.lang.String getFatherEnglishFullName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FatherEnglishFullName.toString());
	}

	/**
	 * Set value of FatherEnglishFullName
	 * @param fatherenglishfullname
	 */
	public final void setFatherEnglishFullName(java.lang.String fatherenglishfullname)
	{
		setFatherEnglishFullName(getContext(), fatherenglishfullname);
	}

	/**
	 * Set value of FatherEnglishFullName
	 * @param context
	 * @param fatherenglishfullname
	 */
	public final void setFatherEnglishFullName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String fatherenglishfullname)
	{
		getMendixObject().setValue(context, MemberNames.FatherEnglishFullName.toString(), fatherenglishfullname);
	}

	/**
	 * @return value of FatherArabicFullName
	 */
	public final java.lang.String getFatherArabicFullName()
	{
		return getFatherArabicFullName(getContext());
	}

	/**
	 * @param context
	 * @return value of FatherArabicFullName
	 */
	public final java.lang.String getFatherArabicFullName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FatherArabicFullName.toString());
	}

	/**
	 * Set value of FatherArabicFullName
	 * @param fatherarabicfullname
	 */
	public final void setFatherArabicFullName(java.lang.String fatherarabicfullname)
	{
		setFatherArabicFullName(getContext(), fatherarabicfullname);
	}

	/**
	 * Set value of FatherArabicFullName
	 * @param context
	 * @param fatherarabicfullname
	 */
	public final void setFatherArabicFullName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String fatherarabicfullname)
	{
		getMendixObject().setValue(context, MemberNames.FatherArabicFullName.toString(), fatherarabicfullname);
	}

	/**
	 * @return value of FatherNationality
	 */
	public final java.lang.String getFatherNationality()
	{
		return getFatherNationality(getContext());
	}

	/**
	 * @param context
	 * @return value of FatherNationality
	 */
	public final java.lang.String getFatherNationality(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FatherNationality.toString());
	}

	/**
	 * Set value of FatherNationality
	 * @param fathernationality
	 */
	public final void setFatherNationality(java.lang.String fathernationality)
	{
		setFatherNationality(getContext(), fathernationality);
	}

	/**
	 * Set value of FatherNationality
	 * @param context
	 * @param fathernationality
	 */
	public final void setFatherNationality(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String fathernationality)
	{
		getMendixObject().setValue(context, MemberNames.FatherNationality.toString(), fathernationality);
	}

	/**
	 * @return value of FatherReligion
	 */
	public final java.lang.String getFatherReligion()
	{
		return getFatherReligion(getContext());
	}

	/**
	 * @param context
	 * @return value of FatherReligion
	 */
	public final java.lang.String getFatherReligion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FatherReligion.toString());
	}

	/**
	 * Set value of FatherReligion
	 * @param fatherreligion
	 */
	public final void setFatherReligion(java.lang.String fatherreligion)
	{
		setFatherReligion(getContext(), fatherreligion);
	}

	/**
	 * Set value of FatherReligion
	 * @param context
	 * @param fatherreligion
	 */
	public final void setFatherReligion(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String fatherreligion)
	{
		getMendixObject().setValue(context, MemberNames.FatherReligion.toString(), fatherreligion);
	}

	/**
	 * @return value of FatherMartialStatus
	 */
	public final java.lang.String getFatherMartialStatus()
	{
		return getFatherMartialStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of FatherMartialStatus
	 */
	public final java.lang.String getFatherMartialStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FatherMartialStatus.toString());
	}

	/**
	 * Set value of FatherMartialStatus
	 * @param fathermartialstatus
	 */
	public final void setFatherMartialStatus(java.lang.String fathermartialstatus)
	{
		setFatherMartialStatus(getContext(), fathermartialstatus);
	}

	/**
	 * Set value of FatherMartialStatus
	 * @param context
	 * @param fathermartialstatus
	 */
	public final void setFatherMartialStatus(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String fathermartialstatus)
	{
		getMendixObject().setValue(context, MemberNames.FatherMartialStatus.toString(), fathermartialstatus);
	}

	/**
	 * @return value of InfantNameArabic
	 */
	public final java.lang.String getInfantNameArabic()
	{
		return getInfantNameArabic(getContext());
	}

	/**
	 * @param context
	 * @return value of InfantNameArabic
	 */
	public final java.lang.String getInfantNameArabic(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.InfantNameArabic.toString());
	}

	/**
	 * Set value of InfantNameArabic
	 * @param infantnamearabic
	 */
	public final void setInfantNameArabic(java.lang.String infantnamearabic)
	{
		setInfantNameArabic(getContext(), infantnamearabic);
	}

	/**
	 * Set value of InfantNameArabic
	 * @param context
	 * @param infantnamearabic
	 */
	public final void setInfantNameArabic(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String infantnamearabic)
	{
		getMendixObject().setValue(context, MemberNames.InfantNameArabic.toString(), infantnamearabic);
	}

	/**
	 * @return value of InfantNameEnglish
	 */
	public final java.lang.String getInfantNameEnglish()
	{
		return getInfantNameEnglish(getContext());
	}

	/**
	 * @param context
	 * @return value of InfantNameEnglish
	 */
	public final java.lang.String getInfantNameEnglish(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.InfantNameEnglish.toString());
	}

	/**
	 * Set value of InfantNameEnglish
	 * @param infantnameenglish
	 */
	public final void setInfantNameEnglish(java.lang.String infantnameenglish)
	{
		setInfantNameEnglish(getContext(), infantnameenglish);
	}

	/**
	 * Set value of InfantNameEnglish
	 * @param context
	 * @param infantnameenglish
	 */
	public final void setInfantNameEnglish(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String infantnameenglish)
	{
		getMendixObject().setValue(context, MemberNames.InfantNameEnglish.toString(), infantnameenglish);
	}

	/**
	 * @return value of TimeOfBirth
	 */
	public final java.util.Date getTimeOfBirth()
	{
		return getTimeOfBirth(getContext());
	}

	/**
	 * @param context
	 * @return value of TimeOfBirth
	 */
	public final java.util.Date getTimeOfBirth(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.TimeOfBirth.toString());
	}

	/**
	 * Set value of TimeOfBirth
	 * @param timeofbirth
	 */
	public final void setTimeOfBirth(java.util.Date timeofbirth)
	{
		setTimeOfBirth(getContext(), timeofbirth);
	}

	/**
	 * Set value of TimeOfBirth
	 * @param context
	 * @param timeofbirth
	 */
	public final void setTimeOfBirth(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date timeofbirth)
	{
		getMendixObject().setValue(context, MemberNames.TimeOfBirth.toString(), timeofbirth);
	}

	/**
	 * @return value of DateOfBirth
	 */
	public final java.util.Date getDateOfBirth()
	{
		return getDateOfBirth(getContext());
	}

	/**
	 * @param context
	 * @return value of DateOfBirth
	 */
	public final java.util.Date getDateOfBirth(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DateOfBirth.toString());
	}

	/**
	 * Set value of DateOfBirth
	 * @param dateofbirth
	 */
	public final void setDateOfBirth(java.util.Date dateofbirth)
	{
		setDateOfBirth(getContext(), dateofbirth);
	}

	/**
	 * Set value of DateOfBirth
	 * @param context
	 * @param dateofbirth
	 */
	public final void setDateOfBirth(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date dateofbirth)
	{
		getMendixObject().setValue(context, MemberNames.DateOfBirth.toString(), dateofbirth);
	}

	/**
	 * @return value of DateInHijri
	 */
	public final java.lang.String getDateInHijri()
	{
		return getDateInHijri(getContext());
	}

	/**
	 * @param context
	 * @return value of DateInHijri
	 */
	public final java.lang.String getDateInHijri(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DateInHijri.toString());
	}

	/**
	 * Set value of DateInHijri
	 * @param dateinhijri
	 */
	public final void setDateInHijri(java.lang.String dateinhijri)
	{
		setDateInHijri(getContext(), dateinhijri);
	}

	/**
	 * Set value of DateInHijri
	 * @param context
	 * @param dateinhijri
	 */
	public final void setDateInHijri(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String dateinhijri)
	{
		getMendixObject().setValue(context, MemberNames.DateInHijri.toString(), dateinhijri);
	}

	/**
	 * @return value of Gender
	 */
	public final java.lang.String getGender()
	{
		return getGender(getContext());
	}

	/**
	 * @param context
	 * @return value of Gender
	 */
	public final java.lang.String getGender(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Gender.toString());
	}

	/**
	 * Set value of Gender
	 * @param gender
	 */
	public final void setGender(java.lang.String gender)
	{
		setGender(getContext(), gender);
	}

	/**
	 * Set value of Gender
	 * @param context
	 * @param gender
	 */
	public final void setGender(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String gender)
	{
		getMendixObject().setValue(context, MemberNames.Gender.toString(), gender);
	}

	/**
	 * @return value of InfantMedicalRecord
	 */
	public final java.lang.String getInfantMedicalRecord()
	{
		return getInfantMedicalRecord(getContext());
	}

	/**
	 * @param context
	 * @return value of InfantMedicalRecord
	 */
	public final java.lang.String getInfantMedicalRecord(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.InfantMedicalRecord.toString());
	}

	/**
	 * Set value of InfantMedicalRecord
	 * @param infantmedicalrecord
	 */
	public final void setInfantMedicalRecord(java.lang.String infantmedicalrecord)
	{
		setInfantMedicalRecord(getContext(), infantmedicalrecord);
	}

	/**
	 * Set value of InfantMedicalRecord
	 * @param context
	 * @param infantmedicalrecord
	 */
	public final void setInfantMedicalRecord(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String infantmedicalrecord)
	{
		getMendixObject().setValue(context, MemberNames.InfantMedicalRecord.toString(), infantmedicalrecord);
	}

	/**
	 * @return value of PlaceOfBirth
	 */
	public final java.lang.String getPlaceOfBirth()
	{
		return getPlaceOfBirth(getContext());
	}

	/**
	 * @param context
	 * @return value of PlaceOfBirth
	 */
	public final java.lang.String getPlaceOfBirth(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PlaceOfBirth.toString());
	}

	/**
	 * Set value of PlaceOfBirth
	 * @param placeofbirth
	 */
	public final void setPlaceOfBirth(java.lang.String placeofbirth)
	{
		setPlaceOfBirth(getContext(), placeofbirth);
	}

	/**
	 * Set value of PlaceOfBirth
	 * @param context
	 * @param placeofbirth
	 */
	public final void setPlaceOfBirth(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String placeofbirth)
	{
		getMendixObject().setValue(context, MemberNames.PlaceOfBirth.toString(), placeofbirth);
	}

	/**
	 * @return value of BirthCountry
	 */
	public final java.lang.String getBirthCountry()
	{
		return getBirthCountry(getContext());
	}

	/**
	 * @param context
	 * @return value of BirthCountry
	 */
	public final java.lang.String getBirthCountry(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.BirthCountry.toString());
	}

	/**
	 * Set value of BirthCountry
	 * @param birthcountry
	 */
	public final void setBirthCountry(java.lang.String birthcountry)
	{
		setBirthCountry(getContext(), birthcountry);
	}

	/**
	 * Set value of BirthCountry
	 * @param context
	 * @param birthcountry
	 */
	public final void setBirthCountry(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String birthcountry)
	{
		getMendixObject().setValue(context, MemberNames.BirthCountry.toString(), birthcountry);
	}

	/**
	 * @return value of BirthOrder
	 */
	public final java.lang.Integer getBirthOrder()
	{
		return getBirthOrder(getContext());
	}

	/**
	 * @param context
	 * @return value of BirthOrder
	 */
	public final java.lang.Integer getBirthOrder(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.BirthOrder.toString());
	}

	/**
	 * Set value of BirthOrder
	 * @param birthorder
	 */
	public final void setBirthOrder(java.lang.Integer birthorder)
	{
		setBirthOrder(getContext(), birthorder);
	}

	/**
	 * Set value of BirthOrder
	 * @param context
	 * @param birthorder
	 */
	public final void setBirthOrder(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer birthorder)
	{
		getMendixObject().setValue(context, MemberNames.BirthOrder.toString(), birthorder);
	}

	/**
	 * @return value of DOB_Letter
	 */
	public final java.lang.String getDOB_Letter()
	{
		return getDOB_Letter(getContext());
	}

	/**
	 * @param context
	 * @return value of DOB_Letter
	 */
	public final java.lang.String getDOB_Letter(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DOB_Letter.toString());
	}

	/**
	 * Set value of DOB_Letter
	 * @param dob_letter
	 */
	public final void setDOB_Letter(java.lang.String dob_letter)
	{
		setDOB_Letter(getContext(), dob_letter);
	}

	/**
	 * Set value of DOB_Letter
	 * @param context
	 * @param dob_letter
	 */
	public final void setDOB_Letter(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String dob_letter)
	{
		getMendixObject().setValue(context, MemberNames.DOB_Letter.toString(), dob_letter);
	}

	/**
	 * @return value of DOB_ArabicLetter
	 */
	public final java.lang.String getDOB_ArabicLetter()
	{
		return getDOB_ArabicLetter(getContext());
	}

	/**
	 * @param context
	 * @return value of DOB_ArabicLetter
	 */
	public final java.lang.String getDOB_ArabicLetter(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DOB_ArabicLetter.toString());
	}

	/**
	 * Set value of DOB_ArabicLetter
	 * @param dob_arabicletter
	 */
	public final void setDOB_ArabicLetter(java.lang.String dob_arabicletter)
	{
		setDOB_ArabicLetter(getContext(), dob_arabicletter);
	}

	/**
	 * Set value of DOB_ArabicLetter
	 * @param context
	 * @param dob_arabicletter
	 */
	public final void setDOB_ArabicLetter(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String dob_arabicletter)
	{
		getMendixObject().setValue(context, MemberNames.DOB_ArabicLetter.toString(), dob_arabicletter);
	}

	/**
	 * @return value of Hijri_letter
	 */
	public final java.lang.String getHijri_letter()
	{
		return getHijri_letter(getContext());
	}

	/**
	 * @param context
	 * @return value of Hijri_letter
	 */
	public final java.lang.String getHijri_letter(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Hijri_letter.toString());
	}

	/**
	 * Set value of Hijri_letter
	 * @param hijri_letter
	 */
	public final void setHijri_letter(java.lang.String hijri_letter)
	{
		setHijri_letter(getContext(), hijri_letter);
	}

	/**
	 * Set value of Hijri_letter
	 * @param context
	 * @param hijri_letter
	 */
	public final void setHijri_letter(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String hijri_letter)
	{
		getMendixObject().setValue(context, MemberNames.Hijri_letter.toString(), hijri_letter);
	}

	/**
	 * @return value of Hijri_ArabicLetter
	 */
	public final java.lang.String getHijri_ArabicLetter()
	{
		return getHijri_ArabicLetter(getContext());
	}

	/**
	 * @param context
	 * @return value of Hijri_ArabicLetter
	 */
	public final java.lang.String getHijri_ArabicLetter(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Hijri_ArabicLetter.toString());
	}

	/**
	 * Set value of Hijri_ArabicLetter
	 * @param hijri_arabicletter
	 */
	public final void setHijri_ArabicLetter(java.lang.String hijri_arabicletter)
	{
		setHijri_ArabicLetter(getContext(), hijri_arabicletter);
	}

	/**
	 * Set value of Hijri_ArabicLetter
	 * @param context
	 * @param hijri_arabicletter
	 */
	public final void setHijri_ArabicLetter(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String hijri_arabicletter)
	{
		getMendixObject().setValue(context, MemberNames.Hijri_ArabicLetter.toString(), hijri_arabicletter);
	}

	/**
	 * @return value of JsonObject_Root
	 */
	public final emiratesservice.proxies.Root getJsonObject_Root() throws com.mendix.core.CoreException
	{
		return getJsonObject_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of JsonObject_Root
	 */
	public final emiratesservice.proxies.Root getJsonObject_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		emiratesservice.proxies.Root result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.JsonObject_Root.toString());
		if (identifier != null)
			result = emiratesservice.proxies.Root.load(context, identifier);
		return result;
	}

	/**
	 * Set value of JsonObject_Root
	 * @param jsonobject_root
	 */
	public final void setJsonObject_Root(emiratesservice.proxies.Root jsonobject_root)
	{
		setJsonObject_Root(getContext(), jsonobject_root);
	}

	/**
	 * Set value of JsonObject_Root
	 * @param context
	 * @param jsonobject_root
	 */
	public final void setJsonObject_Root(com.mendix.systemwideinterfaces.core.IContext context, emiratesservice.proxies.Root jsonobject_root)
	{
		if (jsonobject_root == null)
			getMendixObject().setValue(context, MemberNames.JsonObject_Root.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.JsonObject_Root.toString(), jsonobject_root.getMendixObject().getId());
	}

	/**
	 * @return value of JsonObject_Infants
	 */
	public final emiratesservice.proxies.Infants getJsonObject_Infants() throws com.mendix.core.CoreException
	{
		return getJsonObject_Infants(getContext());
	}

	/**
	 * @param context
	 * @return value of JsonObject_Infants
	 */
	public final emiratesservice.proxies.Infants getJsonObject_Infants(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		emiratesservice.proxies.Infants result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.JsonObject_Infants.toString());
		if (identifier != null)
			result = emiratesservice.proxies.Infants.load(context, identifier);
		return result;
	}

	/**
	 * Set value of JsonObject_Infants
	 * @param jsonobject_infants
	 */
	public final void setJsonObject_Infants(emiratesservice.proxies.Infants jsonobject_infants)
	{
		setJsonObject_Infants(getContext(), jsonobject_infants);
	}

	/**
	 * Set value of JsonObject_Infants
	 * @param context
	 * @param jsonobject_infants
	 */
	public final void setJsonObject_Infants(com.mendix.systemwideinterfaces.core.IContext context, emiratesservice.proxies.Infants jsonobject_infants)
	{
		if (jsonobject_infants == null)
			getMendixObject().setValue(context, MemberNames.JsonObject_Infants.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.JsonObject_Infants.toString(), jsonobject_infants.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return jsonObjectMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final emiratesservice.proxies.JsonObject that = (emiratesservice.proxies.JsonObject) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "EmiratesService.JsonObject";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
