// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package emiratesservice.proxies;

public class JsonObject_2
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject jsonObject_2MendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EmiratesService.JsonObject_2";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Doc_name("Doc_name"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		Size("Size"),
		JsonObject_2_Attachmentss("EmiratesService.JsonObject_2_Attachmentss");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public JsonObject_2(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "EmiratesService.JsonObject_2"));
	}

	protected JsonObject_2(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject jsonObject_2MendixObject)
	{
		if (jsonObject_2MendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("EmiratesService.JsonObject_2", jsonObject_2MendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a EmiratesService.JsonObject_2");

		this.jsonObject_2MendixObject = jsonObject_2MendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'JsonObject_2.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static emiratesservice.proxies.JsonObject_2 initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return emiratesservice.proxies.JsonObject_2.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static emiratesservice.proxies.JsonObject_2 initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new emiratesservice.proxies.JsonObject_2(context, mendixObject);
	}

	public static emiratesservice.proxies.JsonObject_2 load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return emiratesservice.proxies.JsonObject_2.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Doc_name
	 */
	public final java.lang.String getDoc_name()
	{
		return getDoc_name(getContext());
	}

	/**
	 * @param context
	 * @return value of Doc_name
	 */
	public final java.lang.String getDoc_name(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Doc_name.toString());
	}

	/**
	 * Set value of Doc_name
	 * @param doc_name
	 */
	public final void setDoc_name(java.lang.String doc_name)
	{
		setDoc_name(getContext(), doc_name);
	}

	/**
	 * Set value of Doc_name
	 * @param context
	 * @param doc_name
	 */
	public final void setDoc_name(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String doc_name)
	{
		getMendixObject().setValue(context, MemberNames.Doc_name.toString(), doc_name);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of DeleteAfterDownload
	 */
	public final java.lang.Boolean getDeleteAfterDownload()
	{
		return getDeleteAfterDownload(getContext());
	}

	/**
	 * @param context
	 * @return value of DeleteAfterDownload
	 */
	public final java.lang.Boolean getDeleteAfterDownload(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.DeleteAfterDownload.toString());
	}

	/**
	 * Set value of DeleteAfterDownload
	 * @param deleteafterdownload
	 */
	public final void setDeleteAfterDownload(java.lang.Boolean deleteafterdownload)
	{
		setDeleteAfterDownload(getContext(), deleteafterdownload);
	}

	/**
	 * Set value of DeleteAfterDownload
	 * @param context
	 * @param deleteafterdownload
	 */
	public final void setDeleteAfterDownload(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean deleteafterdownload)
	{
		getMendixObject().setValue(context, MemberNames.DeleteAfterDownload.toString(), deleteafterdownload);
	}

	/**
	 * @return value of Contents
	 */
	public final java.lang.String getContents()
	{
		return getContents(getContext());
	}

	/**
	 * @param context
	 * @return value of Contents
	 */
	public final java.lang.String getContents(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Contents.toString());
	}

	/**
	 * Set value of Contents
	 * @param contents
	 */
	public final void setContents(java.lang.String contents)
	{
		setContents(getContext(), contents);
	}

	/**
	 * Set value of Contents
	 * @param context
	 * @param contents
	 */
	public final void setContents(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String contents)
	{
		getMendixObject().setValue(context, MemberNames.Contents.toString(), contents);
	}

	/**
	 * @return value of Size
	 */
	public final java.lang.Integer getSize()
	{
		return getSize(getContext());
	}

	/**
	 * @param context
	 * @return value of Size
	 */
	public final java.lang.Integer getSize(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Size.toString());
	}

	/**
	 * Set value of Size
	 * @param size
	 */
	public final void setSize(java.lang.Integer size)
	{
		setSize(getContext(), size);
	}

	/**
	 * Set value of Size
	 * @param context
	 * @param size
	 */
	public final void setSize(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer size)
	{
		getMendixObject().setValue(context, MemberNames.Size.toString(), size);
	}

	/**
	 * @return value of JsonObject_2_Attachmentss
	 */
	public final emiratesservice.proxies.Attachmentss getJsonObject_2_Attachmentss() throws com.mendix.core.CoreException
	{
		return getJsonObject_2_Attachmentss(getContext());
	}

	/**
	 * @param context
	 * @return value of JsonObject_2_Attachmentss
	 */
	public final emiratesservice.proxies.Attachmentss getJsonObject_2_Attachmentss(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		emiratesservice.proxies.Attachmentss result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.JsonObject_2_Attachmentss.toString());
		if (identifier != null)
			result = emiratesservice.proxies.Attachmentss.load(context, identifier);
		return result;
	}

	/**
	 * Set value of JsonObject_2_Attachmentss
	 * @param jsonobject_2_attachmentss
	 */
	public final void setJsonObject_2_Attachmentss(emiratesservice.proxies.Attachmentss jsonobject_2_attachmentss)
	{
		setJsonObject_2_Attachmentss(getContext(), jsonobject_2_attachmentss);
	}

	/**
	 * Set value of JsonObject_2_Attachmentss
	 * @param context
	 * @param jsonobject_2_attachmentss
	 */
	public final void setJsonObject_2_Attachmentss(com.mendix.systemwideinterfaces.core.IContext context, emiratesservice.proxies.Attachmentss jsonobject_2_attachmentss)
	{
		if (jsonobject_2_attachmentss == null)
			getMendixObject().setValue(context, MemberNames.JsonObject_2_Attachmentss.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.JsonObject_2_Attachmentss.toString(), jsonobject_2_attachmentss.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return jsonObject_2MendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final emiratesservice.proxies.JsonObject_2 that = (emiratesservice.proxies.JsonObject_2) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "EmiratesService.JsonObject_2";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
