// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package emiratesservice.proxies;

public class Root
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject rootMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "EmiratesService.Root";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		NotificationType("NotificationType"),
		NotificationNumber("NotificationNumber"),
		PlaceOfBirth("PlaceOfBirth"),
		InfantNameArabic("InfantNameArabic"),
		InfantNameEnglish("InfantNameEnglish"),
		TimeOfBirth("TimeOfBirth"),
		DateOfBirth("DateOfBirth"),
		DateInHijri("DateInHijri"),
		Gender("Gender"),
		NameOfTheHospital("NameOfTheHospital"),
		MotherMedicalRecord("MotherMedicalRecord"),
		MotherEmiratesID("MotherEmiratesID"),
		MotherEnglishFullName("MotherEnglishFullName"),
		MotherArabicFullName("MotherArabicFullName"),
		MotherMartialStatus("MotherMartialStatus"),
		MotherReligion("MotherReligion"),
		FatherEmiratesId("FatherEmiratesId"),
		FatherEnglishFullName("FatherEnglishFullName"),
		FatherArabicFullName("FatherArabicFullName"),
		FatherMartialStatus("FatherMartialStatus"),
		FatherReligion("FatherReligion"),
		IsPoliceCase("IsPoliceCase"),
		IsFatherKnown("IsFatherKnown"),
		ContinueWithCertificate("ContinueWithCertificate"),
		MotherNationality("MotherNationality"),
		FatherNationality("FatherNationality"),
		IsBirthcertificateNeeded("IsBirthcertificateNeeded"),
		Status("Status"),
		PlaceOfBirthMD("PlaceOfBirthMD"),
		PlaceOfBirthPU("PlaceOfBirthPU"),
		IsDraftRequest("IsDraftRequest"),
		Request_title("Request_title"),
		CSD_remark("CSD_remark"),
		Edit("Edit"),
		Infants_Root("EmiratesService.Infants_Root"),
		BirthCerticate_Root("EmiratesService.BirthCerticate_Root"),
		Attachmentss_Root("EmiratesService.Attachmentss_Root");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Root(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "EmiratesService.Root"));
	}

	protected Root(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject rootMendixObject)
	{
		if (rootMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("EmiratesService.Root", rootMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a EmiratesService.Root");

		this.rootMendixObject = rootMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Root.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static emiratesservice.proxies.Root initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return emiratesservice.proxies.Root.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static emiratesservice.proxies.Root initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new emiratesservice.proxies.Root(context, mendixObject);
	}

	public static emiratesservice.proxies.Root load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return emiratesservice.proxies.Root.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of NotificationType
	 */
	public final java.lang.String getNotificationType()
	{
		return getNotificationType(getContext());
	}

	/**
	 * @param context
	 * @return value of NotificationType
	 */
	public final java.lang.String getNotificationType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.NotificationType.toString());
	}

	/**
	 * Set value of NotificationType
	 * @param notificationtype
	 */
	public final void setNotificationType(java.lang.String notificationtype)
	{
		setNotificationType(getContext(), notificationtype);
	}

	/**
	 * Set value of NotificationType
	 * @param context
	 * @param notificationtype
	 */
	public final void setNotificationType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String notificationtype)
	{
		getMendixObject().setValue(context, MemberNames.NotificationType.toString(), notificationtype);
	}

	/**
	 * @return value of NotificationNumber
	 */
	public final java.lang.String getNotificationNumber()
	{
		return getNotificationNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of NotificationNumber
	 */
	public final java.lang.String getNotificationNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.NotificationNumber.toString());
	}

	/**
	 * Set value of NotificationNumber
	 * @param notificationnumber
	 */
	public final void setNotificationNumber(java.lang.String notificationnumber)
	{
		setNotificationNumber(getContext(), notificationnumber);
	}

	/**
	 * Set value of NotificationNumber
	 * @param context
	 * @param notificationnumber
	 */
	public final void setNotificationNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String notificationnumber)
	{
		getMendixObject().setValue(context, MemberNames.NotificationNumber.toString(), notificationnumber);
	}

	/**
	 * @return value of PlaceOfBirth
	 */
	public final java.lang.String getPlaceOfBirth()
	{
		return getPlaceOfBirth(getContext());
	}

	/**
	 * @param context
	 * @return value of PlaceOfBirth
	 */
	public final java.lang.String getPlaceOfBirth(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PlaceOfBirth.toString());
	}

	/**
	 * Set value of PlaceOfBirth
	 * @param placeofbirth
	 */
	public final void setPlaceOfBirth(java.lang.String placeofbirth)
	{
		setPlaceOfBirth(getContext(), placeofbirth);
	}

	/**
	 * Set value of PlaceOfBirth
	 * @param context
	 * @param placeofbirth
	 */
	public final void setPlaceOfBirth(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String placeofbirth)
	{
		getMendixObject().setValue(context, MemberNames.PlaceOfBirth.toString(), placeofbirth);
	}

	/**
	 * @return value of InfantNameArabic
	 */
	public final java.lang.String getInfantNameArabic()
	{
		return getInfantNameArabic(getContext());
	}

	/**
	 * @param context
	 * @return value of InfantNameArabic
	 */
	public final java.lang.String getInfantNameArabic(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.InfantNameArabic.toString());
	}

	/**
	 * Set value of InfantNameArabic
	 * @param infantnamearabic
	 */
	public final void setInfantNameArabic(java.lang.String infantnamearabic)
	{
		setInfantNameArabic(getContext(), infantnamearabic);
	}

	/**
	 * Set value of InfantNameArabic
	 * @param context
	 * @param infantnamearabic
	 */
	public final void setInfantNameArabic(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String infantnamearabic)
	{
		getMendixObject().setValue(context, MemberNames.InfantNameArabic.toString(), infantnamearabic);
	}

	/**
	 * @return value of InfantNameEnglish
	 */
	public final java.lang.String getInfantNameEnglish()
	{
		return getInfantNameEnglish(getContext());
	}

	/**
	 * @param context
	 * @return value of InfantNameEnglish
	 */
	public final java.lang.String getInfantNameEnglish(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.InfantNameEnglish.toString());
	}

	/**
	 * Set value of InfantNameEnglish
	 * @param infantnameenglish
	 */
	public final void setInfantNameEnglish(java.lang.String infantnameenglish)
	{
		setInfantNameEnglish(getContext(), infantnameenglish);
	}

	/**
	 * Set value of InfantNameEnglish
	 * @param context
	 * @param infantnameenglish
	 */
	public final void setInfantNameEnglish(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String infantnameenglish)
	{
		getMendixObject().setValue(context, MemberNames.InfantNameEnglish.toString(), infantnameenglish);
	}

	/**
	 * @return value of TimeOfBirth
	 */
	public final java.util.Date getTimeOfBirth()
	{
		return getTimeOfBirth(getContext());
	}

	/**
	 * @param context
	 * @return value of TimeOfBirth
	 */
	public final java.util.Date getTimeOfBirth(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.TimeOfBirth.toString());
	}

	/**
	 * Set value of TimeOfBirth
	 * @param timeofbirth
	 */
	public final void setTimeOfBirth(java.util.Date timeofbirth)
	{
		setTimeOfBirth(getContext(), timeofbirth);
	}

	/**
	 * Set value of TimeOfBirth
	 * @param context
	 * @param timeofbirth
	 */
	public final void setTimeOfBirth(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date timeofbirth)
	{
		getMendixObject().setValue(context, MemberNames.TimeOfBirth.toString(), timeofbirth);
	}

	/**
	 * @return value of DateOfBirth
	 */
	public final java.util.Date getDateOfBirth()
	{
		return getDateOfBirth(getContext());
	}

	/**
	 * @param context
	 * @return value of DateOfBirth
	 */
	public final java.util.Date getDateOfBirth(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DateOfBirth.toString());
	}

	/**
	 * Set value of DateOfBirth
	 * @param dateofbirth
	 */
	public final void setDateOfBirth(java.util.Date dateofbirth)
	{
		setDateOfBirth(getContext(), dateofbirth);
	}

	/**
	 * Set value of DateOfBirth
	 * @param context
	 * @param dateofbirth
	 */
	public final void setDateOfBirth(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date dateofbirth)
	{
		getMendixObject().setValue(context, MemberNames.DateOfBirth.toString(), dateofbirth);
	}

	/**
	 * @return value of DateInHijri
	 */
	public final java.util.Date getDateInHijri()
	{
		return getDateInHijri(getContext());
	}

	/**
	 * @param context
	 * @return value of DateInHijri
	 */
	public final java.util.Date getDateInHijri(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DateInHijri.toString());
	}

	/**
	 * Set value of DateInHijri
	 * @param dateinhijri
	 */
	public final void setDateInHijri(java.util.Date dateinhijri)
	{
		setDateInHijri(getContext(), dateinhijri);
	}

	/**
	 * Set value of DateInHijri
	 * @param context
	 * @param dateinhijri
	 */
	public final void setDateInHijri(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date dateinhijri)
	{
		getMendixObject().setValue(context, MemberNames.DateInHijri.toString(), dateinhijri);
	}

	/**
	 * @return value of Gender
	 */
	public final java.lang.String getGender()
	{
		return getGender(getContext());
	}

	/**
	 * @param context
	 * @return value of Gender
	 */
	public final java.lang.String getGender(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Gender.toString());
	}

	/**
	 * Set value of Gender
	 * @param gender
	 */
	public final void setGender(java.lang.String gender)
	{
		setGender(getContext(), gender);
	}

	/**
	 * Set value of Gender
	 * @param context
	 * @param gender
	 */
	public final void setGender(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String gender)
	{
		getMendixObject().setValue(context, MemberNames.Gender.toString(), gender);
	}

	/**
	 * @return value of NameOfTheHospital
	 */
	public final java.lang.String getNameOfTheHospital()
	{
		return getNameOfTheHospital(getContext());
	}

	/**
	 * @param context
	 * @return value of NameOfTheHospital
	 */
	public final java.lang.String getNameOfTheHospital(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.NameOfTheHospital.toString());
	}

	/**
	 * Set value of NameOfTheHospital
	 * @param nameofthehospital
	 */
	public final void setNameOfTheHospital(java.lang.String nameofthehospital)
	{
		setNameOfTheHospital(getContext(), nameofthehospital);
	}

	/**
	 * Set value of NameOfTheHospital
	 * @param context
	 * @param nameofthehospital
	 */
	public final void setNameOfTheHospital(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String nameofthehospital)
	{
		getMendixObject().setValue(context, MemberNames.NameOfTheHospital.toString(), nameofthehospital);
	}

	/**
	 * @return value of MotherMedicalRecord
	 */
	public final java.lang.String getMotherMedicalRecord()
	{
		return getMotherMedicalRecord(getContext());
	}

	/**
	 * @param context
	 * @return value of MotherMedicalRecord
	 */
	public final java.lang.String getMotherMedicalRecord(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MotherMedicalRecord.toString());
	}

	/**
	 * Set value of MotherMedicalRecord
	 * @param mothermedicalrecord
	 */
	public final void setMotherMedicalRecord(java.lang.String mothermedicalrecord)
	{
		setMotherMedicalRecord(getContext(), mothermedicalrecord);
	}

	/**
	 * Set value of MotherMedicalRecord
	 * @param context
	 * @param mothermedicalrecord
	 */
	public final void setMotherMedicalRecord(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String mothermedicalrecord)
	{
		getMendixObject().setValue(context, MemberNames.MotherMedicalRecord.toString(), mothermedicalrecord);
	}

	/**
	 * @return value of MotherEmiratesID
	 */
	public final java.lang.String getMotherEmiratesID()
	{
		return getMotherEmiratesID(getContext());
	}

	/**
	 * @param context
	 * @return value of MotherEmiratesID
	 */
	public final java.lang.String getMotherEmiratesID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MotherEmiratesID.toString());
	}

	/**
	 * Set value of MotherEmiratesID
	 * @param motheremiratesid
	 */
	public final void setMotherEmiratesID(java.lang.String motheremiratesid)
	{
		setMotherEmiratesID(getContext(), motheremiratesid);
	}

	/**
	 * Set value of MotherEmiratesID
	 * @param context
	 * @param motheremiratesid
	 */
	public final void setMotherEmiratesID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String motheremiratesid)
	{
		getMendixObject().setValue(context, MemberNames.MotherEmiratesID.toString(), motheremiratesid);
	}

	/**
	 * @return value of MotherEnglishFullName
	 */
	public final java.lang.String getMotherEnglishFullName()
	{
		return getMotherEnglishFullName(getContext());
	}

	/**
	 * @param context
	 * @return value of MotherEnglishFullName
	 */
	public final java.lang.String getMotherEnglishFullName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MotherEnglishFullName.toString());
	}

	/**
	 * Set value of MotherEnglishFullName
	 * @param motherenglishfullname
	 */
	public final void setMotherEnglishFullName(java.lang.String motherenglishfullname)
	{
		setMotherEnglishFullName(getContext(), motherenglishfullname);
	}

	/**
	 * Set value of MotherEnglishFullName
	 * @param context
	 * @param motherenglishfullname
	 */
	public final void setMotherEnglishFullName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String motherenglishfullname)
	{
		getMendixObject().setValue(context, MemberNames.MotherEnglishFullName.toString(), motherenglishfullname);
	}

	/**
	 * @return value of MotherArabicFullName
	 */
	public final java.lang.String getMotherArabicFullName()
	{
		return getMotherArabicFullName(getContext());
	}

	/**
	 * @param context
	 * @return value of MotherArabicFullName
	 */
	public final java.lang.String getMotherArabicFullName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MotherArabicFullName.toString());
	}

	/**
	 * Set value of MotherArabicFullName
	 * @param motherarabicfullname
	 */
	public final void setMotherArabicFullName(java.lang.String motherarabicfullname)
	{
		setMotherArabicFullName(getContext(), motherarabicfullname);
	}

	/**
	 * Set value of MotherArabicFullName
	 * @param context
	 * @param motherarabicfullname
	 */
	public final void setMotherArabicFullName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String motherarabicfullname)
	{
		getMendixObject().setValue(context, MemberNames.MotherArabicFullName.toString(), motherarabicfullname);
	}

	/**
	 * @return value of MotherMartialStatus
	 */
	public final java.lang.String getMotherMartialStatus()
	{
		return getMotherMartialStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of MotherMartialStatus
	 */
	public final java.lang.String getMotherMartialStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MotherMartialStatus.toString());
	}

	/**
	 * Set value of MotherMartialStatus
	 * @param mothermartialstatus
	 */
	public final void setMotherMartialStatus(java.lang.String mothermartialstatus)
	{
		setMotherMartialStatus(getContext(), mothermartialstatus);
	}

	/**
	 * Set value of MotherMartialStatus
	 * @param context
	 * @param mothermartialstatus
	 */
	public final void setMotherMartialStatus(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String mothermartialstatus)
	{
		getMendixObject().setValue(context, MemberNames.MotherMartialStatus.toString(), mothermartialstatus);
	}

	/**
	 * @return value of MotherReligion
	 */
	public final java.lang.String getMotherReligion()
	{
		return getMotherReligion(getContext());
	}

	/**
	 * @param context
	 * @return value of MotherReligion
	 */
	public final java.lang.String getMotherReligion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MotherReligion.toString());
	}

	/**
	 * Set value of MotherReligion
	 * @param motherreligion
	 */
	public final void setMotherReligion(java.lang.String motherreligion)
	{
		setMotherReligion(getContext(), motherreligion);
	}

	/**
	 * Set value of MotherReligion
	 * @param context
	 * @param motherreligion
	 */
	public final void setMotherReligion(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String motherreligion)
	{
		getMendixObject().setValue(context, MemberNames.MotherReligion.toString(), motherreligion);
	}

	/**
	 * @return value of FatherEmiratesId
	 */
	public final java.lang.String getFatherEmiratesId()
	{
		return getFatherEmiratesId(getContext());
	}

	/**
	 * @param context
	 * @return value of FatherEmiratesId
	 */
	public final java.lang.String getFatherEmiratesId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FatherEmiratesId.toString());
	}

	/**
	 * Set value of FatherEmiratesId
	 * @param fatheremiratesid
	 */
	public final void setFatherEmiratesId(java.lang.String fatheremiratesid)
	{
		setFatherEmiratesId(getContext(), fatheremiratesid);
	}

	/**
	 * Set value of FatherEmiratesId
	 * @param context
	 * @param fatheremiratesid
	 */
	public final void setFatherEmiratesId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String fatheremiratesid)
	{
		getMendixObject().setValue(context, MemberNames.FatherEmiratesId.toString(), fatheremiratesid);
	}

	/**
	 * @return value of FatherEnglishFullName
	 */
	public final java.lang.String getFatherEnglishFullName()
	{
		return getFatherEnglishFullName(getContext());
	}

	/**
	 * @param context
	 * @return value of FatherEnglishFullName
	 */
	public final java.lang.String getFatherEnglishFullName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FatherEnglishFullName.toString());
	}

	/**
	 * Set value of FatherEnglishFullName
	 * @param fatherenglishfullname
	 */
	public final void setFatherEnglishFullName(java.lang.String fatherenglishfullname)
	{
		setFatherEnglishFullName(getContext(), fatherenglishfullname);
	}

	/**
	 * Set value of FatherEnglishFullName
	 * @param context
	 * @param fatherenglishfullname
	 */
	public final void setFatherEnglishFullName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String fatherenglishfullname)
	{
		getMendixObject().setValue(context, MemberNames.FatherEnglishFullName.toString(), fatherenglishfullname);
	}

	/**
	 * @return value of FatherArabicFullName
	 */
	public final java.lang.String getFatherArabicFullName()
	{
		return getFatherArabicFullName(getContext());
	}

	/**
	 * @param context
	 * @return value of FatherArabicFullName
	 */
	public final java.lang.String getFatherArabicFullName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FatherArabicFullName.toString());
	}

	/**
	 * Set value of FatherArabicFullName
	 * @param fatherarabicfullname
	 */
	public final void setFatherArabicFullName(java.lang.String fatherarabicfullname)
	{
		setFatherArabicFullName(getContext(), fatherarabicfullname);
	}

	/**
	 * Set value of FatherArabicFullName
	 * @param context
	 * @param fatherarabicfullname
	 */
	public final void setFatherArabicFullName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String fatherarabicfullname)
	{
		getMendixObject().setValue(context, MemberNames.FatherArabicFullName.toString(), fatherarabicfullname);
	}

	/**
	 * @return value of FatherMartialStatus
	 */
	public final java.lang.String getFatherMartialStatus()
	{
		return getFatherMartialStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of FatherMartialStatus
	 */
	public final java.lang.String getFatherMartialStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FatherMartialStatus.toString());
	}

	/**
	 * Set value of FatherMartialStatus
	 * @param fathermartialstatus
	 */
	public final void setFatherMartialStatus(java.lang.String fathermartialstatus)
	{
		setFatherMartialStatus(getContext(), fathermartialstatus);
	}

	/**
	 * Set value of FatherMartialStatus
	 * @param context
	 * @param fathermartialstatus
	 */
	public final void setFatherMartialStatus(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String fathermartialstatus)
	{
		getMendixObject().setValue(context, MemberNames.FatherMartialStatus.toString(), fathermartialstatus);
	}

	/**
	 * @return value of FatherReligion
	 */
	public final java.lang.String getFatherReligion()
	{
		return getFatherReligion(getContext());
	}

	/**
	 * @param context
	 * @return value of FatherReligion
	 */
	public final java.lang.String getFatherReligion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FatherReligion.toString());
	}

	/**
	 * Set value of FatherReligion
	 * @param fatherreligion
	 */
	public final void setFatherReligion(java.lang.String fatherreligion)
	{
		setFatherReligion(getContext(), fatherreligion);
	}

	/**
	 * Set value of FatherReligion
	 * @param context
	 * @param fatherreligion
	 */
	public final void setFatherReligion(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String fatherreligion)
	{
		getMendixObject().setValue(context, MemberNames.FatherReligion.toString(), fatherreligion);
	}

	/**
	 * @return value of IsPoliceCase
	 */
	public final java.lang.Boolean getIsPoliceCase()
	{
		return getIsPoliceCase(getContext());
	}

	/**
	 * @param context
	 * @return value of IsPoliceCase
	 */
	public final java.lang.Boolean getIsPoliceCase(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsPoliceCase.toString());
	}

	/**
	 * Set value of IsPoliceCase
	 * @param ispolicecase
	 */
	public final void setIsPoliceCase(java.lang.Boolean ispolicecase)
	{
		setIsPoliceCase(getContext(), ispolicecase);
	}

	/**
	 * Set value of IsPoliceCase
	 * @param context
	 * @param ispolicecase
	 */
	public final void setIsPoliceCase(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean ispolicecase)
	{
		getMendixObject().setValue(context, MemberNames.IsPoliceCase.toString(), ispolicecase);
	}

	/**
	 * @return value of IsFatherKnown
	 */
	public final java.lang.Boolean getIsFatherKnown()
	{
		return getIsFatherKnown(getContext());
	}

	/**
	 * @param context
	 * @return value of IsFatherKnown
	 */
	public final java.lang.Boolean getIsFatherKnown(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsFatherKnown.toString());
	}

	/**
	 * Set value of IsFatherKnown
	 * @param isfatherknown
	 */
	public final void setIsFatherKnown(java.lang.Boolean isfatherknown)
	{
		setIsFatherKnown(getContext(), isfatherknown);
	}

	/**
	 * Set value of IsFatherKnown
	 * @param context
	 * @param isfatherknown
	 */
	public final void setIsFatherKnown(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isfatherknown)
	{
		getMendixObject().setValue(context, MemberNames.IsFatherKnown.toString(), isfatherknown);
	}

	/**
	 * @return value of ContinueWithCertificate
	 */
	public final java.lang.Boolean getContinueWithCertificate()
	{
		return getContinueWithCertificate(getContext());
	}

	/**
	 * @param context
	 * @return value of ContinueWithCertificate
	 */
	public final java.lang.Boolean getContinueWithCertificate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ContinueWithCertificate.toString());
	}

	/**
	 * Set value of ContinueWithCertificate
	 * @param continuewithcertificate
	 */
	public final void setContinueWithCertificate(java.lang.Boolean continuewithcertificate)
	{
		setContinueWithCertificate(getContext(), continuewithcertificate);
	}

	/**
	 * Set value of ContinueWithCertificate
	 * @param context
	 * @param continuewithcertificate
	 */
	public final void setContinueWithCertificate(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean continuewithcertificate)
	{
		getMendixObject().setValue(context, MemberNames.ContinueWithCertificate.toString(), continuewithcertificate);
	}

	/**
	 * @return value of MotherNationality
	 */
	public final java.lang.String getMotherNationality()
	{
		return getMotherNationality(getContext());
	}

	/**
	 * @param context
	 * @return value of MotherNationality
	 */
	public final java.lang.String getMotherNationality(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MotherNationality.toString());
	}

	/**
	 * Set value of MotherNationality
	 * @param mothernationality
	 */
	public final void setMotherNationality(java.lang.String mothernationality)
	{
		setMotherNationality(getContext(), mothernationality);
	}

	/**
	 * Set value of MotherNationality
	 * @param context
	 * @param mothernationality
	 */
	public final void setMotherNationality(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String mothernationality)
	{
		getMendixObject().setValue(context, MemberNames.MotherNationality.toString(), mothernationality);
	}

	/**
	 * @return value of FatherNationality
	 */
	public final java.lang.String getFatherNationality()
	{
		return getFatherNationality(getContext());
	}

	/**
	 * @param context
	 * @return value of FatherNationality
	 */
	public final java.lang.String getFatherNationality(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FatherNationality.toString());
	}

	/**
	 * Set value of FatherNationality
	 * @param fathernationality
	 */
	public final void setFatherNationality(java.lang.String fathernationality)
	{
		setFatherNationality(getContext(), fathernationality);
	}

	/**
	 * Set value of FatherNationality
	 * @param context
	 * @param fathernationality
	 */
	public final void setFatherNationality(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String fathernationality)
	{
		getMendixObject().setValue(context, MemberNames.FatherNationality.toString(), fathernationality);
	}

	/**
	 * @return value of IsBirthcertificateNeeded
	 */
	public final java.lang.Boolean getIsBirthcertificateNeeded()
	{
		return getIsBirthcertificateNeeded(getContext());
	}

	/**
	 * @param context
	 * @return value of IsBirthcertificateNeeded
	 */
	public final java.lang.Boolean getIsBirthcertificateNeeded(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsBirthcertificateNeeded.toString());
	}

	/**
	 * Set value of IsBirthcertificateNeeded
	 * @param isbirthcertificateneeded
	 */
	public final void setIsBirthcertificateNeeded(java.lang.Boolean isbirthcertificateneeded)
	{
		setIsBirthcertificateNeeded(getContext(), isbirthcertificateneeded);
	}

	/**
	 * Set value of IsBirthcertificateNeeded
	 * @param context
	 * @param isbirthcertificateneeded
	 */
	public final void setIsBirthcertificateNeeded(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isbirthcertificateneeded)
	{
		getMendixObject().setValue(context, MemberNames.IsBirthcertificateNeeded.toString(), isbirthcertificateneeded);
	}

	/**
	 * @return value of Status
	 */
	public final java.lang.String getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final java.lang.String getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Status.toString());
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(java.lang.String status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String status)
	{
		getMendixObject().setValue(context, MemberNames.Status.toString(), status);
	}

	/**
	 * @return value of PlaceOfBirthMD
	 */
	public final java.lang.String getPlaceOfBirthMD()
	{
		return getPlaceOfBirthMD(getContext());
	}

	/**
	 * @param context
	 * @return value of PlaceOfBirthMD
	 */
	public final java.lang.String getPlaceOfBirthMD(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PlaceOfBirthMD.toString());
	}

	/**
	 * Set value of PlaceOfBirthMD
	 * @param placeofbirthmd
	 */
	public final void setPlaceOfBirthMD(java.lang.String placeofbirthmd)
	{
		setPlaceOfBirthMD(getContext(), placeofbirthmd);
	}

	/**
	 * Set value of PlaceOfBirthMD
	 * @param context
	 * @param placeofbirthmd
	 */
	public final void setPlaceOfBirthMD(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String placeofbirthmd)
	{
		getMendixObject().setValue(context, MemberNames.PlaceOfBirthMD.toString(), placeofbirthmd);
	}

	/**
	 * @return value of PlaceOfBirthPU
	 */
	public final java.lang.String getPlaceOfBirthPU()
	{
		return getPlaceOfBirthPU(getContext());
	}

	/**
	 * @param context
	 * @return value of PlaceOfBirthPU
	 */
	public final java.lang.String getPlaceOfBirthPU(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PlaceOfBirthPU.toString());
	}

	/**
	 * Set value of PlaceOfBirthPU
	 * @param placeofbirthpu
	 */
	public final void setPlaceOfBirthPU(java.lang.String placeofbirthpu)
	{
		setPlaceOfBirthPU(getContext(), placeofbirthpu);
	}

	/**
	 * Set value of PlaceOfBirthPU
	 * @param context
	 * @param placeofbirthpu
	 */
	public final void setPlaceOfBirthPU(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String placeofbirthpu)
	{
		getMendixObject().setValue(context, MemberNames.PlaceOfBirthPU.toString(), placeofbirthpu);
	}

	/**
	 * @return value of IsDraftRequest
	 */
	public final java.lang.Boolean getIsDraftRequest()
	{
		return getIsDraftRequest(getContext());
	}

	/**
	 * @param context
	 * @return value of IsDraftRequest
	 */
	public final java.lang.Boolean getIsDraftRequest(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsDraftRequest.toString());
	}

	/**
	 * Set value of IsDraftRequest
	 * @param isdraftrequest
	 */
	public final void setIsDraftRequest(java.lang.Boolean isdraftrequest)
	{
		setIsDraftRequest(getContext(), isdraftrequest);
	}

	/**
	 * Set value of IsDraftRequest
	 * @param context
	 * @param isdraftrequest
	 */
	public final void setIsDraftRequest(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isdraftrequest)
	{
		getMendixObject().setValue(context, MemberNames.IsDraftRequest.toString(), isdraftrequest);
	}

	/**
	 * @return value of Request_title
	 */
	public final java.lang.String getRequest_title()
	{
		return getRequest_title(getContext());
	}

	/**
	 * @param context
	 * @return value of Request_title
	 */
	public final java.lang.String getRequest_title(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Request_title.toString());
	}

	/**
	 * Set value of Request_title
	 * @param request_title
	 */
	public final void setRequest_title(java.lang.String request_title)
	{
		setRequest_title(getContext(), request_title);
	}

	/**
	 * Set value of Request_title
	 * @param context
	 * @param request_title
	 */
	public final void setRequest_title(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String request_title)
	{
		getMendixObject().setValue(context, MemberNames.Request_title.toString(), request_title);
	}

	/**
	 * @return value of CSD_remark
	 */
	public final java.lang.String getCSD_remark()
	{
		return getCSD_remark(getContext());
	}

	/**
	 * @param context
	 * @return value of CSD_remark
	 */
	public final java.lang.String getCSD_remark(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CSD_remark.toString());
	}

	/**
	 * Set value of CSD_remark
	 * @param csd_remark
	 */
	public final void setCSD_remark(java.lang.String csd_remark)
	{
		setCSD_remark(getContext(), csd_remark);
	}

	/**
	 * Set value of CSD_remark
	 * @param context
	 * @param csd_remark
	 */
	public final void setCSD_remark(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String csd_remark)
	{
		getMendixObject().setValue(context, MemberNames.CSD_remark.toString(), csd_remark);
	}

	/**
	 * @return value of Edit
	 */
	public final java.lang.Boolean getEdit()
	{
		return getEdit(getContext());
	}

	/**
	 * @param context
	 * @return value of Edit
	 */
	public final java.lang.Boolean getEdit(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Edit.toString());
	}

	/**
	 * Set value of Edit
	 * @param edit
	 */
	public final void setEdit(java.lang.Boolean edit)
	{
		setEdit(getContext(), edit);
	}

	/**
	 * Set value of Edit
	 * @param context
	 * @param edit
	 */
	public final void setEdit(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean edit)
	{
		getMendixObject().setValue(context, MemberNames.Edit.toString(), edit);
	}

	/**
	 * @return value of Infants_Root
	 */
	public final emiratesservice.proxies.Infants getInfants_Root() throws com.mendix.core.CoreException
	{
		return getInfants_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of Infants_Root
	 */
	public final emiratesservice.proxies.Infants getInfants_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		emiratesservice.proxies.Infants result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Infants_Root.toString());
		if (identifier != null)
			result = emiratesservice.proxies.Infants.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Infants_Root
	 * @param infants_root
	 */
	public final void setInfants_Root(emiratesservice.proxies.Infants infants_root)
	{
		setInfants_Root(getContext(), infants_root);
	}

	/**
	 * Set value of Infants_Root
	 * @param context
	 * @param infants_root
	 */
	public final void setInfants_Root(com.mendix.systemwideinterfaces.core.IContext context, emiratesservice.proxies.Infants infants_root)
	{
		if (infants_root == null)
			getMendixObject().setValue(context, MemberNames.Infants_Root.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Infants_Root.toString(), infants_root.getMendixObject().getId());
	}

	/**
	 * @return value of BirthCerticate_Root
	 */
	public final emiratesservice.proxies.BirthCerticate getBirthCerticate_Root() throws com.mendix.core.CoreException
	{
		return getBirthCerticate_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of BirthCerticate_Root
	 */
	public final emiratesservice.proxies.BirthCerticate getBirthCerticate_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		emiratesservice.proxies.BirthCerticate result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.BirthCerticate_Root.toString());
		if (identifier != null)
			result = emiratesservice.proxies.BirthCerticate.load(context, identifier);
		return result;
	}

	/**
	 * Set value of BirthCerticate_Root
	 * @param birthcerticate_root
	 */
	public final void setBirthCerticate_Root(emiratesservice.proxies.BirthCerticate birthcerticate_root)
	{
		setBirthCerticate_Root(getContext(), birthcerticate_root);
	}

	/**
	 * Set value of BirthCerticate_Root
	 * @param context
	 * @param birthcerticate_root
	 */
	public final void setBirthCerticate_Root(com.mendix.systemwideinterfaces.core.IContext context, emiratesservice.proxies.BirthCerticate birthcerticate_root)
	{
		if (birthcerticate_root == null)
			getMendixObject().setValue(context, MemberNames.BirthCerticate_Root.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.BirthCerticate_Root.toString(), birthcerticate_root.getMendixObject().getId());
	}

	/**
	 * @return value of Attachmentss_Root
	 */
	public final emiratesservice.proxies.Attachmentss getAttachmentss_Root() throws com.mendix.core.CoreException
	{
		return getAttachmentss_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of Attachmentss_Root
	 */
	public final emiratesservice.proxies.Attachmentss getAttachmentss_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		emiratesservice.proxies.Attachmentss result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Attachmentss_Root.toString());
		if (identifier != null)
			result = emiratesservice.proxies.Attachmentss.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Attachmentss_Root
	 * @param attachmentss_root
	 */
	public final void setAttachmentss_Root(emiratesservice.proxies.Attachmentss attachmentss_root)
	{
		setAttachmentss_Root(getContext(), attachmentss_root);
	}

	/**
	 * Set value of Attachmentss_Root
	 * @param context
	 * @param attachmentss_root
	 */
	public final void setAttachmentss_Root(com.mendix.systemwideinterfaces.core.IContext context, emiratesservice.proxies.Attachmentss attachmentss_root)
	{
		if (attachmentss_root == null)
			getMendixObject().setValue(context, MemberNames.Attachmentss_Root.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Attachmentss_Root.toString(), attachmentss_root.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return rootMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final emiratesservice.proxies.Root that = (emiratesservice.proxies.Root) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "EmiratesService.Root";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
